### ISSUE TITLE
Publish benchmark among other popular navigators

### ISSUE THREAD

**Issue by luong-komorebi** [ajeetdsouza/zoxide#100]
Hi there, I am a new user of your tool. It serves my purpose very well so I appreciate the effort that you are putting into it. 

I do acknowledge that this is your repo and it is your interest to create something to the world. As an end user, I still couldn't help but wonder how it performs next to tools like z.lua, z, etc. and what is its advantages beside being written in Rust. Therefore, I would love it if you share some benchmarks. 

Again, this is totally optional and not really an issue. Just some good motivations that I think would be beneficial to the users of this and the developers who investigate it to contribute more to the development.

**Comment by cole-h** [comment]
Once upon a time, there was a basic claim of the speedup over these other tools. However, one of the developers of another similar project took issue and thought the numbers weren't realistic, which sparked a bit of unfortunate drama; thus, it was removed (and the related issue(s) deleted). I don't want another repeat of that, but if @ajeetdsouza doesn't think this is a problem anymore, it would be easy to add.

There's also the problem that not all systems are made equally -- my numbers might be faster than someone with a Pentium, and someone with a Threadripper might be even faster than me! I can understand that it's nice to see a ballpark, but I think it's better if you test all your choices and decide for yourself.

**Comment by luong-komorebi** [comment]
Thanks, @cole-h for the kind words.
This issue is hence closed. 

I do still believe that there's a value in benchmarks. It s not about ego, dramas or anyone winning someone else. It's about competition that drives everyone concerned to a better reality. 

> There's also the problem that not all systems are made equally -- my numbers might be faster ...

My curiosity is: on the same machine, how would zoxide perform compare to others. There may be trade-offs in each implementation but it is still interesting to see the numbers. You dont even have to claim you are faster than another tool, just showing the raw numbers in specific use cases is good enough. 

Anyway, maybe that is just my personal interest and maintainers are fine to turn it down.

**Comment by luong-komorebi** [comment]
Also, for some background information @cole-h 
This is the PR i m getting in my repo: https://github.com/luong-komorebi/Awesome-Linux-Software/pull/509

And these are the words that is used for it
![image](https://user-images.githubusercontent.com/15828926/89060809-d542dd80-d38d-11ea-8718-e6e3f0135d63.png)
![image](https://user-images.githubusercontent.com/15828926/89060816-d8d66480-d38d-11ea-9b7d-94b6ff5d399c.png)

**Comment by ajeetdsouza** [comment]
Hey @luong-komorebi,

There have been issues in the past, but you do make a valid point. The README  earlier had a blanket claim of being at least 10x faster than other autojumpers. While this was not wrong, the benchmarking process hadn't been made transparent. I think if I created a separate wiki article with my process, system specifications, and results, that would be a much better way to compare, and I don't think a lot of people would take issue with that.

I'm currently quite busy, so I won't be able to work on it anytime soon, but all the same, I'll reopen the issue so I can work on it once I have the time.

**Comment by ajeetdsouza** [comment]
Since the creation of this issue, zoxide has become still faster while continuously adding new features. I think it's safe to say that this is a non-goal now.
