### ISSUE TITLE
fish's pwd does not like `-L`

### ISSUE THREAD

**Issue by judu** [ajeetdsouza/zoxide#101]
I installed zoxide tonight and I've started having this error when using `cd`:

```
❯ cd projets/                                                                                                                                         [0][2020-08-05 03:16:16]
pwd: Option '-L' inconnue
- (ligne 45): 
pwd -L
^
dans la substitution de commande
        appelé à la ligne 43 du fichier '-',

dans la fonction '_zoxide_hook',
        appelé à la ligne 5 du fichier '/usr/share/fish/functions/cd.fish',
        avec la liste de paramètres 'VARIABLE SET PWD'

dans le gestionnaire d'événement: gestionnaire pour la variable 'PWD'

       pwdpwd - output the current working directory
        -

   Synopsis
       pwd

pwd: Tapez 'help pwd' pour sa documentation
```

Let me translate that for you: `pwd` complains about not knowing of the `-L` flag.

Turns out that fish has a wrapper around pwd which does not know the `-L` flag. I'm not sure if this should be a fish issue or not. 🤷
(Edit: created an issue on fish's side: https://github.com/fish-shell/fish-shell/issues/7240 )

In the meantime, I found two ways to cope with that.

- The unsafe one:

```
zoxide add (eval (which pwd) -L)
```

- The hardcoded one:

```
zoxide add (/usr/bin/pwd -L)
```

Maybe you have a better idea.

**Comment by cole-h** [comment]
`pwd` is a fish builtin that does indeed have support for the `-L` flag, at least as of 3.1.2. Which version of fish are you using, and what does `type pwd` output? It could be that *you* have a `pwd` wrapper.

**Comment by judu** [comment]
Well, I discovered since then that I'm running an old version of fish :facepalm: 

We can close this issue.
