### ISSUE TITLE
Interactive queries do not stay sorted by score?

### ISSUE THREAD

**Issue by bhipple** [ajeetdsouza/zoxide#102]
When I first startup an interactive query, everything is sorted as expected:

![init](https://user-images.githubusercontent.com/2071583/89716844-9361fa80-d97e-11ea-817c-155341acfcc8.png)

However, when I start typing, this is no longer the case:

![fuzzy](https://user-images.githubusercontent.com/2071583/89716859-a5dc3400-d97e-11ea-835b-05717275c416.png)

Am I just missing some flags to `fzf` or is `zoxide` meant to handle this for me?

**Comment by ajeetdsouza** [comment]
Hey @bhipple,

By default, fzf tries to show the best match for your search first. If you'd like to retain the order provided by zoxide (sorted by score), you can `export _ZO_FZF_OPTS="--no-sort"`.

**Comment by bhipple** [comment]
Thank you!  In my case I went with 

```
export _ZO_FZF_OPTS="--no-sort --reverse --border --height 40%
```
and now it works exactly as I had it working with `z`!

**Comment by kohane27** [comment]
Thank you for such for raising this issue and @ajeetdsouza answering this! I've been baffling by this for weeks and now I'm very happy with the results sorted by scores! Thank you again for creating such an awesome tool!
