### ISSUE TITLE
Glob exclude patterns?

### ISSUE THREAD

**Issue by macintacos** [ajeetdsouza/zoxide#106]
I'd like to specify glob patterns for excluding directories (and any of subdirectories that match the pattern). Is this possible?

**Comment by ajeetdsouza** [comment]
This feature is not currently supported, but it is definitely useful. I will work on this.

**Comment by ajeetdsouza** [comment]
Added in https://github.com/ajeetdsouza/zoxide/commit/5cfcd79c3949b1bd1a7f7d007c322b5d085f53ab.

**Comment by ajeetdsouza** [comment]
Released in zoxide 0.5.0.
