### ISSUE TITLE
Zsh on Ubuntu came across an error when initializing

### ISSUE THREAD

**Issue by spencerwooo** [ajeetdsouza/zoxide#108]
Loading zoxide, i.e., running:

```zsh
eval "$(zoxide init zsh)"
```

gives me:

![image](https://user-images.githubusercontent.com/32114380/93989097-15d23c80-fdbc-11ea-8784-533ae320c385.png)

both inside `.zshrc` and running in the interactive shell. Any idea why? (Also the `z` command aliases don't work obviously.)

**Comment by ajeetdsouza** [comment]
Dupe of https://github.com/ajeetdsouza/zoxide/issues/94.

The problem is that the `zi` alias has already been set (probably by [zinit](https://github.com/zdharma/zinit)). You might want to `unalias zi` first. I'll fix this soon.

**Comment by spencerwooo** [comment]
Oh sorry, I didn't notice that issue. Thanks for the workaround.

**Comment by ajeetdsouza** [comment]
Btw, this is fixed in v0.5.0.
