### ISSUE TITLE
Import the entries from .z

### ISSUE THREAD

**Issue by alaymari** [ajeetdsouza/zoxide#11]
I started using zoxide and am very impressed by its speed compared to other utilities. Am currently using zsh-z. It would be nice if there was a way to import the entries from the earlier $HOME/.z to zoxide database. Any plans on using the existing data?

**Comment by ahmedelgabri** [comment]
a quick & hacky way to populate `zoxide` with the same history (without the ranking) is to generate a long `cd` command from the `~/.z` file & run that command, then `zoxide` history will have the same history.

What you want is to convert this format in `~/.z` file

```
/path/to/directory|6.3435|12333123123
/path/to/directory2|4.3435|595959559
…
```

To this command

```
cd /path/to/directory; cd /path/to/directory; …
```

Which can be done with some regex & search & replace in your favorite editor.

**Comment by alaymari** [comment]
After I posted, thought of going that way. But I would still miss the "frequency" part. Thanks for the tip.

**Comment by ahmedelgabri** [comment]
I'd also like add to the initial request, a way to export to text or maybe even thinking about having a more portable format for `~/.zo` because right now it's a binary & there is no way to migrate that to anything else if/when needed.

**Comment by cole-h** [comment]
The new `zoxide migrate <path/to/z/file>` command has been merged!

If you find any issues with it, please open a new issue and ping me there, and I'll do my best to solve it.

**Comment by ahmedelgabri** [comment]
@cole-h thanks! 

1. There is no new release, so how can I get this change?
2. Can we have an export too?

**Comment by alaymari** [comment]
@cole-h Thanks for implementing what we asked so fast.

As @ahmedelgabri mentions, if there is even a nightly/unstable release, I can try.

**Comment by cole-h** [comment]
If you're using `cargo` to install, all you should need to do to get the update is:

(NOTE: there hasn't been a new release yet which means installing from git is necessary)

1) `cargo install --git https://github.com/ajeetdsouza/zoxide --force` -- the force flag is only necessary if you already have `zoxide` installed in order to overwrite the binary with the updated version
2) Ensure that `~/.cargo/bin` (where `cargo` installs binaries to by default) is in your PATH
3) Enjoy migrating from `z`!

---

About export: I don't see a need for this feature. If you want to see the entries in the database, just `zoxide query -i` (or `zi` if you have the aliases setup). You could even view the database itself, but you won't get much information out of it aside from the directories.

 If someone can convince me otherwise, or @ajeetdsouza thinks it would be nice to have, I can probably take some time to implement it.

**Comment by ajeetdsouza** [comment]
Agreed. I have a few more modifications to make, I will try to make a release tomorrow.

**Comment by ahmedelgabri** [comment]
@cole-h I tried `cargo install --git https://github.com/ajeetdsouza/zoxide --force` & still doesn't seem to pull the latest changes.



> About export: I don't see a need for this feature. If you want to see the entries in the database, just `zoxide query -i` (or `zi` if you have the aliases setup). You could even view the database itself, but you won't get much information out of it aside from the directories.

The reason behind export is for example if someone wants to migrate from `zoxide` to something else, they can export their data & convert it to be used by the other tool without losing it. I couldn't view the database myself, maybe for lack of knowledge on how to view what is inside a binary file.

For example, what made `migrate` possible is that `~/.z` format is very simple to parse & even could be done in a naive way with something like this https://github.com/ajeetdsouza/zoxide/issues/11#issuecomment-597385158

**Comment by ahmedelgabri** [comment]
`migrate` works great thanks @cole-h, one caveat that when I delete `~/.zo` or move it it gets recreated right away. 

This didn't work `~/.zo` was created somehow either before or when `zoxide` ran
```sh
$ rm ~/.zo
$ zoxide migrate ~/.z
```

This worked 🤔 

```sh
$ rm ~/.zo && zoxide migrate ~/.z
```

**Comment by cole-h** [comment]
@ahmedelgabri You're probably sourcing the init script using `zoxide init <shell>` which, by default, hooks into your prompt redrawing. One of the reasons I am an advocate for `PWD`-monitoring hooks by default ;)

I'll think about how we could handle this better. Maybe we could allow overwriting duplicate entries, but requiring a flag, as well as user interaction, for that. E.g. `The path <path> already exists in your database with rank <rank>. Would you like to overwrite it with rank <rank>? [y/N]` with the flag (`-i, --interactive` for interactive migration?), or just printing `path <path> already exists in database -- skipping` without that flag.

---

I think I will abstain from implementing the `exmigrate` subcommand, for now. Sorry.

**Comment by ahmedelgabri** [comment]
@cole-h You could also add a `--force` flag which can simplify things & I'd assume anyone who wants to `migrate` will care more about having the data they are migrating more than the _new_ database.

 

> I think I will abstain from implementing the `exmigrate` subcommand, for now. Sorry.

That's ok, but at least maybe document somehow how can we open the database? :)

**Comment by cole-h** [comment]
I like that. Simpler. Will work on it.

---

For opening the database, all I needed to do was `nvim ~/.zo` (`vim` and `vi` also work), and it shows the unrepresentable bytes along with actual paths:

![image](https://user-images.githubusercontent.com/28582702/76660419-20229c80-6536-11ea-9f12-d0567f2bdd6e.png)

(screenshot from `nvim`)

**Comment by ahmedelgabri** [comment]
> For opening the database, all I needed to do was `nvim ~/.zo` (`vim` and `vi` also work), and it shows the unrepresentable bytes along with actual paths:
> 
> ![image](https://user-images.githubusercontent.com/28582702/76660419-20229c80-6536-11ea-9f12-d0567f2bdd6e.png)
> 
> (screenshot from `nvim`)

That's good enough, thanks!

--- 

> @ahmedelgabri You're probably sourcing the init script using `zoxide init <shell>` which, by default, hooks into your prompt redrawing. One of the reasons I am an advocate for `PWD`-monitoring hooks by default ;)

On this issue, maybe the `zoxide inti <shell>` for `zsh` for example can take advantage of `$chpwd_functions` array. Like how `direnv` works, even though it has an `init` command too that just takes advantage of this. 

Here is the output of `direnv hook zsh` 

```zsh

_direnv_hook() {
  trap -- '' SIGINT;
  eval "$("/usr/local/bin/direnv" export zsh)";
  trap - SIGINT;
}
typeset -ag precmd_functions;
if [[ -z ${precmd_functions[(r)_direnv_hook]} ]]; then
  precmd_functions=( _direnv_hook ${precmd_functions[@]} )
fi
typeset -ag chpwd_functions;
if [[ -z ${chpwd_functions[(r)_direnv_hook]} ]]; then
  chpwd_functions=( _direnv_hook ${chpwd_functions[@]} )
fi
```

vs `zoxide init zsh`

```zsh

_zoxide_precmd() {
    zoxide add
}

[[ -n "${precmd_functions[(r)_zoxide_precmd]}" ]] || {
    precmd_functions+=(_zoxide_precmd)
}

z() {
    if [ "$#" -eq 0 ]; then
        cd "$HOME"
    elif [ "$#" -eq 1 ] && [ "$1" = "-" ]; then
        cd "-"
    else
        _Z_RESULT=$(zoxide query "$@")
        case "$_Z_RESULT" in
            "query: "*)
                cd "${_Z_RESULT:7}"
                ;;
            *)
                echo -n "$_Z_RESULT"
                ;;
        esac
    fi
}


alias zi="z -i"

alias za="zoxide add"
alias zq="zoxide query"
alias zr="zoxide remove"
```

**Comment by cole-h** [comment]
Pretty sure that was introduced very recently here: https://github.com/ajeetdsouza/zoxide/commit/9c8e8da71a03f5c3c070247f5b0bffd971a70f62 :) Rerun the above `cargo install` command to get the updated version, if you haven't already.

`zoxide init zsh --hook pwd`

**Comment by ahmedelgabri** [comment]
Great, thanks!

**Comment by cole-h** [comment]
@ahmedelgabri
