### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by hydrargyrum** [ajeetdsouza/zoxide#113]
I can't find any other documentation than the README, which is itself very scarce.

> zoxide is a blazing fast alternative to cd, inspired by z and z.lua. It keeps track of the directories you use most frequently, and uses a ranking algorithm to navigate to the best match.

Which is almost the only info.

After eval zoxide init, what should we do? What can we do? What are the commands? z/zq? Are there others? What do they do anyway? There is zero help.

```
% z -h
Error: no match found
% zq -h
zoxide-query 0.4.3
Search for a directory

USAGE:
    zoxide query [FLAGS] [keywords]...

FLAGS:
    -h, --help           Prints help information
    -i, --interactive    Opens an interactive selection menu using fzf
    -l, --list           List all matching directories
    -s, --score          Display score along with result
    -V, --version        Prints version information

ARGS:
    <keywords>...    
```

There is just too little info.

**Comment by cole-h** [comment]
There are some potential commands listed here: https://github.com/ajeetdsouza/zoxide#examples

**Comment by hydrargyrum** [comment]
Oh indeed. But a more formal description (a manual page?) would be nice.

**Comment by E3D3** [comment]
The help option could also be a little better.
`za --help`, `zq --help` and `zr --help` works, but not `zi --help`, and instead of `z --help`, we have to use `zoxide --help`.

**Comment by ajeetdsouza** [comment]
I've added manpages for each zoxide subcommand. Do let me know if there's anything else you'd like me to include.
