### ISSUE TITLE
Repo topics: xonsh, xontrib

### ISSUE THREAD

**Issue by anki-code** [ajeetdsouza/zoxide#115]
Hello! zoxide is great! Thanks!

But why the repo has `xonsh` and `xontrib` topics? :)

I'm not against the grey promo technologies and just want to ask to remove it after some time if it is really unrelated. If it's related please add [xonsh](https://github.com/xonsh/xonsh) and [xontrib-zoxide](https://github.com/dyuri/xontrib-zoxide) mention to the README to show the motivation of adding this topics.

Thanks!

**Comment by ajeetdsouza** [comment]
Hey @anki-code, I added the tags because zoxide now supports the xonsh shell on master, and has been [added](https://github.com/xonsh/xonsh/pull/3927) to the list of xontribs. I'm hoping to make a release over the weekend.

**Comment by anki-code** [comment]
Got it! Thanks! Hope your release will be best!

**Comment by ajeetdsouza** [comment]
Thanks! I noticed you contribute to the xonsh shell, so in case you'd like to see the code for it, I've added it [here](https://github.com/ajeetdsouza/zoxide/blob/master/templates/xonsh.txt). Feedback would be appreciated!

**Comment by anki-code** [comment]
@ajeetdsouza I had a quick look to the code. I don't know the step by step use case and I could be wrong but just one note: if zoxide support will be a xontrib which wiritten using xonsh api (be a `.py` file with `__xonsh__.*` or `import xonsh` calls) it could be automatically compiated by Python (as `.pyc` file) and initilize and work faster. 

In case of execx-ing the code every time it will be compiled every time so it's additional loading time in xonshrc. 

May be I don't know some details why this approach was selected.

**Comment by anki-code** [comment]
JFYI: xontrib template - https://github.com/xonsh/xontrib-cookiecutter

**Comment by ajeetdsouza** [comment]
The main advantage of having zoxide generate the plugin code is:

- easier version control - we eliminate the possibility that the user has different versions of zoxide and the shell plugin
- we can dynamically change the plugin code based on user preference

The shell plugin itself is barely over 100 LOC, so it's highly unlikely that you will find a noticeable difference with a compiled pyc file.

---

Either way, I like the idea of writing the plugin in pure Python using the xonsh API - it would be more readable, and allow for better static analysis.
