### ISSUE TITLE
zoxide xxh plugins for xxh shells (xonsh, zsh, fish, bash)

### ISSUE THREAD

**Issue by anki-code** [ajeetdsouza/zoxide#116]
hi! zoxide is incredible!

It will be great to create zoxide plugins for [xxh](https://github.com/xxh/xxh) shells i.e.:
* xxh-plugin-xonsh-zoxide
* xxh-plugin-zsh-zoxide
* xxh-plugin-fish-zoxide
* xxh-plugin-bash-zoxide

Thanks!

### For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by ajeetdsouza** [comment]
Hey @anki-code, xxh looks great! I'm not sure how xxh internals work, but I'd be willing to help out if you want to work on this.

**Comment by anki-code** [comment]
I've added zoxide as xxh-prerun-plugin:

### [xxh-plugin-prerun-zoxide](https://github.com/xxh/xxh-plugin-prerun-zoxide)

Now anyone can xxh-ing to the host and do `z` :)

**Comment by ajeetdsouza** [comment]
This is fantastic, thank you!
