### ISSUE TITLE
"--no-aliases" flag breaks "--cmd" one

### ISSUE THREAD

**Issue by Crandel** [ajeetdsouza/zoxide#118]
I use `zoxide init --cmd j --no-aliases zsh` command to init zoxide, because `z` alias used by zinit. Also I have `jq` for working with json files. Latest update broke behavior and now zoxide is not working at all. 
I use this workaround as a temporary fix, but it would be nice to configure aliases more, maybe using config file
```
eval "$(zoxide init --cmd j --no-aliases zsh)"
__zoxide_unset 'j'
j() {
  __zoxide_z "$@"
}
__zoxide_unset 'ji'
ji () {
  _zoxide_result="$(zoxide query -i -- "$@")"  && _z_cd "$_zoxide_result"
}
```

**Comment by ajeetdsouza** [comment]
Hey @Crandel,

`zoxide --no-aliases` no longer defines any aliases. This is to allow a user to have full flexibility when choosing which aliases they would like on their system.

I think this configuration should work for you:
 
```shell
eval "$(zoxide init --no-aliases zsh)"

alias j='__zoxide_z'
alias ji='__zoxide_zi'
```

**Comment by Crandel** [comment]
OK, looks good for me
