### ISSUE TITLE
Match fzf default Ctrl + R settings

### ISSUE THREAD

**Issue by SuperSandro2000** [ajeetdsouza/zoxide#123]
I was really puzzled when the fzf integration did not look like my Ctrl + R binding despite the the same environment variable being used. It turns out that fzf has two default settings (``--height ${FZF_TMUX_HEIGHT:-40%} --reverse`` https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash#L21) which I think should be also used here to match the user expectations. Any later argument is overwriting the defaults.

I am not fluent in rust. I did research that the change should probably be made here https://github.com/ajeetdsouza/zoxide/blob/master/src/fzf.rs#L21 but I am unsure how.

As an alternative until this is added I am just going to change my ``$FZF_DEFAULT_OPTS`` env.

**Comment by ajeetdsouza** [comment]
Hey @SuperSandro2000,

By default, zoxide keeps the default behavior of fzf. The default zoxide options for fzf may be changed in a future release, but if you'd like to customize it yourself, you can use the `_ZO_FZF_OPTS` environment variable.

`zoxide init --help` has some documentation on environment variables.

**Comment by SuperSandro2000** [comment]
I just added the default ops to ``FZF_DEFAULT_OPTS``.
