### ISSUE TITLE
Antigen instructions wrong?

### ISSUE THREAD

**Issue by tocklime** [ajeetdsouza/zoxide#13]
In readme.md, antigen instructions say to 
```
antigen bundle zsh-users/zsh-syntax-highlighting
```

But I don't see how that can work. Indeed, the obvious

```
antigen bundle ajeetdsouza/zoxide
```

Seems to do the trick.

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/6d91b4e3c4941fa43c863cf94e4090549debf4ef, thanks!

**Comment by Slapbox** [comment]
@ajeetdsouza is Antigen install still supported? I see it's no longer mentioned and Antigen seems to fail to install it.

**Comment by ajeetdsouza** [comment]
Antigen was never supported as an installation method. You always need to install the zoxide binary via a package manager, but once that is done, you can use `eval "$(zoxide init zsh)"` in your config file, or you can call `antigen bundle ajeetdsouza/zoxide`, which will do this for you.

**Comment by Slapbox** [comment]
Thanks for your reply @ajeetdsouza! Is there any way to bundle zoxide into a one-click zsh installer? For example, on Cygwin there's no package manager available and with `winget` I get some error about the operation not being supported - though I don't have the error text handy.

**Comment by ajeetdsouza** [comment]
Does the default installer in the README not work?

```
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

**Comment by Slapbox** [comment]
You know what, it probably will. I foolishly looked under Windows, forgetting Cygwin is more like Linux. Thanks for the tip - I'll report back if that fails, but I assume it will work.

**Comment by ajeetdsouza** [comment]
I've never tried it with Cygwin before, do let me know if it works so I can add instructions to the README.

**Comment by Slapbox** [comment]
I believe the only issue is that the `zoxide.exe` is not having the executable permission properly set. I still have a little more testing to do later though.

**Comment by ajeetdsouza** [comment]
Oh, that's awesome. I've added chmod to the install script, and put a line in the README. Thanks for reporting this issue!
