### ISSUE TITLE
Broken pipes are not handled elegantly

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#137]
Thanks @kidonng for pointing this out!

To reproduce, run the following with more than 1 entry in the database:

```sh
zoxide query -l | head -n1
```

The output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/cmd/query.rs:64:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is a simple fix - replacing 

```rust
println!("foo");
```

with

```rust
writeln!(std::io::stdout(), "foo").context("could not write to stdout")?;
```

And later handling `io::ErrorKind::BrokenPipe`. However, handling printing errors everywhere would make the code unnecessarily verbose, so it's worth looking into how we can make this more elegant.

**Comment by daizeng1984** [comment]
got random error message. I guess they are related?:
```
Error: could not write to fzf                                                                                                                                                                                                                                                                                                                                                                                     
Caused by:                                                                                                                                                                                                   Broken pipe (os error 32)
```

**Comment by ajeetdsouza** [comment]
That is related, although I've never seen the issue with fzf before. What were your exact steps?

**Comment by daizeng1984** [comment]
is there way to see logs? It's random for me. Suspect it happens my initial use after not using it for a while.

**Comment by ajeetdsouza** [comment]
fzf is closing the pipe before zoxide finishes writing to it - chances are you have a lot of directories in zoxide and you either selected something in fzf or exited fzf early. The cause is the same as the issue described above, I'll fix it soon.
