### ISSUE TITLE
[Feature Request] Exclude current directory from candidates

### ISSUE THREAD

**Issue by 0xC0FFEE** [ajeetdsouza/zoxide#139]
Thanks for writing this plugin!

Often the following situation happens to me: I want to switch to the folder `foo`, so I run `z foo`. However I realize that I'm in the wrong folder (`cd`ed into `/a/foo`, however I wanted to go to `/b/foo`). In `z.lua` I could re-run `z foo` and the current working directory would be excluded from the candidates, so I'd navigate to `/b/foo`. In `zoxide` this is not the case, so re-running `z foo` is basically a nop. Instead I've to run `zi foo` and select the correct folder.

FWICT there should be no use-case to `cd` into the current working directory again, so changing this behavior to `cd` into the next best match should not break any existing use-cases.

**Comment by ajeetdsouza** [comment]
Agreed, this should be default behaviour. If a user wants to cd into the same directory (for example, I sometimes need to do this when the directory I'm in has been deleted and recreated by a testing script), they can just use `z .`.
