### ISSUE TITLE
Go to $HOME without args

### ISSUE THREAD

**Issue by xynxynxyn** [ajeetdsouza/zoxide#14]
`cd` goes to the home directory when invoked without args. Maybe `z` could do the same?

**Comment by ajeetdsouza** [comment]
This is a good idea, I will add this in the next release!

**Comment by ajeetdsouza** [comment]
Added in https://github.com/ajeetdsouza/zoxide/commit/f0c5e28fd7e56d7cec045a40154ab4768339da44.

**Comment by vict0rsch** [comment]
Keep in mind, the original `z` shows you the current ranking. Which is also a nice feature. Not sure if it's worth not implementing @xynxynxyn's suggestion, but just wanted to point that out as `cd` does already get you home
