### ISSUE TITLE
Error message when aliasing cd to z

### ISSUE THREAD

**Issue by Anomalocaridid** [ajeetdsouza/zoxide#140]
If I alias `cd` as `z` with the line `alias cd="z"` in `zsh` (whether it's in `.zshrc` or manually run as a command), then I get the error `__zoxide_cd:11: maximum nested function level reached; increase FUNCNEST?` every time I run `z` regardless if it's with the alias or normally. If `z` uses `cd` internally, then `cd` might be getting interpreted as the alias rather than as the built-in version.

**Comment by ajeetdsouza** [comment]
Thanks for reporting this, I'll work on it soon.

In the meantime, you can fix it on your end by creating the `cd` alias _after_ calling `zoxide init`, rather than before.

**Comment by jan-schaeffer** [comment]
Hi, I'm getting the same issue. First declaring the alias and then installing solves it, but everytime I resource `.zshrc` the issue reappers. Reinstalling zoxide isn't the best option. Any idea on how to fix this permanently?
