### ISSUE TITLE
Ranger plugin

### ISSUE THREAD

**Issue by rif** [ajeetdsouza/zoxide#15]
Thank you for your awesome plugin :)

An excellent addition would be a ranger plugin like this:
https://github.com/skywind3000/z.lua/blob/master/ranger_zlua.py

Thank you

**Comment by ajeetdsouza** [comment]
I've added a basic plugin into https://github.com/ajeetdsouza/zoxide/commit/f31fcf2d1fa7cf4410a455ebf86b50ed5b9fe5f9, just put `zoxide_ranger.py` in `~/.config/ranger/plugins`.

I'll continue to add features as and when time permits, but do let me know if there's anything specific you would like to see in `zoxide-ranger`!
