### ISSUE TITLE
Zoxide creates NUL file when used on MSYS2

### ISSUE THREAD

**Issue by BasixKOR** [ajeetdsouza/zoxide#150]
I know this is a very niche use case, but I thought it's better to report it after all.

After I added zoxide initialization in my fish profile, Zoxide created a NUL file in a working directory.

I believe this can affect users using Git Bash too, since they are based on MSYS2 too.

# Possible fix

Considering fish and bash environments are very likely to have a some kind of POSIX emulation, I think it won't hurt to use `/dev/null` directly instead of changing it based on compliation target.

**Comment by BasixKOR** [comment]
You can read the issue I reported earlier on MSYS2 here: https://github.com/msys2/MSYS2-packages/issues/2347

**Comment by ajeetdsouza** [comment]
Thanks for reporting it, zoxide does aim to support MSYS2 on Windows.

The shells with this problem don't actually support Windows natively, so using `NUL` on Windows was unnecessary. I've created a PR to remove this and use `/dev/null` everywhere.
