### ISSUE TITLE
Question: What units does $_ZO_MAXAGE use ?

### ISSUE THREAD

**Issue by E3D3** [ajeetdsouza/zoxide#153]
What units does `$_ZO_MAXAGE` use ?
I guess that it expects a number of days as integer but the README doesn't tell more than
`$_ZO_MAXAGE: sets the maximum total age after which entries start getting deleted`

**Comment by ajeetdsouza** [comment]
Hey @E3D3, I've added a page explaining this to the [Wiki](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm). Do let me know if you have any further doubts.

**Comment by E3D3** [comment]
Thanks for clarifying this, although I'm not sure if I understand the mechanisme good enough.
Am I right that lowering the value of `_ZO_MAXAGE` will delete less used entries quicker ?

Can you also tell how to get the default value of `_ZO_MAXAGE` ? I can't find/print it in bash by using `$ENV` or `set`, I guess because it is only used in a subshell from one of the help-functions.

**Comment by ajeetdsouza** [comment]
Admittedly, the documentation is lacking. Thanks for reviewing it!

I've added some clarifications to the previous page, and I've added a new page for [configuration](https://github.com/ajeetdsouza/zoxide/wiki/Configuration).

**Comment by ajeetdsouza** [comment]
It doesn't have a unit, it's just the maximum total score of all the directories after which their scores get reduced to 90%. The wiki details the exact algorithm.
