### ISSUE TITLE
Add social preview

### ISSUE THREAD

**Issue by anki-code** [ajeetdsouza/zoxide#155]
Hi! Great tool!

Please add "Social preview" in the repository settings.

Examples you can find here - https://github.com/topics/xonsh

And then check here - https://github.com/topics/xontrib

Thanks!

**Comment by ajeetdsouza** [comment]
Hey @anki-code,

I'm not very good at this kind of stuff, so I really do appreciate pointers like this! I especially loved [xxh's GIF](https://repository-images.githubusercontent.com/219294494/561c6500-0423-11eb-8de3-df840f6a912d) - would you be able to tell me how you created it?

**Comment by anki-code** [comment]
I made the gif manually from the images:
```python
sudo apt install imagemagick
convert -delay 20 -loop 0 *.png myimage.gif
```

**Comment by ajeetdsouza** [comment]
Done. ImageMagick worked great, thanks a lot!
