### ISSUE TITLE
Handle space-separated paths not in the database yet

### ISSUE THREAD

**Issue by eugenesvk** [ajeetdsouza/zoxide#156]
As far as I understood from some quick testing, zoxide handles space separated paths if they've already been visited and added to a database (this is a great improvement over the default cd functionality), so this works (testing in a fish shell within WSL)
```
$ cd "/mnt/c/Program Files"
$ z /mnt/c/Program Files
```
However, for a new folder this `z /mnt/c/Program Files (x86)` would fail with `Error: no match found`
Would it be possible to improve this path handling even further and in those case when the command doesn't match anything in the database (i.e. it's not composed of path snippets that match some real path) it would as a final step still be matched as one complete string and `cd`ed to if the destination exists?

**Comment by ajeetdsouza** [comment]
Hey @eugenesvk,

Arguments in command line utilities are not necessarily separated by a single space. If I get the arguments `["foo", "bar"]`, it's possible that my user may have separated `foo` and `bar` by a single space, a double space, a tab character (`\t`), or some other whitespace (the way arguments are split is shell-dependent). For that reason, joining arguments by a single space is not _correct_, as such.

`z` is intended to be a superset of `cd`, so when something isn't already in the database, you need to `z` into it once while using the actual path. If you're typing out the path by hand, you can use Tab to autocomplete the path (and avoid writing `z /mnt/c/Program\ Files\ (x86)`). If you are copy pasting the path, you can put it in quotes instead (`z "/mnt/c/Program Files (x86)"`).  For that reason, I don't see a lot of utility for this kind of feature either.

If you still want to change this behavior for yourself, you could add initialize zoxide without aliases (`zoxide init --no-aliases`) and modify the `__zoxide_z` function to first check if the arguments form a valid path when joined by a space. zoxide is intended to be hackable, so this should not be too difficult.

**Comment by eugenesvk** [comment]
> If you're typing out the path by hand, you can use Tab to autocomplete the path (and avoid writing z /mnt/c/Program\ Files\ (x86)). If you are copy pasting the path, you can put it in quotes instead (z "/mnt/c/Program Files (x86)"). For that reason, I don't see a lot of utility for this kind of feature either

The utility is precisely to avoid these awful practices of _Tabs_ and _quotes_ as they serve no purpose for such a utility that is z or cd since the only thing expected after `z` is a path, no flags nor anything else, so it's just adds extra inconvenience!

> the way arguments are split is shell-dependent). For that reason, joining arguments by a single space is not correct, as such.

That's true, though it might still be useful to try :)

But I do realize now that it's indeed an impossible feature for `z` since you simply don't get enough information from the shell to ensure a consistently correct behavior
However, it's possible to force my shell to behave better via using the xonsh `!` macro to pass all the separating whitespaces in paths to your utility in a single argument (just like it's done in this [replacement of a cd](https://github.com/eugenesvk/xontrib-cd) that accepts arbitrary paths without the need to tab/quote anything)

**Comment by eugenesvk** [comment]
By the way, am i correct that only `z` and `zi` commands accept no flags?

**Comment by ajeetdsouza** [comment]
`zoxide` itself provides a lot of subcommands and flags for querying, inserting, and importing into the zoxide database. `z` and `zi` are simply shell functions that call zoxide for a particular purpose, so no extra flags are expected from the user.

The other functions (`zq`, `zr`, etc.) don't do anything particularly interesting, so they allow the user to pass flags. However, they are not very useful as aliases, and I'm planning to phase them out in the next major release. They're one-liner aliases, and they're quite easy to define if anyone actively uses them.

If you do want custom behavior, you can simply write a small shell function that calls on zoxide to do the heavy lifting. A lot of people do this, including myself. For example, on my system, if you use `z` and it takes you to the wrong directory, you can call `zz` and go to the next best option.

**Comment by eugenesvk** [comment]
Thanks for the clarification, that's helpful, I guess I'll limit this xontrib to `z`/`zi` then and let the other functions have inconsistent behavior while they are still alive :)

The thing is, though, is that the custom behavior I want to do can only be built on top of an existing alias, I can't actually create a function that achieves it on its own for the same reason you can't do it — functions receive a list of arguments split on whitespace.
What I'm planning to do is replace `z` "in-place" with `z!`, which then treats all the subsequent input as one argument, preserving all of the whitespace. So if there are no flags allowed, it just makes it easier to override, no need to worry about `z -flag` and replacing it with `z -flag!`

Although this raises one __complication__: as far as I understand, `zoxide` doesn't split arguments by whitespace while querying the database, right?
So if I have a `C:\AppData\Test\Space  Folder2` folder in the database and pass the `zoxide query "app test space"`, I get no results because `zoxide` is designed in a way that would assume those arguments would've been split by the shell and fed as 3 separate arguments `app`, `test`, and `space`

__Question:__ Is this something that could be added within `zoxide` or do you believe that the only proper way is for the shell alias function `z` to be modified to account for this (e.g. test if the dir exists and if it doesn't add another step to split the single argument into multiple arguments and feed them as expected to `zoxide`?

**Comment by ajeetdsouza** [comment]
I think this too would be better to add to `z` itself, for a few reasons:

- It's a very specific feature that most people would not find useful, but would affect the complexity of the tool (by adding more options), as well as the complexity of the code (more to maintain).
- It would hurt modularity. Currently, I keep command-specific logic separate - zoxide on its own is a simply query engine for filepaths, and it can be used to define shell functions that behave as desired.
