### ISSUE TITLE
Handle PowerShell Provider Paths

### ISSUE THREAD

**Issue by davidkna** [ajeetdsouza/zoxide#163]
Some paths in powershell are prefixed with strings like for example `Microsoft.PowerShell.Core\FileSystem::` for WSL Paths (`Microsoft.PowerShell.Core\FileSystem::\\wsl$\fedoraremix`) or SMB network shares (`Microsoft.PowerShell.Core\FileSystem::\\NAS\Share`).

A simple fix would be to switch from `(Get-Location).Path` to `(Get-Location).ProviderPath` or strip the prefix. `ProviderPath` wouldn't technically not be a logical path anymore and stuff like [PSDrives](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7.1) would vanish. I think both options could make the path invalid. So it might be best to just accept paths with these prefixes.

For reference [this](https://github.com/starship/starship/blob/dde61f5cf34ee3ea0a59b84720fb82609e409ce7/src/init/starship.ps1#L5-L23) is how starship removes the prefixes.

**Comment by ajeetdsouza** [comment]
We can't store the path as `Microsoft.PowerShell.Core\FileSystem::`, because that is a shell-specific filepath. zoxide would not be able to resolve the path (eg. `C:\foo\..` -> `C:\`), or even verify if the path still exists.

I'm not a Windows user - could you specify how removing the prefix might make the path invalid?

**Comment by davidkna** [comment]
I think the prefix acts a a sort of protocol prefix and removing it could remove the extra information needed to resolve that path.

Also in the case of PSDrives just removing the prefix could still result in a path that is shell specific and which does not exist in the file system. `ProviderPath` isn't set for every kind of provider path, but I think it's more likely to result in a non-shell specific path (albeit one that isn't strictly logical anymore (e.g. `Dev:\` -> `C:\...\mydevfolder`)) and it sounds like zoxide wouldn't want to handle the exceptions.
See also [this document](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_providers?view=powershell-7.1) about providers from ms.

**Comment by ajeetdsouza** [comment]
I've created a PR to fix this. This would refrain from calling `zoxide add` except when using the `FileSystem` provider.
