### ISSUE TITLE
Change this misleading information ASAP

### ISSUE THREAD

**Issue by skywind3000** [ajeetdsouza/zoxide#17]
I am the author of [z.lua](https://github.com/skywind3000/z.lua). change this misleading information asap.

here is my benchmark with both z.lua and zoxide (clear each database at first):

    skywind@weilin0:/tmp$ time _zlua --add /tmp
    real    0m0.025s
    user    0m0.000s
    sys     0m0.016s
    skywind@weilin0:/tmp$ time _zlua --add /tmp
    real    0m0.037s
    user    0m0.016s
    sys     0m0.000s
    skywind@weilin0:/tmp$ time _zlua --add /tmp
    real    0m0.022s
    user    0m0.000s
    sys     0m0.016s
    skywind@weilin0:/tmp$ time ~/software/zoxide add
    real    0m0.026s
    user    0m0.000s
    sys     0m0.000s
    skywind@weilin0:/tmp$ time ~/software/zoxide add
    real    0m0.026s
    user    0m0.000s
    sys     0m0.000s
    skywind@weilin0:/tmp$ time ~/software/zoxide add
    real    0m0.021s
    user    0m0.000s
    sys     0m0.016s

and the result from hyperfine:

    skywind@weilin0:/tmp$ hyperfine 'lua /home/skywind/.local/etc/z.lua --add /tmp' '/home/skywind/software/zoxide add'
    Benchmark #1: lua /home/skywind/.local/etc/z.lua --add /tmp
      Time (mean ± σ):      24.5 ms ±   3.9 ms    [User: 4.0 ms, System: 10.4 ms]
      Range (min … max):    20.2 ms …  44.6 ms    97 runs

    Benchmark #2: /home/skywind/software/zoxide add
      Time (mean ± σ):      17.0 ms ±   3.7 ms    [User: 0.9 ms, System: 6.1 ms]
      Range (min … max):    12.5 ms …  33.1 ms    142 runs

    Summary
      '/home/skywind/software/zoxide add' ran
        1.44 ± 0.39 times faster than 'lua /home/skywind/.local/etc/z.lua --add /tmp'

zoxide is indeed **a little** faster than z.lua, but not **10-20 times**, please remove those words in your documentation.

What a shame to promote your work by dishonor others.

**Comment by ajeetdsouza** [comment]
Copy-pasting my comment from Reddit:

That doesn't look right. What OS are you using? Are you using the `musl` target? Have you built in release mode?

This is what it looks like on my PC:

Adding to database:

```
$ hyperfine "~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide add /tmp"  "~/git/z.lua/z.lua --add /tmp"

Benchmark #1: ~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide add /tmp
    Time (mean ± σ):       0.2 ms ±   0.1 ms    [User: 0.3 ms, System: 0.4 ms]
    Range (min … max):     0.2 ms …   0.9 ms    2328 runs

Benchmark #2: ~/git/z.lua/z.lua --add /tmp
    Time (mean ± σ):       2.7 ms ±   0.2 ms    [User: 1.8 ms, System: 1.0 ms]
    Range (min … max):     2.5 ms …   5.2 ms    744 runs

Summary
    '~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide add /tmp' ran
    10.91 ± 2.80 times faster than '~/git/z.lua/z.lua --add /tmp'
```

Querying:

``` 
    $ hyperfine "~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide query tmp"  "~/git/z.lua/z.lua -e /tmp"

    Benchmark #1: ~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide query tmp
      Time (mean ± σ):       0.1 ms ±   0.1 ms    [User: 0.3 ms, System: 0.3 ms]
      Range (min … max):     0.1 ms …   1.0 ms    2409 runs

    Benchmark #2: ~/git/z.lua/z.lua -e /tmp
      Time (mean ± σ):       2.4 ms ±   0.1 ms    [User: 1.7 ms, System: 0.8 ms]
      Range (min … max):     2.2 ms …   3.9 ms    867 runs

    Summary
      '~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide query tmp' ran
       19.67 ± 9.24 times faster than '~/git/z.lua/z.lua -e /tmp'
```

Even under the assumption that you are using the correct build targets, I do understand that the difference in performance might be less dramatic on a slower system. However, as it still does run faster, I do not see the need for the aggression in your reply.

**Comment by skywind3000** [comment]
just a little hint, please change:

    /path/to/z.lua --add /tmp

to:

    lua5.3 /path/to/z.lua --add /tmp

The first one is not the right command used in z.lua, it will start a bash/zsh process at first then the bash/zsh process would parse the first line of `z.lua` and start lua5.3 for it.

The second one will not start bash/zsh, which is the command used in z.lua .

**Comment by cole-h** [comment]
![image](https://user-images.githubusercontent.com/28582702/77024242-42a82180-694b-11ea-9daa-144314b12f67.png)

Here are my results (with the query commands).

**Comment by skywind3000** [comment]
query is less important, it will only happens when people run a `z` command, nobody can tell the difference between 2ms or 0.2ms.

what is your result in `--add` ??

**Comment by ajeetdsouza** [comment]
I don't see your point - 10x is still a lot faster, especially when we're talking about **milliseconds**. However, I don't want this repository to turn into a pissing contest between `zoxide` and `z.lua`, since:
- I have different plans for `zoxide`
- @skywind3000 is being needlessly aggressive and petty about this, as he demonstrated in [#40](https://github.com/ajeetdsouza/zoxide/issues/40) (now deleted).

I'm deleting this issue. @skywind3000, I've removed the benchmarks from the README, so stay off my repo.
