### ISSUE TITLE
One-liner install instruction doesn't work

### ISSUE THREAD

**Issue by kolmone** [ajeetdsouza/zoxide#172]
I am trying to install zoxide with the one-liner on a Raspberry Pi 4 running Raspberry Pi OS, but the script gets stuck here when trying to install Rust:
```
❯ curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh | sh
No binaries are available for your CPU architecture (armv7l)
Compiling from source...
Cargo will be installed.
```
However separately downloading the script and running it works fine:
```
❯ curl https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh --output install.sh
❯ chmod +x install.sh
❯ ./install.sh
Compiling from source...
Cargo will be installed.
Is this okay? (y/N): y
info: downloading installerr

Welcome to Rust!
...
```
Obviously this is not a huge issue since in the end I was able to install zoxide, but it would be nice if the given instructions worked here too (and to know what is different between the two methods).

**Comment by ajeetdsouza** [comment]
Hey @kolmone, thanks for reporting this issue! I've opened up https://github.com/webinstall/webi-installers/pull/223, which should fix this issue.

**Comment by ajeetdsouza** [comment]
@kolmone, this issue should be fixed now. zoxide has been added to `webi`, and I've added the new instructions to the README.
