### ISSUE TITLE
Use zinit to install binary

### ISSUE THREAD

**Issue by DanKGooGLy** [ajeetdsouza/zoxide#175]
How would I use zinit to install the zoxide binary from github releases? I currently have 
```
zinit wait"1" lucid as"command" for \
    (other command binaries)
    from"gh-r" mv"zoxide* -> zoxide" pick"zoxide/zoxide" \
        ajeetdsouza/zoxide

**Comment by ajeetdsouza** [comment]
Hey @DanKGooGLy, if you found the solution to this, could you share it here? I think other zinit users might find this useful.

**Comment by DanKGooGLy** [comment]
I wasn't able to find an actual solution, so I used cargo to install zoxide. Would you like me to investigate some more?

**Comment by m-wynn** [comment]
```
zinit ice wait"2" as"command" from"gh-r" lucid \
  mv"zoxide*/zoxide -> zoxide" \
  atclone"./zoxide init zsh > init.zsh" \
  atpull"%atclone" src"init.zsh" nocompile'!'
zinit light ajeetdsouza/zoxide
```

**Comment by ajeetdsouza** [comment]
Thanks, @m-wynn!

**Comment by defaude** [comment]
On my system, I got a warning using the above snippet by @m-wynn . I guess the directory structure of the released package has changed a bit?

I got rid of the warning by simply dropping the `mv` part:

```shell
zinit ice wait"2" as"command" from"gh-r" lucid \
  atclone"./zoxide init zsh > init.zsh" \
  atpull"%atclone" src"init.zsh" nocompile'!'
zinit light ajeetdsouza/zoxide
```
