### ISSUE TITLE
Cd to previous directory `z -` is broken in fish

### ISSUE THREAD

**Issue by comfortablynick** [ajeetdsouza/zoxide#178]
After  https://github.com/ajeetdsouza/zoxide/commit/7b00d5a42331b03c8cb367adfd5678a7a7e8b329, the command `z -` no longer works. I think this is because the logic for the directory stack is in a [fish function](https://github.com/fish-shell/fish-shell/blob/a918cabf5e1c148bbdde81213016e852a21914a4/share/functions/cd.fish#L21).

```
$ z -
cd: The directory “-” does not exist

$ builtin cd -
cd: The directory “-” does not exist
```

To test, I redefined `__zoxide_cd`:
```fish
function __zoxide_cd
      cd $argv; and commandline -f repaint
end
```

(Using `builtin commandline` is probably unnecessary since the authors of fish shell only use `commandline`.)

**Comment by ajeetdsouza** [comment]
Hey @comfortablynick, thanks for reporting this issue!

I had changed it to `builtin cd` to make something like this possible:

```fish
function cd
    z $argv
end
```

Using `builtin` everywhere reduces ambiguity, and would have allowed fish users to do something like this. Unfortunately, the fact that fish already includes wraps their own `cd` builtin complicates this.
