### ISSUE TITLE
Brew / AUR packages

### ISSUE THREAD

**Issue by PhilsLab** [ajeetdsouza/zoxide#18]
I'd love to see this tool as brew package as well as on the arch user repository.

**Comment by kseistrup** [comment]
Already in AUR: https://aur.archlinux.org/packages/zoxide

**Comment by jkaan** [comment]
I could help with making this available as a brew package, although I am not entirely sure how to do it.

**Comment by ptzz** [comment]
Looks like `brew` has to wait a bit:

```
~$ brew audit --new-formula zoxide
zoxide:
  * GitHub repository too new (<30 days old)
Error: 1 problem in 1 formula detected
```

**Comment by jkaan** [comment]
I've figured out that it is possible if we create our own tap. We would need a repository that starts with homebrew-zoxide since then it works nicely with `brew tap`.

@ajeetdsouza Would you be able to create that repo, I can do the rest :).

**Comment by ajeetdsouza** [comment]
@jkaan [Done!](https://github.com/ajeetdsouza/homebrew-zoxide)

**Comment by jkaan** [comment]
@ajeetdsouza Can't fork the repo or clone it since it is empty apparently :o. I have it working locally though!

**Comment by ajeetdsouza** [comment]
Whoops! I've added a LICENSE file there, you should be able to fork it now.

**Comment by jkaan** [comment]
@ajeetdsouza Here it is: https://github.com/ajeetdsouza/homebrew-zoxide/pull/1 !

**Comment by ajeetdsouza** [comment]
@jkaan, instead of using a URL to download a tarball and building it, why not directly use `cargo install zoxide`? In fact, you could even use the install script from this repository itself, which will download prepackaged binaries from GitHub.

**Comment by ajeetdsouza** [comment]
@PhilsLab, both packages are created!
