### ISSUE TITLE
zq -l` doesn't exist as shown in the readme gif

### ISSUE THREAD

**Issue by OleStrohm** [ajeetdsouza/zoxide#184]
In the first gif of the readme `zq -l` is showcased, however this doesn't actually exist. `zoxide query -l` does however work, but the shorthand is a lot nicer to use.

Reading through the rest of the readme it seems this is intentional, if so you may wish to update the gif in the readme, as it seems like `zq -l` is a command.

**Comment by jsumner** [comment]
This was removed in version 0.6.0.  From the changelog:
>     **Removed**
>     Aliases: za, zq, zqi, zr, zri. These are trivial aliases to zoxide that can easily be defined manually, and aren't very useful to most users.

zq was just (effectively) an alias to "zoxide query" - if you really want you could add back in yourself :)

**Comment by ajeetdsouza** [comment]
Hey, I've just updated the README. Sorry about the delay!
