### ISSUE TITLE
Manpages aren't installed with `nix-env -i`

### ISSUE THREAD

**Issue by whonore** [ajeetdsouza/zoxide#188]
```sh
nix-env -i zoxide
man zoxide
# No manual entry for zoxide
```

I think all that needs to be done is to add a `postInstall` hook that calls `installManpage` in https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/zoxide/default.nix.

See [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/exa/default.nix) and [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/bat/default.nix) for similar examples.

**Comment by ajeetdsouza** [comment]
Hey @whonore, this is not possible yet because manpages were added very recently (the current stable release of zoxide did not include them). Once there is a new release, we can add manpages to Nix and other package managers.

**Comment by whonore** [comment]
Great, thanks. Feel free to close this issue then or leave it open as a reminder.

**Comment by ajeetdsouza** [comment]
Looks like this has been added [here](https://github.com/NixOS/nixpkgs/commit/ab92ec63d29361d8632d89d318d915d974f40c54).
