### ISSUE TITLE
`zoxide remove` should accept multiple paths

### ISSUE THREAD

**Issue by kidonng** [ajeetdsouza/zoxide#190]
- `zoxide remove` current only accepts one path at a time.
- `zoxide remove -i` only process the first path selected with fzf.

**Comment by ajeetdsouza** [comment]
I've added a PR to allow multi-select for zoxide remove -i. I'm not sure it's a good idea to support this in `zoxide remove` itself:

- It's easily achievable with a simple loop.
- It's not used very often.
- `zoxide remove -i` takes a list of `KEYWORDS`, but `zoxide remove` takes a single `PATH`. Allowing multiple paths here might cause confusion between the two APIs.

**Comment by kidonng** [comment]
> I've added a PR to allow multi-select for zoxide remove -i. 

Thank you! That's impossible to achieve if zoxide doesn't change how it handles the selection.

> - It's easily achievable with a simple loop / multiple invocations.

I don't think that's a good excuse. `rm`, `ls`, `mkdir`, and most programs we use daily takes multiple arguments, and it's counter-intuitive that zoxide is the different one.

> - It's not used very often.

This is a fair point, but it shouldn't take too much effort to implement, right?

> - `zoxide remove -i` takes a list of KEYWORDS, but `zoxide remove` takes a single PATH. Allowing multiple paths here might cause confusion between the two APIs. This way, the single `PATH` is more explicit.

I don't think there is any confusion. By `--interactive` it already means you are **selecting paths**, I don't think people assume `--interactive` will take paths.

> Could you highlight the exact use case for which you want `zoxide remove` to support multiple PATHs?

As I said above, I tried to `zoxide remove path1 path2 ...` by nature, since that's how most programs work. And it really confused me when zoxide says it only takes one path.

If you ever changed you mind and decide to make `zoxide remove` takes multiple paths, I suggest doing it to `zoxide add` as well.

**Comment by kidonng** [comment]
@ajeetdsouza Kindly ping since you may have unsubscribed to the thread and not seeing my new comment.

**Comment by ajeetdsouza** [comment]
I'll work on this soon.

**Comment by kidonng** [comment]
@ajeetdsouza you are awesome 🔥, thanks so much

**Comment by ajeetdsouza** [comment]
No problem! 😄
