### ISSUE TITLE
zoxide breaks if used with nushell when navigating inside of files

### ISSUE THREAD

**Issue by Sympel** [ajeetdsouza/zoxide#197]
Nushell has the possibility to enter structured files (.json, .xml, etc.) and navigating inside of them like you would
navigate normally (cd, ls, etc.). When inside a file, `pwd` returns the path inside the file starting from root. If the path
returned by this does not exist inside the actual filesystem outside the file, zoxide displays an error. Even if this would not
happen, adding the current path to zoxide when inside a file is not desired behavior, since zoxide cannot enter it anyways.

I fixed this on my system by updating the `__zoxide_hook` function in the `zoxide.nu` file:
```
def __zoxide_hook [] {
    if $(shells | where active == $true | get name) == filesystem {
        zoxide add -- $(pwd)
    } { }
}
```

The condition checks if the current shell is inside of the regular filesystem and does not call `zoxide add` if not.

**Comment by ajeetdsouza** [comment]
Thanks for reporting this! I've created a PR to fix this.
