### ISSUE TITLE
Order multiple patterns in `z foo bar`

### ISSUE THREAD

**Issue by c02y** [ajeetdsouza/zoxide#205]
For path like `/path/foo/abc/bar`, is it able to get the path using random order in multiple patterns for `z`?

For example, is it better that both `z foo bar` and `z bar foo` work to get `/path/foo/abc/bar`, currently `z bar foo` fails to find `/path/foo/abc/bar`

**Comment by ajeetdsouza** [comment]
Hey @c02y, which shell are you using?

**Comment by c02y** [comment]
fish-shell

**Comment by ajeetdsouza** [comment]
zoxide matches patterns in order, and I don't have plans to change that at the moment. However, it is also built for scriptability, which means you can just write your own `z` function, like so:

```fish
function z
    set argc (count $argv)
    if test $argc -eq 0
        cd $HOME
    else if test "$argv" = -
        cd -
    else if begin
            test $argc -eq 1; and test -d $argv[1]
        end
        cd $argv[1]
    else
        set -l result (zoxide query -l --exclude (__zoxide_pwd))
        for keyword in $argv
            set result (printf '%s\n' $result | string match -aei $keyword)
        end
        if test (count $result) -eq 0
            echo "zoxide: no match found"
            return
        end
        cd (echo $result[1])
    end
end
```
