### ISSUE TITLE
WIP: new syntax in nushell

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#208]
Hey @ajeetdsouza ,
Just dropping by to let you know that we're working on changing some of the syntax in `nushell`. The two PRs below contain some breaking changes. We just released build `0.31.0` yesterday (5/11/2021). With build `0.31.0` your existing integration code still works. These new breaking changes start in build `0.31.1`.  

[Simplify expressions](https://github.com/nushell/nushell/pull/3389)
[Simplify string interpolation](https://github.com/nushell/nushell/pull/3401)

What I had to do to get the `.zoxide.nu` script working this morning, after building from main, was to replace all `$(` with `(`. After I did that it worked just fine. We plan on releasing these changes in `0.32` approximately 3 weeks from now.

We're still experimenting so things may change in the next 3 weeks. If you don't mind, I'll try to keep updating here if there are further breaking changes that affect `zoxide`. Feel free to come hang with us on [Discord](https://discord.gg/NtAbbGn) while we figure work on our latest changes.

**Comment by ajeetdsouza** [comment]
Sounds good, thanks @fdncred!

**Comment by ajeetdsouza** [comment]
Hey @fdncred, now that support for Nushell 0.32.0 has been merged, I'm closing this issue. Do create another issue if any breaking changes come up in future.

**Comment by fdncred** [comment]
Thanks!

**Comment by nightscape** [comment]
Hi @ajeetdsouza, could you create a new release including this change?
Afais package managers like `brew` haven't picked up the change yet.

**Comment by ajeetdsouza** [comment]
@nightscape I just release v0.7.1 with the Nushell update, hopefully brew picks it up soon.
