### ISSUE TITLE
Move ranger plugin to its own repository and rename ranger.py to __init__.py to simplify installation

### ISSUE THREAD

**Issue by Anomalocaridid** [ajeetdsouza/zoxide#215]
Ranger at some point added the ability to load plugins that are within directories inside the plugins folder. This requires that the entry file is named \_\_init__.py. This would simplify installing and updating plugins by only requiring that users clone the plugin repository into the plugins folder without needing to copy the plugin files into the plugins folder every time the plugin gets updated.

Edit: fixed formatting error.

**Comment by ajeetdsouza** [comment]
Hey @Anomalocaridid, you can use the better-maintained [`ranger-zoxide`](https://github.com/jchook/ranger-zoxide) plugin instead. I've added a link in the [README](https://github.com/ajeetdsouza/zoxide#third-party-integrations) as well.

**Comment by Anomalocaridid** [comment]
Thanks a lot!
