### ISSUE TITLE
Print full path of the directory jumped to

### ISSUE THREAD

**Issue by NerdyPepper** [ajeetdsouza/zoxide#22]
Would you consider having an option like `_ZO_VERBOSE` that would print the full path of the directory that `z` picked?

```sh
$ z tr
/home/np/rustuff/track
```

Feel free to close this issue if it has already been implemented, I am not the most attentive of readers ;)

**Comment by ajeetdsouza** [comment]
I'm not sure I see a use case for this. Why not configure your prompt to show the current directory instead?

**Comment by NerdyPepper** [comment]
>I'm not sure I see a use case for this.

I currently use a shortened version of `$PWD` in my prompt, to save horizontal space:

```
/home/np/rustuff/eva/src/lex/mod.rs  ->  ~/r/e/s/l/mod.rs
```

It gets a little confusing though, when I jump directories. Previously, I used to use [`autojump`](https://github.com/wting/autojump), which provided an indication as suggested above. Perhaps users who have the entire `$PWD` can go ahead and disable the flag.

**Comment by ajeetdsouza** [comment]
I've added it in https://github.com/ajeetdsouza/zoxide/commit/8ca49ea211b1d13994806cc3c1b579c0e334d1a9, you'll be able to use it in the next release!
