### ISSUE TITLE
feature: jump to next match on next z

### ISSUE THREAD

**Issue by orefalo** [ajeetdsouza/zoxide#229]
I use jump today
https://github.com/gsamokovarov/jump

A great feature is Reverse jump, or the ability to jump to the next match with a simple 'z' command

would be nice to have a similar feature.

**Comment by ajeetdsouza** [comment]
@orefalo the `z` command excludes the current directory. If you re-run the previous `z` command (which is basically <kbd>UpArrow</kbd>+<kbd>Return</kbd>), it will take you to the second match.

**Comment by orefalo** [comment]
I will close this one: as this seems to be an expected behavior.

Just saying that when calling z,
  it is more useful to jump to the next match, than to the home folder

I can use cd for the latest.
