### ISSUE TITLE
Adding to nix/nixpkgs

### ISSUE THREAD

**Issue by ysndr** [ajeetdsouza/zoxide#23]
Hi
I have opened a pull request over on [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/pull/82282) for inclusion of this tool in the nix package repo.

**Comment by ajeetdsouza** [comment]
Thank you!

**Comment by ysndr** [comment]
Merged now!

**Comment by ajeetdsouza** [comment]
Thank you!
