### ISSUE TITLE
Jump if one result if more open query interactive mode

### ISSUE THREAD

**Issue by yoann9344** [ajeetdsouza/zoxide#232]
Hello !
I haven't seen any configuration to jump if there's only one result, and if there's more then open the interactive mode.
So I'm using an inefficient bash script to obtain this behavior :
```bash
# eval "$(zoxide init zsh)"
function z() {
    query=`zoxide query --list $1`
    query_length=`echo $query | wc -l`
    if test $query_length -eq 1
    then
        cd "$query"
    else if test $query_length -gt 1
        zoxide query -i $1
    fi

}
```
Would it be possible to add this behavior in the config ?

**Comment by ajeetdsouza** [comment]
Hey @yoann9344, if you set `_ZO_FZF_OPTS='--select-1'`, the interactive `zi` command actually behaves as you'd expect. In future versions of `zoxide`, this flag will be set by default.

**Comment by yoann9344** [comment]
Perfect ! Merci beaucoup ! :)

```bash
_ZO_FZF_OPTS='--select-1'
eval "$(zoxide init zsh)"
alias z='zi'  # ;D
```
