### ISSUE TITLE
`zi` does not work

### ISSUE THREAD

**Issue by liebkne** [ajeetdsouza/zoxide#234]
When I call `zi xxx`, it always echoes `zoxide: no match found`. 

However, `__zoxide_zi xxx` does work properly.

- `fzf --version`: 0.27.2 (brew)
- `bash --version`: GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
- OS: 11.3.1 (20E241)

**Comment by ajeetdsouza** [comment]
Hey @liebkne, can I get your ```zoxide --version```` as well?

**Comment by liebkne** [comment]
Oh, I missed that...its' `zoxide: stable 0.7.2 (bottled)` installed by `brew`.

**Comment by ajeetdsouza** [comment]
Strange, it seems to be working fine for me.

1. Could you share your `.bashrc` (at least the part where you're sourcing zoxide)?
2. What's the output of `type __zoxide_zi` and `type zi`?

**Comment by liebkne** [comment]
Here you go!

```
 $ type __zoxide_zi
__zoxide_zi is a function
__zoxide_zi ()
{
    \builtin local __zoxide_result;
    __zoxide_result="$(zoxide query -i -- "$@")" && __zoxide_cd "${__zoxide_result}"
}

 $ type zi
zi is aliased to `z -i'
```

and the `.bashrc` is [here](http://dpaste.com/C8H92KFMV).

**Comment by liebkne** [comment]
Wow, you're right. I forgot to remove the settings for `z.lua`... Sorry.

```
alias zz='z -c'      # restrict matches to subdirs of $PWD
alias zi='z -i'      # cd with interactive selection
alias zf='z -I'      # use fzf to select in multiple matches
alias zb='z -b'      # quickly cd to the parent directory
```

**Comment by ajeetdsouza** [comment]
Not a problem! I'll add some code to remove predefined aliases when initializing zoxide, so that this doesn't happen in future.

**Comment by tutods** [comment]
I'm using fish and the zi command dind't work.
How to fix it?

**Comment by ajeetdsouza** [comment]
@tutods please open a fresh issue with more details.
