### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by AckslD** [ajeetdsouza/zoxide#236]
If I renamed some of my common directories, is it possible to edit the database in some way to reflect this without loosing the current scores?

**Comment by AckslD** [comment]
Thanks for your reply @ajeetdsouza! That would indeed be great I think!

**Comment by kidonng** [comment]
@ajeetdsouza Would you reconsider #133? Once it's implemented, updating database can be archived via export -> edit -> import, and that can be implemented via simple shell scripts.

**Comment by Allaman** [comment]
For anyone finding this issue with a similar problem (migrating from Linux to MacOS and therefore different paths) my workaround was as follows:
1. Export all directories via `zoxide query --all` on my old machine 
2. Running a search and replace over the output.
3. Add the paths on my new machine with the following script. Of course I will loose my scores but I can live with that :) 

```sh
#!/bin/bash

input="$HOME/Downloads/zoxide.txt"
if [[ -f "$_ZO_DATA_DIR/db.zo" ]]
then
  echo "WARNING zoxide db exists"
  echo "Continue?"
  select choice in "Yes" "No"; do
    case $choice in
      Yes ) echo "Going on"; break;;
      No ) exit;;
    esac
  done
fi

while IFS= read -r line
do
  if [[ ! -d "$line" ]]
  then
    echo "WARNING $line does not exist - not adding to database"
  else
    zoxide add "$line"
  fi
done < "$input"
```

**Comment by ajeetdsouza** [comment]
Closing in favour of https://github.com/ajeetdsouza/zoxide/issues/453.
