### ISSUE TITLE
(filtering) Behavior differences with original z

### ISSUE THREAD

**Issue by spamwax** [ajeetdsouza/zoxide#241]
I was just wondering if zoxide aims to behave exactly like the [original z](https://github.com/rupa/z) in terms of `cd`ing into a query that matches partially:

If my database has `/path/partial/end` and I type `z partial`, it would `cd` to that path, which zoxide doesn't do.

**Comment by ajeetdsouza** [comment]
Hey @spamwax, that's intended behaviour - it's easier to remember a folder by its own name than its parent name, and matching results are also more accurate and predictable as a result.

If you really wanted to `z` into a directory explicitly by its parent, you could do something like `z partial /`. The `/` at the end means there are more directories following `partial`.

**Comment by spamwax** [comment]
thanks for the hint
