### ISSUE TITLE
How can i modify ~/.zoxide.nu file?

### ISSUE THREAD

**Issue by hustcer** [ajeetdsouza/zoxide#244]
Hello, Thanks for the great work. And how can I modify the ~/.zoxide.nu file ?
It was overrode after modification automatically. I want to change 
```nushell
build-string (ansi gb) (pwd) (ansi reset) $git "> "
```
to 
```bash
build-string (ansi gb) (pwd | path basename) (ansi reset) $git "> "
```

**Comment by ajeetdsouza** [comment]
Hey @hustcer,

If you use the default prompt in Nushell, you can set `prompt = __zoxide_hook;__zoxide_prompt`, but if you'd like a custom prompt, you can follow the Nushell [docs on prompt configuration](https://www.nushell.sh/book/configuration.html#prompt-configuration) -- zoxide doesn't change anything about this process. The only requirement of zoxide is that you have to add `__zoxide_hook;` before the prompt string that you define.

The `~/.zoxide.nu` file should not be edited, it's generated by zoxide on shell startup. I've [added a line](https://github.com/ajeetdsouza/zoxide/blob/05a95fe5258b7e639277b322d4c3e4485eeb4712/templates/nushell.txt#L4) to `.zoxide.nu` to make this more clear.

**Comment by hustcer** [comment]
Thanks a lot.
