### ISSUE TITLE
Add zoxide: the link webinstall.dev/zoxide is broken

### ISSUE THREAD

**Issue by einverne** [ajeetdsouza/zoxide#245]
It seems the URL to install zoxide is broken.

    curl -sS https://webinstall.dev/zoxide | bash

The URL gives:

    Cannot GET /zoxide

Run the command shows:

``` 
"zoxide" Not found.
 
See https://webinstall.dev/ for featured installers
or https://webinstall.dev/sitemap.xml for a list of all installers
 
Think "zoxide" is something we should have? Let us know:
 
  https://github.com/webinstall/webi-installers/issues/new?title=Add%20zoxide
```

**Comment by ajeetdsouza** [comment]
Noted, thanks! I've created an issue on webinstallers' tracker, it should be fixed soon.

**Comment by ajeetdsouza** [comment]
@einverne the link is back up, so you should be able to use the webinstaller now.
