### ISSUE TITLE
Confusing message when only match is current directory in Fish

### ISSUE THREAD

**Issue by whonore** [ajeetdsouza/zoxide#248]
In the fish shell (and possibly others, I haven't checked), `z dir` where `dir` only matches the current directory prints `"zoxide: no match found"`. This is because [this line](https://github.com/ajeetdsouza/zoxide/blob/main/templates/fish.txt#L73) explicitly ignores `$__zoxide_pwd`. 

This message is confusing since the user didn't explicitly ask for the exclusion and a match does in fact exist. It would be nicer if it instead said something like `"dir only matches the current directory"` or even nothing at all since it isn't really an error to try to navigate to where you currently are.

**Comment by ajeetdsouza** [comment]
Hey @whonore, thanks for reporting this.

Excluding the current directory is a recent feature of zoxide. We figured that not many people would want to jump to the directory they're already in, and those that do could just use `z .` instead.

I understand the error message is confusing at first, but once you understand that zoxide is exclusively looking for matches other than the current directory, the `no match found` message starts to make more sense. For now, I'd say it's a fairly succint error message; I'd be hesitant to change it unless a lot of people find it confusing.

Also -- if you'd like to include `$PWD` in your queries, you can just edit your `z` function and remove the `--exclude $PWD` flag from your `zoxide query`.
