### ISSUE TITLE
(eval):10: parse error near `()'

### ISSUE THREAD

**Issue by vict0rsch** [ajeetdsouza/zoxide#25]
Install went well:

```
⚡️ 14% at 🕙 22:52:00 🚀 ᐅ curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh | sh
Detected target: x86_64-apple-darwin
Downloading zoxide...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617  100   617    0     0   2722      0 --:--:-- --:--:-- --:--:--  2730
100  862k  100  862k    0     0  1157k      0 --:--:-- --:--:-- --:--:-- 3102k
curl: Saved to filename 'zoxide-x86_64-apple-darwin'
Password:
zoxide is installed!
Please ensure that /usr/local/bin is added to your $PATH.
```

Though adding `eval "$(zoxide init zsh)"` to `.zshrc` throws:

```
zsh: defining function based on alias `z'
zsh: parse error near `()'
```

**Comment by crazystylus** [comment]
What version of zsh and zoxide are you using? Could you post up a copy of your .zshrc so that I can try to replicate the scenario? It seems to work fine on my Mac.

**Comment by BlairLeduc** [comment]
I am experiencing the same. I have Oh My Zsh installed and zsh 5.7.1.

**Comment by ajeetdsouza** [comment]
This error occurs if you already have an alias linked to `z` when calling `eval "$(zoxide init zsh)"`. Check that nothing else is using the `z` alias.

**Comment by BlairLeduc** [comment]
That's it!

I had the z plugin installed. I removed the plugin and I am good to go.

Thanks, @ajeetdsouza!

**Comment by ajeetdsouza** [comment]
No worries!

**Comment by vict0rsch** [comment]
Ok removing `z` from Oh-My-Zsh's `plugins` list worked thanks
