### ISSUE TITLE
Incorrect version returning with `--version` for v0.7.4

### ISSUE THREAD

**Issue by mjsteinbaugh** [ajeetdsouza/zoxide#252]
I'm seeing the wrong version return for zoxide built from crates.io:

```sh
cargo install --version 0.7.4 zoxide
zoxide --version
```

```
zoxide v0.11.1-121-gcbba5d0bc6f6
```

Anything I need to change configuration to fix this?

**Comment by mjsteinbaugh** [comment]
For reference, the same version installed from Homebrew returns the correct version string (see [`recipe`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/zoxide.rb) for details).

**Comment by ajeetdsouza** [comment]
Hm, that's strange. zoxide hasn't ever had a v0.11 and the commit ID referenced there does not exist.

Are you sure you're running the binary from the correct location? I tried `cargo install --version 0.7.4 zoxide` just now (I'm on macOS) and then ran `~/.cargo/bin/zoxide -V` and it worked just fine.

**Comment by mjsteinbaugh** [comment]
Super weird, right?

OK so I did some sleuthing this morning, nuking my Rust install and starting from scratch on macOS 11.5.1, rustup 1.24.3, rustc 1.54.0.

I'm seeing this error reproduce, now with a different version string.

```sh
cargo install --version 0.7.4 zoxide
zoxide --version
```

```
zoxide v0.11.1-128-g7c5c74dfda14-dirty
```

Trying to track down the culprit, it looks like there could be something going on with `askama_shared`.

```sh
fd 0.11.1 | sort
```

```
registry/cache/github.com-1ecc6299db9ec823/askama_shared-0.11.1.crate
registry/src/github.com-1ecc6299db9ec823/askama_shared-0.11.1
```

See related links:

- https://crates.io/crates/askama_shared
- https://github.com/djc/askama

Here's a link to my [Rust configuration script](https://github.com/acidgenomics/koopa/blob/main/lang/shell/bash/functions/common/install/rust.sh#L24), for reference.

Best,
Mike

**Comment by ajeetdsouza** [comment]
Created a PR that runs git in the correct directory, as well as avoids running git entirely for release builds.

**Comment by mjsteinbaugh** [comment]
Can confirm this is working for me now:

```sh
cargo install --git 'https://github.com/ajeetdsouza/zoxide'
zoxide --version
# zoxide v0.7.4
```

Thanks!
