### ISSUE TITLE
got error with elvish shell on windows version

### ISSUE THREAD

**Issue by xBLACKICEx** [ajeetdsouza/zoxide#254]
![picture](https://user-images.githubusercontent.com/51036094/129980007-2a118247-3bdd-414a-9cae-d936ea1c5d9f.png)

OS: Windows 11 Pro 
OS build 22000.132
elvish version: 0.16.0-dev.22ad09cc9355b870d218d38ba2101b27887c277e
zoxide: install by scoop, version v0.7.4

**Comment by ajeetdsouza** [comment]
I'm not able to reproduce this, the same command is working fine for me on Windows. Are you able to reliably reproduce this? This is the definition of the `z` function:

```elvish
fn __zoxide_z [@rest]{
    if (builtin:eq [] $rest) {
        __zoxide_cd ~
    } elif (builtin:eq [-] $rest) {
        __zoxide_cd (builtin:get-env __zoxide_oldpwd)
    } elif (and (builtin:eq (builtin:count $rest) 1) (path:is-dir $rest[0])) { # <- this is what should have executed
        __zoxide_cd $rest[0]
    } else {
        __zoxide_cd (zoxide query --exclude $pwd -- $@rest)
    }
}
```

In your case, you passed one argument that was a valid directory, so the 3rd condition should have been executed, but from the stacktrace it looks like it fell back to the 4th condition. I'm trying to figure out why the 3rd condition failed. Can you run `use path; path:is-dir ".\.azure\"` and see if you get `$true`?

---

Note to self: try to improve errors on Elvish so that "no match found" does not result in a stacktrace.

**Comment by xBLACKICEx** [comment]
Sorry, I don't know where to put __zoxide_z , so i putted in rc.elv

and here is the output

![图片](https://user-images.githubusercontent.com/51036094/130316557-db10d770-679b-45c7-900a-d0697229f26f.png)

![图片](https://user-images.githubusercontent.com/51036094/130316901-ff041035-af40-4a7a-8874-75b4a50f73b6.png)



> 
> 
> I'm not able to reproduce this, the same command is working fine for me on Windows. Are you able to reliably reproduce this? This is the definition of the `z` function:
> 
> ```
> fn __zoxide_z [@rest]{
>     if (builtin:eq [] $rest) {
>         __zoxide_cd ~
>     } elif (builtin:eq [-] $rest) {
>         __zoxide_cd (builtin:get-env __zoxide_oldpwd)
>     } elif (and (builtin:eq (builtin:count $rest) 1) (path:is-dir $rest[0])) { # <- this is what should have executed
>         __zoxide_cd $rest[0]
>     } else {
>         __zoxide_cd (zoxide query --exclude $pwd -- $@rest)
>     }
> }
> ```
> 
> In your case, you passed one argument that was a valid directory, so the 3rd condition should have been executed, but from the stacktrace it looks like it fell back to the 4th condition. I'm trying to figure out why the 3rd condition failed. Can you run `use path; path:is-dir ".\.azure\"` and see if you get `$true`?
> 
> Note to self: try to improve errors on Elvish so that "no match found" does not result in a stacktrace.

**Comment by ajeetdsouza** [comment]
Try `use path; path:is-dir '.\.azure\'` instead. Double quotes treat `\` as an escape character.

**Comment by xBLACKICEx** [comment]
> Try `use path; path:is-dir '.\.azure\'` instead. Double quotes treat `\` as an escape character.

well i got false
![image](https://user-images.githubusercontent.com/51036094/130337486-a72fc955-6b58-455d-b922-03927f4fcdf0.png)

**Comment by ajeetdsouza** [comment]
Hm, looks like a breaking change in Elvish 0.16.0 may be the cause of this. Can you tell me what the output of this command is?

```elvish
use path; path:is-dir &follow-symlink=$true '.\.azure\'
```

**Comment by xBLACKICEx** [comment]
> Hm, looks like a breaking change in Elvish 0.16.0 may be the cause of this. Can you tell me what the output of this command is?
> 
> ```
> use path; path:is-dir &follow-symlink=$true '.\.azure\'
> ```

I have reinstalled the window in the past few days, but zoxide still does not work, but some of the results have changed.
zoxide is work well with powershell

![image](https://user-images.githubusercontent.com/51036094/130483568-0f077c66-8519-4ea0-9363-09ba05b63389.png)

Edition	Windows 11 Pro N
Version	21H2
OS build	22000.160

elvish is download form official page Head version
zoxide is install by: cargo install zoxide

![image](https://user-images.githubusercontent.com/51036094/130483868-693e91c4-3126-4fc6-8c78-56501b46419e.png)
![image](https://user-images.githubusercontent.com/51036094/130484961-ab52cbcf-633a-49e6-ae62-109fef1da295.png)

**Comment by ajeetdsouza** [comment]
I think I figured out the error. Can you run `cargo install --git 'https://github.com/ajeetdsouza/zoxide' --branch elvish` and see if it's fixed for you?

**Comment by xBLACKICEx** [comment]
![image](https://user-images.githubusercontent.com/51036094/130513672-861e658b-eab4-43c2-b09e-addd258ad384.png)
yes, look like work well, thanks

> I think I figured out the error. Can you run `cargo install --git 'https://github.com/ajeetdsouza/zoxide' --branch elvish` and see if it's fixed for you?

**Comment by ajeetdsouza** [comment]
Awesome, I'll merge it then. Thanks for reporting and helping debug this issue!
