### ISSUE TITLE
Error while compiling zoxide

### ISSUE THREAD

**Issue by json1c** [ajeetdsouza/zoxide#256]
Error while compiling zoxide. https://pastebin.com/9Bgbc0YN

**Comment by ajeetdsouza** [comment]
Hey @json1c, did you try upgrading Rust and reinstalling?

**Comment by json1c** [comment]
i will try today

**Comment by ajeetdsouza** [comment]
@json1c did you try?

**Comment by json1c** [comment]
im been busy all week. just tried it. error, here is the log: https://pastebin.com/jPQagGKg

**Comment by ajeetdsouza** [comment]
It definitely seems like an issue with the overlay. I'm not sure how to reach the maintainer of the dm9pZCAq overlay, but I've created an issue [here](https://notabug.org/dm9pZCAq/dm9pZCAq-overlay/issues/1).

In the meantime, I'd suggest using the [GURU overlay](https://github.com/gentoo/guru/tree/master/app-shells/zoxide) instead.

**Comment by dm9pZCAq** [comment]
@ajeetdsouza you can also ping me here

> Try upgrading your version of Rust

what is the minimum suitable version of rust need to be installed to compile `zoxide`?

**Comment by dm9pZCAq** [comment]
i found needed version here
https://github.com/NixOS/nixpkgs/issues/137060

[dm9pZCAq/dm9pZCAq-overlay#1](https://notabug.org/dm9pZCAq/dm9pZCAq-overlay/issues/1) will be fixed soon

**Comment by dm9pZCAq** [comment]
@json1c now you can install `zoxide-0.7.3` with stable `amd64` keyword

or `zoxide-0.7.4` with `rust-1.54.0` but with unstable `~amd64`

**Comment by ajeetdsouza** [comment]
That was quick, thanks!
