### ISSUE TITLE
zoxide-bin for aur

### ISSUE THREAD

**Issue by ashincoder** [ajeetdsouza/zoxide#261]
Currently the aur only has zoxide-git. It would be great to support zoxide-bin

**Comment by ajeetdsouza** [comment]
Hey @ashincoder, zoxide is now on the [official Arch repository](https://archlinux.org/packages/community/x86_64/zoxide/). You can simply run `pacman -S zoxide`, they should have a binary available.

**Comment by ashincoder** [comment]
oh ok thanks
just checked
