### ISSUE TITLE
Adding flag for editing 

### ISSUE THREAD

**Issue by premell** [ajeetdsouza/zoxide#262]
So I really love zoxide, however most of the time when I navigate to a folder, I want to edit something within that folder. I think it would be useful to have either another command like "ze", or a flag, "z --edit", that opens your default editor in the folder. So if I go "ze awesome", it instantly opens the directory "~/.config/awesome" in my editor, instead of having to open it manually afterwards. To really make use of this feature we could add the number of times files are opened aswell. So you could go "ze lua.rc" and it instantly opens up e.g awesomes config file.

**Comment by ajeetdsouza** [comment]
Hey @premell, you can create a custom function to implement your first idea. Assuming you're on `zsh` and `vim`:

```zsh
function ze() {
    vim "$(zoxide query -- $@)"
}
```

The second idea you mentioned requires us to track files, which I'd say is out of scope for zoxide right now.

Btw, here's something I just wrote that you might find interesting. It takes in `N` arguments (`N-1` arguments to find the directory, and `1` argument to find the file).

```zsh
function ze() {
    local dir file
    dir="$(zoxide query --  ${@[1,-2]})"
    file="$(find "$dir" -maxdepth 1 -type f -exec basename {} \; | grep "${@[-1]}" | head -1)"
    if [ -z "$file" ]; then
        echo "zoxide: file not found"
    else
        vim "$dir/$file"
    fi
}
```
