### ISSUE TITLE
Not working with nushell 0.37

### ISSUE THREAD

**Issue by gnerzhin** [ajeetdsouza/zoxide#265]
I installed both nushell and zoxide with "cargo install" and followed the setup instructions for nushell in the README.
While the z and zi commands can be used, jumps are never added to the database.
After downgrading nushell to 0.36 everything is working fine for me, also no problems when using zsh.

**Comment by ajeetdsouza** [comment]
Looks like https://github.com/nushell/nushell/pull/4003 broke it. I'll draft a PR to fix this.
