### ISSUE TITLE
Praise for zoxide

### ISSUE THREAD

**Issue by Raytle** [ajeetdsouza/zoxide#268]
By the way, my scathing criticism in my previous comment notwithstanding, zoxide works great!

The integration with `fzf` is slick!

Thanks for creating this useful utility.

**Comment by ajeetdsouza** [comment]
Thank you, I appreciate it! 😄

**Comment by Raytle** [comment]
> Thank you, I appreciate it! smile

**You are welcome!**

I recommend you promote zoxide by asking guys like this...

https://www.youtube.com/c/BrodieRobertson/videos
https://www.youtube.com/c/LukeSmithxyz/videos

...to review it. If you are comfortable, perhaps you might even do a video chat with each them which they might append to the end of their video reviews of zoxide. I imagine each YouTuber would have some suggestions for improving zoxide that he would explain to you during such a video chat.

You can find more YouTubers like the two indicated above at...

https://www.reddit.com/r/lukesmith/comments/j7kmw0/lets_make_an_exhaustive_list_of_quality_luke/

Why do this? It will make you a better developer and help you earn more money. How? When you interview at a company you can show them, "I not only know how to write software applications, but I know how to promote my software to help it gain traction and how to improve my software applications by proactively asking for, and then incorporating suggestions (including constructive criticism) to improve my software applications and thereby delight users of my software applications."

Most engineers are poor at sales and marketing. To earn more money you need to learn how to promote yourself better.

**Comment by ajeetdsouza** [comment]
That's a fair enough point. I'm not sure if creators are open to suggestions like that, but I suppose I could drop them an email and ask.

**Comment by Raytle** [comment]
I suggest that you contact them... **now**. 

They all need good content for their YouTube channels. I would guess at least one of them would be delighted to do a short video chat with you.

I suggest that you post your availability on a freemium of one of the following...

- https://freebusy.io/en
- https://calendly.com/

Then when you email them, you might indicate something like, "I'm the creator of [zoxide](https://github.com/ajeetdsouza/zoxide). Would you like to review zoxide for your YouTube channel? Would you like to video chat with me for, say 5 to 10 minutes? I'm also ammenable to a live chat session for, say, up to 30 minutes on your YouTube channel if you would like your viewers to be able to ask me questions. If you would like to take me up on one or both of the proceeding options please feel free to schedule with me at **link to your freebusy.io or calendly.com**."

To earn more money you need to study sales and marketing. You are bad at them. Try searching on Google for, for example, **"How to market yourself as a programmer Reddit"** and/or **"How to market yourself as a programmer Ycombinantor"**.

Sales and marketing, like computer programming, are disciplines that one needs to study to master.
