### ISSUE TITLE
Purge Removed Directories

### ISSUE THREAD

**Issue by theduke** [ajeetdsouza/zoxide#269]
It would be great to have a command like `zoxide purge-removed` to remove all deleted directories from the database.

**Comment by ajeetdsouza** [comment]
Hey @theduke, is there any reason you want to delete them instantly? zoxide automatically purges deleted directories after 90 days. The only reason this doesn't happen instantly is to allow zoxide to remember external HDDs and USB drives.

**Comment by theduke** [comment]
After moving or deleting a lot of files the database can contain a lot of invalid directories, which results in a lot of `not found` errors until the database is cleaned up.

But nuking the whole database is also annoying.

The command could optionally take include paths and an `--exclude` flag so things like HHDs could be ignored.

**Comment by ajeetdsouza** [comment]
zoxide doesn't return deleted directories at all -- purging the directories will not remove the `no match found` errors. If you want to debug:

- `zoxide query -i` shows you the list of directories in the database
- `zoxide query -i --all` shows you deleted directories as well

Does the directory you're looking for exist in the database?

**Comment by theduke** [comment]
Ah, true, I tested and it seems to work fine.

I do distinctly remember running into an issue where I got a "the directory does not exist" error, but that might have been something intermittent.
