### ISSUE TITLE
Zoxide database doesn't update

### ISSUE THREAD

**Issue by thorstenkampe** [ajeetdsouza/zoxide#278]
Updated today from version 0.7.5 to 0.7.6: now the zoxide location database does not update anymore.

* OS: Windows 10
* Shell: Powershell 7.1.4
* Initialisation: `Invoke-Expression -Command (Out-String -InputObject (zoxide init powershell))`
* zoxide is invoked via `zi`

**Comment by thorstenkampe** [comment]
going back to 0.7.5 solves the issue

**Comment by ajeetdsouza** [comment]
Hey, thanks for reporting this. I've created a PR, it'll be fixed in the next release.
