### ISSUE TITLE
Error: could not launch fzf

### ISSUE THREAD

**Issue by reckoner** [ajeetdsouza/zoxide#28]
I am running this on windows 10 cygwin. I built zoxide with windows cargo and I *do* have /usr/bin/fzf which works fine.

Error: could not launch fzf

Caused by:
    The system cannot find the file specified. (os error 2)

**Comment by tjysdsg** [comment]
Just install [fzf](https://github.com/junegunn/fzf) on your computer

**Comment by ajeetdsouza** [comment]
Just to clarify, are you able to run the `fzf` command?

**Comment by reckoner** [comment]
Yes. I runs fine. I have been using the original `z` with it.

**Comment by ajeetdsouza** [comment]
Could you try this:
1. Install `fzf` on Windows (not Cygwin)
2. Add `fzf` to your `PATH` - ensure that you can run `fzf` with a regular `cmd.exe`
3. Try `zoxide` inside Cygwin now, and see if it works?

**Comment by reckoner** [comment]
https://github.com/junegunn/fzf/wiki/Cygwin

says that `fzf` is incompatible with mintty (primary cygwin terminal emulator) but it works great with  regular command console (I just tried it). The `fzf` version I have been running is the Ruby version mentioned in the above link.

Thanks anyway.

**Comment by ajeetdsouza** [comment]
Okay, no problem!
