### ISSUE TITLE
Suggestion: A way to create live demos

### ISSUE THREAD

**Issue by veracioux** [ajeetdsouza/zoxide#282]
NOTE: I am assuming that the asciicast in the README was created by manually typing out the commands, and then speeding the video up. If you are using something to automate the typing of the commands, you can stop reading.

Disclaimer: This is shameless self-promotion, but I think what I suggest could be useful to the project.

I have created a small bash program that automates the creation of live CLI demos: [tuterm](https://github.com/veracioux/tuterm).

**How it works**
- You create a specialized bash script
- You run the script
- Tuterm automatically reproduces the commands, as if a human were typing them
- You record it and upload it to [asciinema](https://asciinema.org) using another 2 commands, or you can use another method for that

You prevent mistakes, make the demo reproducible and easy to change when a new version of zoxide comes out.

**Another (IMO even cooler) feature**
The same script that runs the demo can be used (with optional modifications) as an interactive tutorial for users. They run the script and tuterm displays the expected command to them. The users are expected to repeat the command, etc. Error checking included.

**How I can help**
I can recreate the existing demo in the README using this method. Or I can change it based on your feedback. I can also supplement the demo with an interactive tutorial if necessary.

Let me know if your project would benefit from this. Sorry if I am wasting your time with this.

**Comment by ajeetdsouza** [comment]
You're right, recording the GIF was definitely a pain! I would definitely be open to using tuterm.

**Comment by veracioux** [comment]
@ajeetdsouza I'll get on it then. For starters, I'll just recreate the existing demo in tuterm.

**Comment by ajeetdsouza** [comment]
Hey @veracioux, did you find time to try this out? I imagine this might be a bit convoluted given that you'd have to showcase the interactive completion feature, but I'm interested in using tuterm for making GIFs.

**Comment by veracioux** [comment]
@ajeetdsouza I'm sorry, I pushed tuterm aside in favor of other projects. I will get back to this in the weekend. Yes, the interactive completion is a bit tricky, and I may have to implement a new feature (https://github.com/veracioux/tuterm/issues/3) in tuterm for it to work properly.

Sorry about this dragging on.

**Comment by ajeetdsouza** [comment]
Thanks for the quick response! Tuterm working on any shell sounds fantastic.

**Comment by ajeetdsouza** [comment]
Closing this for now, feel free to recreate this issue once this feature lands.
