### ISSUE TITLE
[Feature Request] Zoxide Library

### ISSUE THREAD

**Issue by JacobTravers** [ajeetdsouza/zoxide#283]
It would be awesome to integrate zoxide in other rust tools especially file managers like [joshuto](https://github.com/kamiyaa/joshuto). Would it be possible to make a zoxide library similar to the way [skim](https://github.com/lotabout/skim) is both a cli and a [library](https://github.com/lotabout/skim#use-as-a-library)? 

Linking [this issue](https://github.com/kamiyaa/joshuto/issues/97#issuecomment-944695877) for reference

**Comment by ajeetdsouza** [comment]
Hey, apologies for the delayed response. `joshuto` looks great!

zoxide does a file read upon `query` and a file write upon `add`. Are you planning on calling the library function in your main thread? If not, it may not matter whether you use the library or spawn a child process. Plus, you can batch calls to `zoxide add` (it takes multiple paths), making it still faster.

I'm not very convinced about turning zoxide into a library for the sake of one application. I resonate with the creator of `fzf` here (https://github.com/junegunn/fzf/issues/2097):

- It's cumbersome to maintain a stable API
- The CLI is quite useable, even as a child process

Most importantly, it's hard to justify the effort of building a library unless enough people are using it. I'm seeing a lot of upvotes on this issue, so if anybody plans to use zoxide as a library in another project, please do post here!

**Comment by ajeetdsouza** [comment]
@JacobTravers I'm closing this issue since there's no plan for this at the moment, but I've replied on the issue you linked.
