### ISSUE TITLE
zoxide init fish | fish => complete: Too many arguments

### ISSUE THREAD

**Issue by PaulGrandperrin** [ajeetdsouza/zoxide#291]
I don't remember when this error appeared so I don't know if it comes from an update to fish or zoxide..

My fish is 3.1.0 and comes from Ubuntu 20.04.
My zoxide is 0.7.8 and comes from Nixpkg.

`zoxide init fish` is outputing the line "complete -e z", which seems invalid for fish: https://fishshell.com/docs/current/cmds/complete.html

**Comment by ajeetdsouza** [comment]
This has been fixed in zoxide 0.7.9 (released yesterday). The syntax does work on the latest version of fish, which is why it wasn't caught before release.

If you upgrade either zoxide or fish to the latest version, it should fix the issue.

**Comment by PaulGrandperrin** [comment]
Oh ok great! Thanks for the quick answer! I'll wait for zoxide to be update then.
