### ISSUE TITLE
Can't install on Raspbian

### ISSUE THREAD

**Issue by piersolenski** [ajeetdsouza/zoxide#298]
Running `apt install zoxide` on Raspbian as per the [docs](https://github.com/ajeetdsouza/zoxide#installation) results in `error: snap "zoxide" not found`.

**Comment by ajeetdsouza** [comment]
I can't really test this myself because I don't have an RPi, so I've removed the installation instructions from the README for now. Try using the curl-based installer instead:

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

According to [repology](https://repology.org/project/zoxide/versions), zoxide _is_ in the repository of the latest Raspbian Stable. If you figure out how to install it from there, do let me know!

**Comment by piersolenski** [comment]
Hmm that gives me the following error:

```
Thanks for using webi to install 'zoxide@stable' on 'Linux/armv7l'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Error: no 'zoxide' release for 'linux' on 'armv7l' as one of 'tar,exe,zip,xz,git,dmg' by the tag ''
       'zoxide' is available for 'macos,windows,linux' on 'arm64,amd64' as one of 'tar,zip,exe'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/zoxide@.tab
```

**Comment by ajeetdsouza** [comment]
That's definitely a problem, I'll fix that. If you want to install it in the meantime, you can download the tarball manually from [GitHub Releases](https://github.com/ajeetdsouza/zoxide/releases/tag/v0.7.9), extract it, and put the zoxide binary somewhere in `$PATH` (typically `~/.local/bin`).

**Comment by crazystylus** [comment]
Hi @piersolenski ,
Can you tell me the exact RPi Hardware that you are using like 3B, 4B ..?
Can you tell the output of the following commands?
```shell
$ neofetch
$ uname -i
```
I will to replicate the configuration and resolve the issue.

**Comment by piersolenski** [comment]
```
Host: Raspberry Pi 4 Model B Rev 1.2
Kernel: 5.10.63-v7l+
Uptime: 12 days, 21 hours, 38 mins
Packages: 734 (dpkg), 8 (snap)
Shell: zsh 5.7.1
Terminal: /dev/pts/0
CPU: BCM2711 (4) @ 1.500GHz
Memory: 433MiB / 3838MiB
```
`uname -i` is `Unknown`, `uname` is `Linux`

**Comment by piersolenski** [comment]
https://github.com/webinstall/webi-installers/issues/318#issuecomment-977113271

**Comment by ajeetdsouza** [comment]
Fixed!

@piersolenski, could you tell me the output of `cat /etc/os-release`, so that I can update the README?

**Comment by piersolenski** [comment]
Sure!
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by ajeetdsouza** [comment]
Ah, that explains it! `apt install zoxide` only works on Raspbian 11+. I've updated the README to reflect this.
