### ISSUE TITLE
[Idea] replace fzf support with skim library

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [ajeetdsouza/zoxide#3]
The [skim](https://github.com/lotabout/skim) binary is as far as I could tell a direct drop-in replacement for fzf built with rust. I have never used their library but their example on their README

```toml
# Cargo.toml
[dependencies]
skim = "0.7.0"
```

```rust
extern crate skim;
use skim::prelude::*;
use std::io::Cursor;

pub fn main() {
    let options = SkimOptionsBuilder::default()
        .height(Some("50%"))
        .multi(true)
        .build()
        .unwrap();

    let input = "aaaaa\nbbbb\nccc".to_string();

    // `SkimItemReader` is a helper to turn any `BufRead` into a stream of `SkimItem`
    // `SkimItem` was implemented for `AsRef<str>` by default
    let item_reader = SkimItemReader::default();
    let items = item_reader.of_bufread(Cursor::new(input));

    // `run_with` would read and show items from the stream
    let selected_items = Skim::run_with(&options, Some(items))
        .map(|out| out.selected_items)
        .unwrap_or_else(|| Vec::new());

    for item in selected_items.iter() {
        print!("{}: {}{}", item.get_index(), item.get_output_text(), "\n");
    }
}
```

seems simple enough.

**Comment by ajeetdsouza** [comment]
This definitely looks interesting, I will give this a try!

**Comment by ErichDonGubler** [comment]
The only issue with this is that currently, `zoxide` is cross-platform. However, `tui-rs` (made by the @lotabout, the creator of `skim` to dogfood FOR `skim`) is *nix-only, and the author has [preferred not to take the time to make sure it works with Windows](https://github.com/lotabout/skim/issues/25).

**Comment by ajeetdsouza** [comment]
While `zoxide` currently only supports *nix, I do intend to eventually add Windows support. If `skim` worsens the gap, it must be counted out.

Thanks!

**Comment by NightMachinary** [comment]
`skim` is  also much slower than  `fzf`.

**Comment by pickfire** [comment]
Yes, but it's not noticible.
