### ISSUE TITLE
Holding enter boosts directory's rank

### ISSUE THREAD

**Issue by cole-h** [ajeetdsouza/zoxide#30]
At the moment, [this is intended behavior](https://github.com/ajeetdsouza/zoxide/pull/4#issuecomment-598159054) (and also the behavior of most other jumpers).

I am of the opinion that we should have some way to allow the user to decide if they want to add a directory on every prompt redraw, or on every `PWD` change (see the "Prior art" section below for how our predecessors do this). Although a departure from what the other jumpers have named theirs, maybe introducing `$_ZO_WATCH_PWD` to choose whether or not a directory is added on each prompt redraw, or every time `PWD` is changed, is the solution here.

I also believe that any more complicated setup should be up to the user.

To be clear: this issue is supposed to be one for discussing what action should be taken here.

---

### Prior art
[`z` (original)](https://github.com/rupa/z) has the `$_Z_NO_PROMPT_COMMAND` env var to allow the user to disable this functionality (or handle it themselves).

[`z.lua`](https://github.com/skywind3000/z.lua#options) has `$_ZL_ADD_ONCE` (and an `--init once` flag) which controls this.

[`z` (fish edition)](https://github.com/jethrokuan/z) only adds when `PWD` changes, and has no option to modify this behavior.

---

cc @ajeetdsouza

**Comment by ajeetdsouza** [comment]
I agree. I'm thinking of adding a `--hook` flag to the `init` subcommand which can be set to:

- `none`: no hook is set
- `prompt`: runs `zoxide add` on every prompt
- `pwd`: runs `zoxide add` every time the working directory changes

**Comment by cole-h** [comment]
It wasn't clear but I just wanted to make sure: either `prompt` or `pwd` should be default if you go that route. I lean towards defaulting to `pwd`, but it's (obviously) up to you.

**Comment by ajeetdsouza** [comment]
I've never a jumper set on a pwd hook before, although I can see why that would be useful. However, changing the defaults now breaks userspace, which I don't think we should do.

**Comment by ajeetdsouza** [comment]
I've added support for the `pwd` listener in https://github.com/ajeetdsouza/zoxide/commit/9c8e8da71a03f5c3c070247f5b0bffd971a70f62. Currently, it only works with `zsh`; I'm still exploring ways to do this in `bash` and `fish`.

**Comment by cole-h** [comment]
For `fish`, all you should need is:

```rust
const FISH_HOOK_PWD: &str = r#"
function _zoxide_hook --on-variable PWD
    zoxide add
end
"#;
```

**Comment by ajeetdsouza** [comment]
PWD hooks have been added for all 3 shells in https://github.com/ajeetdsouza/zoxide/commit/41aabccb8fd989820d1cf75bfcdafe8fc798c5d6. Thanks!

**Comment by cole-h** [comment]
Woo! Thanks for the quick work!

**Comment by cole-h** [comment]
One more thing: could you please add some examples in the README, when you get a chance?

**Comment by ajeetdsouza** [comment]
I will update the README along with the next release, which should be out soon!
