### ISSUE TITLE
When directory is picked via fzf from `zoxide query -i` before list is complete the output is empty

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [ajeetdsouza/zoxide#303]
## How to reproduce:

1. Some of the directories from your `zoxide query -l` should be on something slow, like HDD, since the check for directory existence will be too fast otherwise.

2. Drop caches, **otherwise the issue will only be apparent after reboot or long idle** (*dies inside*).

```sh
echo 3 | sudo tee /proc/sys/vm/drop_caches
```

3. `zoxide query -i` and press enter immediately, before fzf got all of the items.

**Expected behavior**: first (picked) directory is printed after fzf's exit.

**Actual behavior**: the output is empty, exit code (`echo $?`) is `0`.

4. Now drop caches again, and run `zoxide query -l | fzf` the same way, immediately pressing enter.

**Expected behavior**: first directory is printed after fzf's exit.

**Actual behavior**: first directory is printed after fzf's exit.

I am on arch linux, zsh, everything latest.

But I've also noticed this happening from python's `subprocess.check_output()` and `/bin/sh`, so this doesn't seem to be some weird shell's config shenanigans.

E.g. testing with

```python
#!/usr/bin/env python3


import subprocess as sp

output = sp.check_output(['zoxide', 'query', '-i'])

print(output.decode('utf-8'))

```
will reveal the same issue.

**Comment by ajeetdsouza** [comment]
Thanks for the detailed issue! I've created a PR to fix this.
