### ISSUE TITLE
Are there any other commands?

### ISSUE THREAD

**Issue by igoracmelo** [ajeetdsouza/zoxide#304]
Tried to find more options with `man zoxide` and `z --help` but no success.

**Comment by ajeetdsouza** [comment]
`man zoxide` lists a bunch of [subcommands](https://man.archlinux.org/man/zoxide.1#SUBCOMMANDS) that you can use. `zoxide --help` will show you the same subcommands. Thereafter, you can explore the subcommands using `zoxide add --help`, etc.
