### ISSUE TITLE
`zoxide query` shouldn't autocomplete filenames

### ISSUE THREAD

**Issue by igoracmelo** [ajeetdsouza/zoxide#305]
Since `query` command doesn't load files, I believe it shouldn't show files on tab autocomplete.
```
❯ zoxide query example.py
zoxide: no match found
```

**Comment by ajeetdsouza** [comment]
`zoxide query` actually doesn't accept directory names either. It only takes strings and searches the database with them. The filename autocompletion that you're seeing is just the shell's default autocomplete when there are no completions available.

The `z` command is the one that takes either a directory name or a query string. Completions for `z` are already available on bash and fish, I'm working on bringing it to zsh.
