### ISSUE TITLE
Jump to subdirectory

### ISSUE THREAD

**Issue by igoracmelo** [ajeetdsouza/zoxide#306]
Be able to jump to a subdirectory of a directory that is in the history.
Ideally the subdirectory itself wouldn't need to be in history.

**For example**
History:
```
/home/user/folder1
```

Command:
```
$ zsd f1 f5
$ pwd
/home/user/folder1/a/b/c/d/folder5
```

**Comment by ajeetdsouza** [comment]
This is currently out of scope for zoxide -- zoxide only works on directories that you've been to at least once before. It shouldn't be very hard to implement as custom shell function using [fzf](https://github.com/junegunn/fzf) and and [fd](https://github.com/sharkdp/fd), though. A rough implementation:

```shell
cd "$(fd -t d . | fzf)"
```
