### ISSUE TITLE
Parse error on initialization - zsh & windows

### ISSUE THREAD

**Issue by spf13** [ajeetdsouza/zoxide#308]
The error I get is: 

`(eval):43: parse error near 'elif'`

Using windows w/ zsh 5.8 (x86_64-pc-msys)

Tried using the POSIX initialization with the same result. 

zoxide v0.7.9

**Comment by ajeetdsouza** [comment]
It seems that this is a common issue https://github.com/conda/conda/issues/9922.

**Comment by ajeetdsouza** [comment]
@spf13 the problem is caused by CLRF line endings -- Windows uses `\r\n` for newlines whereas Unix uses just `\n`. Since you're using the Windows version of zoxide and zsh is a Unix tool, it is stumbling at the `\r` character.

I'm trying to see if other tools have a way around this, but in the meantime, you can use `dos2unix` to fix it:

```sh
pacman -Syu dos2unix
eval "$(zoxide init zsh | dos2unix)"
```

**Comment by spf13** [comment]
Thank you, that worked well enough.

**Comment by Orlinky** [comment]
I have the same problem on linux(debian):

```zsh
(eval):10: defining function based on alias `z'
(eval):10: parse error near `()'
```

Tried to use `dos2unix` as suggested but it didn't change anything.

In my `.zshrc` I have:
```zsh
alias z='__zoxide_z'
alias cd='z'
eval "$(zoxide init zsh --no aliases)"
```

**Comment by ajeetdsouza** [comment]
@Orlinky you have to declare the aliases _after_ calling zoxide, not before:

```sh
eval "$(zoxide init zsh --no aliases)"
alias z='__zoxide_z'
alias cd='z'
```

**Comment by Orlinky** [comment]
@ajeetdsouza Thank you!

I see that's why I didn't have the problem on macOS with this setup but on Debian it became apparent.

**Comment by Orlinky** [comment]
@ajeetdsouza It seems I answered too soon, the problem remains but the error changed slightly:

```zsh
(eval):25: defining function based on alias `zi'
(eval):25: parse error near `()'
```

The version of zoxide is `v0.4.3-unknown`.

**Comment by ajeetdsouza** [comment]
Try upgrading to the latest version of zoxide. Debian versions tend to lag behind a lot, use this instead:

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

**Comment by Orlinky** [comment]
Indeed that was it, thank you again for your time!

**Comment by ajeetdsouza** [comment]
@spf13 I fixed this by using `.gitattributes` to ensure that shell scripts never end up with CRLF line endings, thus removing the need for `dos2unix`. Thanks for reporting this issue!

P.S. I love your work, thank you for doing what you do!
