### ISSUE TITLE
[feature] cd into highest ranked *sub*directory

### ISSUE THREAD

**Issue by scottkosty** [ajeetdsouza/zoxide#311]
I wonder if it would be useful to have a command like `zn foo` cd into the highest ranked nth-level subdirectory of foo.

Here is my use case: I have a directory 'teaching', and inside 'teaching' I have 'fall2020', 'spring2021', 'fall2021'. `z fall 2021` doesn't work for me because I have several directories with 'fall2021' as a subdirectory. Further, I am so lazy I don't even want to remember what year or semester it is. If the above `zn` command existed, I could do:

```
z1 teaching
```

This would take me to 'teaching/fall2021' because 'fall2021' is the highest rank subdirectory of 'teaching'.

Thank you for all of your work!

**Comment by ajeetdsouza** [comment]
I think this would work for you:

```sh
z teaching /
```

Note that this matches any level of subdirectories -- if `~/teaching/fall2021/some/subdirectory` has a higher score than `~/teaching/fall2021`, it would be preferred instead.

**Comment by scottkosty** [comment]
Cool trick! I will experiment with that (and even `z teaching / /` seems possibly useful as well). Thank you! I think we close this issue.

Thanks again for all of your work!

**Comment by ajeetdsouza** [comment]
Not a problem!
