### ISSUE TITLE
[Bash] Unable to add z alias at shell login

### ISSUE THREAD

**Issue by g-ongenae** [ajeetdsouza/zoxide#314]
In my `.bash_profile`:

```bash
# Initialize zoxide aliases
eval "$(zoxide init bash)"
```

Error:

```shell
bash: (Ie)__zoxide_hook: syntax error in expression (error token is "__zoxide_hook")
```

In my shell:

```shell
☸ stg in ~ via 🐍 v2.7.18 
❯ z
bash: z: command not found
☸ stg in ~ via 🐍 v2.7.18 took 3s 
❯ zoxide
zoxide v0.7.9
...
```

**Comment by ajeetdsouza** [comment]
What's `bash --version`?

**Comment by g-ongenae** [comment]
```
☸ stg in ~ via 🐍 v2.7.18 
❯ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ajeetdsouza** [comment]
That's a very old version of bash. Could you try using Homebrew to install the latest version (`brew install bash`)?

**Comment by g-ongenae** [comment]
Yes. Just did it, the error remains.

```shell
bash: (Ie)__zoxide_hook: syntax error in expression (error token is "__zoxide_hook")

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

☸ stg in ~ via 🐍 v2.7.18 
❯ bash --version
GNU bash, version 5.1.12(1)-release (x86_64-apple-darwin21.1.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

☸ stg in ~ via 🐍 v2.7.18 
❯ 
```

**Comment by ajeetdsouza** [comment]
I just looked at the error again. That's not a bash error. I believe you're executing `eval "$(zoxide init zsh)"` somewhere in your bash configuration.

**Comment by g-ongenae** [comment]
Oh you're right, I fixed the issue in my shared `.bash_profile` but I forgot to update the one in the `$HOME` folder. Now, it works. Thank you for your help and sorry, I should have been able to figure that out before opening this bug.

**Comment by ajeetdsouza** [comment]
Not a problem, and you're welcome! 😄

**Comment by DesBw** [comment]
I am having this issue. I have put the `eval "$(zoxide init bash)"` in my profile ( `home/.bashrc`) as well as the shell profile `(home/.bashprofile)`. But, I am getting the same error.

**Comment by ajeetdsouza** [comment]
@DesBw please create a fresh issue.
