### ISSUE TITLE
Migrating db.zo from Linux to MacOS

### ISSUE THREAD

**Issue by Allaman** [ajeetdsouza/zoxide#316]
Hello, 

I just switched from Linux to MacOS and want to keep my db.zo for obvious reasons :) The file/folder structure on my new machine is identical to the old machine (from a user's relative point of view)

Turned out that is not that easy as just copying the database to the new machine as MacOS absolute user path is `/Users/michael` in contrast to the absolute path in my Linux based db which is `/home/michael/`

I tried to search and replace the string `home` with `User`  via vim but that resulted in a desirialization error while reading the database...

Any hints how I can migrate my zoxide db to the new system?

Thanks!

**Comment by ajeetdsouza** [comment]
Currently, there isn't a way to do this, outside of hacky shell scripts using `zoxide query --all` and `zoxide add`. https://github.com/ajeetdsouza/zoxide/issues/236 would solve this, but I wanted to see a bit more support for it before adding in another feature.

I suppose it's worth implementing now, so I'll close this issue in favour of that one. If you have any thoughts, I'd love if you could post them there.
