### ISSUE TITLE
completion not working on bash

### ISSUE THREAD

**Issue by g-thome** [ajeetdsouza/zoxide#317]
When in my home folder, typing `z Doc` and pressing tab will trigger an error

```
~
❯ z Doc-bash: builtin: mapfile: not a shell builtin
-bash: COMP_WORDS: bad array subscript
```

**Comment by ajeetdsouza** [comment]
What OS / bash version are you on?

**Comment by g-thome** [comment]
MacOS Monterey 
Bash version 3.2.57(1)-release

**Comment by ajeetdsouza** [comment]
macOS hasn't updated their preinstalled Bash since 2006. You might want to upgrade your Bash (`brew install bash`).

I'll create a PR that only initializes completions if the Bash version is >= 4.

**Comment by g-thome** [comment]
it worked! thanks for the tip :)
