### ISSUE TITLE
Manpage structure in releases broken

### ISSUE THREAD

**Issue by kaihowl** [ajeetdsouza/zoxide#319]
The [0.7.9 release](https://github.com/ajeetdsouza/zoxide/releases/tag/v0.7.9) has manpages included in the tarballs. Thank you for that! :)

Unfortunately, the structure should be `man/man1` such that man would automatically pick them up by the magic of `AUTOPATH`.

I can fix the structure locally with
```shell
mkdir -p man/man1
mv man/zoxide-add.1 man/zoxide-import.1 man/zoxide-init.1 man/zoxide-query.1 man/zoxide-remove.1 man/zoxide.1 man/man1
```

Should the packaged releases receive the same structure?

**Comment by ajeetdsouza** [comment]
Hey @kaihowl!

Can you highlight how AUTOPATH picks up manpages here? I'm not familiar with it.

**Comment by kaihowl** [comment]
Hi @ajeetdsouza,

thank you for the very prompt reply. :)

My knowledge on manpages is limited as well. From my local attempts and from perusing the man manpages, I found the following:

>In addition, for each directory in the command search path (we'll call it a "command directory") for which you do not have a MANPATH_MAP statement, man automatically looks for a manual page directory "nearby" namely as a subdirectory in the command directory itself or in the parent directory of the command directory.

>You can disable the automatic "nearby" searches by including a NOAUTOPATH statement in /etc/man.config.

Source: https://linux.die.net/man/1/man

With this, I am able to extract a released tarball to for example `~/.zoxide`, add that folder to my `PATH`, and enjoy running zoxide. As zoxide is on the `PATH` and there is a nearby folder `man`, the manpages would be found and used by `man zoxide` if they were following the proper directory structure.

From what I see in for example the _nvim_ tarball releases like [this one](https://github.com/neovim/neovim/releases/tag/v0.6.0), the proper structure is `man/man<section>`. This can also be observed in other directories like `/usr/share/man`.

From the man manpage itself, we further read:

> In each directory in the search path as described above, man searches for a file named topic.section, with an optional suffix on the section number and  possibly  a  compression suffix.  If it doesn't find such a file, it then looks in any subdirectories named manN or catN where N is the manual section number.  If the file is in a catN subdirectory, man assumes it is a formatted manual page file (cat page).  Otherwise, man assumes it is unformatted.  In either case, if the filename has a known compression suffix (like .gz), man assumes it is gzipped.

That would in theory imply that the manpages should already work as supplied in the zoxide releases. In practice, I was not able to get this working. When calling `man -d zoxide`, I see

```
path directory /Users/kaihowl/.zoxide is not in the config file
adding /Users/kaihowl/.zoxide/man to manpath
...
No manual entry for zoxide
```

Looking at both a Ubuntu 20.04 and a macOS system, I see that all manpages in for example `/usr/share/man` follow the convention to place the manpages in a section-wise subfolder.

But maybe there is a way to make use of the current manpages, that does not require this directory structure. I am very likely just not aware of that mechanism. How do others make use of the tarballed manpages correctly?

**Comment by ajeetdsouza** [comment]
That's a fair point.
