### ISSUE TITLE
Request: Custom command instead of 'z'

### ISSUE THREAD

**Issue by AndydeCleyre** [ajeetdsouza/zoxide#32]
I'd like to try this as a replacement for `zsh-z`, but use `z` for something else and don't want to have to do a dance of redefining. I currently init `zsh-z` with:

```bash
ZSHZ_CMD=j ZSHZ_NO_RESOLVE_SYMLINKS=1 . ~/Code/zsh-z/zsh-z.plugin.zsh
```

And am looking for something similar to that or like:

```bash
eval "$(zoxide init --no-define-aliases --cmd j zsh)"
```

**Comment by ajeetdsouza** [comment]
This is a valid problem, I will work on this.

**Comment by ifreund** [comment]
until then you can manually source the script with the name of the function `z()` changed to whatever you like, it's what I'm currently doing

**Comment by ajeetdsouza** [comment]
I've added a `--z-cmd` flag in https://github.com/ajeetdsouza/zoxide/commit/ede121ef8b3b50d16ad48dab9ab4a20dbafed7dc, it will be released with v0.3.1.

Sorry this feature took so long to land!

**Comment by AndydeCleyre** [comment]
Can you add a note to the readme?

**Comment by ajeetdsouza** [comment]
@AndydeCleyre done!
