### ISSUE TITLE
Bug: Failed to read /dev/tty

### ISSUE THREAD

**Issue by D1mon** [ajeetdsouza/zoxide#321]
After update from zoxide v.0.7.9 to zoxide v0.8.0:
Failed to read /dev/tty
^[[1;1Rzoxide: fzf returned an error

**Comment by ajeetdsouza** [comment]
Could you provide some steps to reproduce this error? What OS/shell are you on?

**Comment by D1mon** [comment]
Open terminal, and then error.
Manjaro/Konsole(Zsh)

**Comment by rprimus** [comment]
Mon Dec 27 05:30:53 GMT 2021

Was also seeing this in macOS/zsh (with .oh-my-zsh).

Error was caused by having `.oh-my-zsh` plugin `z` enabled.

Removing `z` from the list  enabled `.oh-my-zsh` solved the problem.

@D1mon - does this also work for you?

**Comment by ajeetdsouza** [comment]
Could you share your shell configuration?

**Comment by D1mon** [comment]
Yes, 'z' plugin was enabled. I disable, and error was gone.
Maybe make check if 'z' plugin enable?

**Comment by ajeetdsouza** [comment]
[Found the problem](https://github.com/ohmyzsh/ohmyzsh/blob/0f1de0871327f29c437e3cb0e99c48123892e453/plugins/z/z.sh#L237). Both zoxide and rupa/z define a function called `_z`, and rupa/z is calling the function at every prompt.

I'll change the function name to prevent this from happening in future releases.
