### ISSUE TITLE
Ability to specify and use more than one DB (or similar solution)

### ISSUE THREAD

**Issue by xaocon** [ajeetdsouza/zoxide#322]
I think it would be nice to have the ability to have concepts like workspaces or "histories" in zoxide. It could be very nice when you have a groups of directory trees with matching names but belonging to different classes (think reusable projects for different clients). Something as simple as adding an additional ENV var that specifies the name of the DB file and defaults to current functionality if unset. It could even be used as kind of a privacy setting, though some kind of read only mode or something would probably be a better long term fit for that case.

In thinking of the long term it might make more sense to have a different name than `db.zo` as the default (probably `default.zo`) and if you think you'll use the data dir for things other than DBs in the future then maybe have a directory for them. If nothing is set for the env variable it could look for the default name then look for `db.zo` and offer to move the file. If neither is found creating the default file. The name change isn't important to me at all, just trying to think ahead and thought maybe `db` might be a name someone would use.

I might be able to help with a PR but I don't know anything about the structure and a quick first glance looks like you might have implemented a custom DB so not sure how much help I'll be.

**Comment by ajeetdsouza** [comment]
From what I understand, you have multiple clients (say `foo` and `bar`), and have `~/foo/lots_of_projects` and `~/bar/lots_of_projects` for both of these clients. In that case, couldn't you use the client name as a prefix?

```bash
z foo <project name>
z bar <project name>
```

You can even create aliases for them:

```bash
alias zf='z foo '
alias zb='z bar '
```

or you could keep a variable to do this:

```bash
CURRENT_CLIENT=''

function z() {
  __zoxide_z "$CURRENT_CLIENT" "$@"
}

function change-client() {
  CURRENT_CLIENT="$1"
}
```

**Comment by xaocon** [comment]
Yeah, rewriting all the shell functions to accept an environmental prefix would be one useable workaround.

Seems you'd prefer to keep all the directories in a single spot so I'll close this.
