### ISSUE TITLE
Elvish Shell Syntax Change

### ISSUE THREAD

**Issue by fennewald** [ajeetdsouza/zoxide#323]
One of the shells zoxide supports, elvish (https://elv.sh), is planning to deprecate the lambda syntax used. The new syntax was supported starting in v0.17, but will be mandatory in v0.18.

v0.18 is planned for release [03/2022](https://github.com/elves/elvish/blob/master/0.18.0-release-notes.md). The output for `zoxide init elvish` needs to be updated before then. It is worth noting that the fix will break 0.16 support.

I'll submit a PR that has the breaking change. If it's an issue, maybe we could introduce something like `zoxide init --version 17 elvish` although that feels a little obtuse to me.

**Comment by ajeetdsouza** [comment]
Thanks! We can do breaking releases for pre-1.0 shells, that's not a problem.
