### ISSUE TITLE
ability to print list of zoxide targets

### ISSUE THREAD

**Issue by premell** [ajeetdsouza/zoxide#326]
right now the methods you can use with zoxide is add, import, init, query and remove. I think you should also be able to list the entries in zoxide together with their rank. This was something you could do in the original z. So  if you just do "zoxide list", you get all entries with their rank, but if you specify a path, you only get the entries which match that path

**Comment by premell** [comment]
hmm so apperently zoxide query -l, lists all entries. However it does not show the rank of the entry. Also its difficult too even know that you can use query -l. Maybe it should be its own command? like list for example.

**Comment by ajeetdsouza** [comment]
The following command will give you frecency scores:

```sh
zoxide query -ls
```

This is information is under `zoxide query --help`. If you've installed via a package manager, `man zoxide-query` will give you this information too.
