### ISSUE TITLE
Interactive selection preview doesn't work if you've aliased ls

### ISSUE THREAD

**Issue by Skepfyr** [ajeetdsouza/zoxide#328]
I've aliased the ls command to the wonderful exa tool, however that means that if I run `zi` I get a pretty box on the right that displays: `exa: Unknown argument -p`. I'm pretty sure that's caused by this line:
https://github.com/ajeetdsouza/zoxide/blob/b6b024c452635d672e3dc58707ef86cb944a52ab/src/fzf.rs#L35

I'm not entirely sure what the right fix is, maybe another environment variable and fully qualify `ls` by default.

**Comment by ajeetdsouza** [comment]
Hey, thanks for pointing this out!

I looked up the implementation, it seems fzf uses `sh -c COMMAND` to run the preview command. On UNIX systems, we can reasonably assume that `sh` is POSIX compliant, so we can use `\command -p` to bypass the alias.

**Comment by Skepfyr** [comment]
I don't think that's true because I had `ls` aliased in fish, and so `sh -c 'ls -p'` works fine. [The fzf README](https://github.com/junegunn/fzf#preview-window) claims it uses your `$SHELL` rather than `sh` which makes that approach less helpful.

**Comment by schoenenberg** [comment]
I had the same issue and have setup this little workaround for it. Just set the `ZO_FZF_OPTS` to `--preview=\'exa -la {2..}\'`.

To preserve all the other fzf options: 
```
# fish env set
set -Ux _ZO_FZF_OPTS '--bind=ctrl-z:ignore --exit-0 --height=40% --inline-info --no-sort --reverse --select-1 --preview=\'exa -la {2..}\''
```
