### ISSUE TITLE
Adding `--` broke my PS1

### ISSUE THREAD

**Issue by pfr-dev** [ajeetdsouza/zoxide#335]
So I am only assuming this is the reason my `PS1` is no longer printing the working dir after `zoxide` is called. 

Here is the `PS1` from my `.shrc` which I use on NetBSD within `ksh`

```
#!/bin/sh
# .shrc file for sh(1).

case "$-" in *i*)
    set -o emacs
    set -o noclobber

# give me a cool prompt
cd() {
    command cd -- "$@"
    S="$(dirname "$PWD")/$(basename "$PWD")"
    R="$(dirname "$HOME")/$(basename "$HOME")"
    S=$(echo "$S" | tr -s /)        # /// -> /
    R=$(echo "$R" | tr -s /)        # /// -> /
    if [[ "$S/" == "$R/"* ]]        # ksh(1), bash(1) ver.
    then    PS1=$(printf '\033[35m%s\033[0m \033[37m$\033[0m ' "~${S#$R}\$(__zoxide_hook)")
    else    PS1=$(printf '\033[35m%s\033[0m \033[37m$\033[0m ' "$S\$(__zoxide_hook)")
    fi
}
cd

# zoxide
eval "$(zoxide init posix --hook prompt)"
```

Using `cd` works just fine and prints the working directory that is cd'd into (and so did `zoxide` up until the latest update). Now when using `zoxide` my prompt remains unchanged no mater which directory I'm in or moving to (example below).

Have you any idea how to fix this? I know it isn't necessarioy an issue with `zoxide` and probably more so an issue with `ksh` or how I'm setting my `PS1` but I just thought I'd ask. 

Cheers

Example:

```
~ $ cd Downloads/
~/Downloads $ cd
~ $ z down
~ $ pwd
/home/dave/Downloads
~ $ z git
~ $ pwd
/home/dave/.git
~ $ cd
~ $ cd .git
~/.git $ z
~/.git $ pwd
/home/dave
~/.git $ cd
~ $
```

**Comment by ajeetdsouza** [comment]
Try overriding `__zoxide_cd` after you initialize zoxide:

```sh
__zoxide_cd() {
    cd "$@"
}
```

**Comment by pfr-dev** [comment]
Thank you, working again :+1:

**Comment by ajeetdsouza** [comment]
zoxide v0.9.5 now officially supports `ksh`. Do try it out whenever you get the chance!
