### ISSUE TITLE
Unable to get interactive completions working in zsh

### ISSUE THREAD

**Issue by tanc** [ajeetdsouza/zoxide#336]
I was reluctant to post an issue and instead read through existing issues and tried various things but I'm still unable to get interactive completions when using zoxide with space and tab.

I'm using zsh with oh-my-zsh on Ubuntu 20.04
`zsh 5.8 (x86_64-ubuntu-linux-gnu)`
`zoxide v0.7.9`
`fzf 0.29.0 (brew)`

My loaded zsh plugins are:

```
git
zsh-autosuggestions
zsh-nvm
sudo
history-substring-search
```

I've added zoxide near the end of my `~/.zshrc` file with:
`eval "$(zoxide init zsh)"`

Commands to jump to a directory work, like `z home-as` jumps to `Documents/Projects/home-assistant` correctly.

What doesn't work correctly is `z home-as<space><tab>`. When I press tab I get a list of options from the directory I'm currently in. Almost the same as `cd<space><tab>` shows. More like `ls<space><tab>` as it shows files as well as directories.

The `zi` command works as expected.

Any idea how to debug this?

**Comment by tanc** [comment]
Thanks for the quick response! Unfortunately adding that and opening a new shell doesn't seem to change anything, the directory listing is still shown rather than interactive completions

**Comment by ajeetdsouza** [comment]
Just re-read the issue. Completions were added in v0.8.0+, looks like you need to update your version of zoxide.

**Comment by tanc** [comment]
🤦‍♂️ No way! I had assumed that feature had been there for a while as I only re-read the docs after installing a while ago and wanted to get completions working :-)

Thanks for your help, all good now.

**Comment by ajeetdsouza** [comment]
Haha, not a problem! 😄

**Comment by mdshahjalal5** [comment]
─ zoxide --version                   ─╯
zoxide 0.9.2

I have the same issue, space tab not showing fzf feature but showing z web 'z#/mnt/fed/web2' 'z#/mnt/fed/web2'

**Comment by ajeetdsouza** [comment]
@mdshahjalal5 please update your version of zoxide.
