### ISSUE TITLE
Distro support: add Slackware

### ISSUE THREAD

**Issue by anis-semmar** [ajeetdsouza/zoxide#337]
Hello,

Slackware is not listed in the supported platforms table. There are no Slackbuilds available.
Would it be possible to make one?

Cheers

**Comment by ajeetdsouza** [comment]
Hey @anis-semmar, you can use the generic installer listed in the README:

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

**Comment by anis-semmar** [comment]
right. i must have misread 'platform' for 'distribution' in the install guide. thanks
