### ISSUE TITLE
Option to match only file or directory

### ISSUE THREAD

**Issue by benmccann** [ajeetdsouza/zoxide#339]
[fasd](https://github.com/clvv/fasd) has:
>    -d         match directories only
    -f         match files only

That allows creating separate functions for opening a file or cd-ing to a dir:
```
e() { 
	local file;
	file="$(fasd -Rfl "$@" | fzf -1 -0 --no-sort +m --exit-0)";
	[[ -f "$file" ]] && $EDITOR -- "$file" && return 0 || return 1
}

d() {
	local dir;
	dir="$(fasd -Rdl "$@" | fzf -1 -0 --no-sort +m --exit-0)";
	[[ -d "$dir" ]] && cd -- "$dir" && return 0 || return 1
}
```

Would love to see it in zoxide as well

**Comment by benmccann** [comment]
There are some details about how `fasd` implements this over in the `pazi` repo: https://github.com/euank/pazi/issues/4#issuecomment-414036281

**Comment by ajeetdsouza** [comment]
I had a look into this, but I think this is out of the scope of the project for now. There's no clean way to find recent files, and in a lot of cases, the recent files of GUI applications may not be very relevant on a terminal.

**Comment by ppwwyyxx** [comment]
Second this. To me, lacking support for files is the only reason why other tools don't replace fasd.

> There's no clean way to find recent files

The way fasd does it makes sense: in addition to recording the pwd of every command as "recent directory", it records the [first argument of every command ](https://github.com/clvv/fasd/blob/90b531a5daaa545c74c7d98974b54cbdb92659fc/fasd#L117-L121) as a "recent file" if the file exists. It certainly will miss some files, but works pretty well in practice.
