### ISSUE TITLE
Show subdirectories in interactive completions

### ISSUE THREAD

**Issue by CharlesARoy** [ajeetdsouza/zoxide#340]
Is there a way to enable subdirectories to show up in the interactive completions even when the matching search term only appears in parent paths?

For example, I have a directory called `/data_fs/usr/croy/bio_pipeline/scripts_and_docs_CR` that I frequently navigate to. However, if I type `z bio<Space><Tab>`, I see the following:

![image](https://user-images.githubusercontent.com/46253001/150402658-b025f444-5b23-43a3-a506-55504d3efc97.png)

I know I could remember that I should type say, `z docs` instead, but I'd love it if there was an option to show subdirectories even when the match occurs in a parent directory.

**Comment by ajeetdsouza** [comment]
Try `z bio /`. The `/` matches a path separator that would appear somewhere after `bio`, thus effectively matching subdirectories.

**Comment by CharlesARoy** [comment]
Beautiful! Works like a charm. Thank you!

**Comment by ajeetdsouza** [comment]
Not a problem! I've added this to the README too, for future users.
