### ISSUE TITLE
Can't select in interactive completion on fish shell

### ISSUE THREAD

**Issue by NextAlone** [ajeetdsouza/zoxide#341]
when type `z foo<space><tab>` fzf opens and after selected one, it doesn't show on commandline

it works on zsh

**Comment by ajeetdsouza** [comment]
What version of zoxide are you using? Can you share your Fish configuration?

**Comment by NextAlone** [comment]
> What version of zoxide are you using? Can you share your Fish configuration?

0.8.0 latest on Arch, test with no config, not affected with my configs

**Comment by NextAlone** [comment]
https://user-images.githubusercontent.com/12210746/150510214-20bab9f9-c558-459f-82b0-d8f02bda6413.mp4

**Comment by ajeetdsouza** [comment]
The only way I can see this happening is if `zoxide query -i` returns a non-zero status code. The completion function is defined [here](https://github.com/ajeetdsouza/zoxide/blob/1ed009cc223d3e88311f3804639c0b9931978c73/templates/fish.txt#L76).

Can you try pasting this function after you call `zoxide init fish | source`? After this, try running the completion again, and then check the output of `/tmp/zoxide.log`:

```fish
function __zoxide_z_complete
    set -l tokens (commandline --current-process --tokenize)
    set -l curr_tokens (commandline --cut-at-cursor --current-process --tokenize)

    if test (count $tokens) -le 2 -a (count $curr_tokens) -eq 1
        # If there are < 2 arguments, use `cd` completions.
        __fish_complete_directories "$tokens[2]" ''
    else if test (count $tokens) -eq (count $curr_tokens)
        # If the last argument is empty, use interactive selection.
        set -l query $tokens[2..-1]
        set -l result (zoxide query -i -- $query)

        echo $status > /tmp/zoxide.log
        echo $result >> /tmp/zoxide.log

        commandline --current-process "$tokens[1] "(string escape $result)
        commandline --function repaint
    end
end
```

**Comment by NextAlone** [comment]
> The only way I can see this happening is if `zoxide query -i` returns a non-zero status code. The completion function is defined [here](https://github.com/ajeetdsouza/zoxide/blob/1ed009cc223d3e88311f3804639c0b9931978c73/templates/fish.txt#L76).
> 
> Can you try pasting this function after you call `zoxide init fish | source`? After this, try running the completion again, and then check the output of `/tmp/zoxide.log`:
> 
> ```fish
> function __zoxide_z_complete
>     set -l tokens (commandline --current-process --tokenize)
>     set -l curr_tokens (commandline --cut-at-cursor --current-process --tokenize)
> 
>     if test (count $tokens) -le 2 -a (count $curr_tokens) -eq 1
>         # If there are < 2 arguments, use `cd` completions.
>         __fish_complete_directories "$tokens[2]" ''
>     else if test (count $tokens) -eq (count $curr_tokens)
>         # If the last argument is empty, use interactive selection.
>         set -l query $tokens[2..-1]
>         set -l result (zoxide query -i -- $query)
> 
>         echo $status > /tmp/zoxide.log
>         echo $result >> /tmp/zoxide.log
> 
>         commandline --current-process "$tokens[1] "(string escape $result)
>         commandline --function repaint
>     end
> end
> ```

typed `z dwm <TAB>` then selected the first one below

![image](https://user-images.githubusercontent.com/12210746/157408404-f87c7ca5-cb82-4791-8d68-3d5c8f9dc4de.png)

then selected the first one below

zoxide.log
```log
0
/home/nextalone/Documents/Repos/Cpp/dwm
```

then go home and selected the second one 

zoxide.log
```log
0
/home/nextalone/.local/share/dwm
```
but still go into `/home/nextalone/Documents/Repos/Cpp/dwm` which is the first one

**Comment by NextAlone** [comment]
> > The only way I can see this happening is if `zoxide query -i` returns a non-zero status code. The completion function is defined [here](https://github.com/ajeetdsouza/zoxide/blob/1ed009cc223d3e88311f3804639c0b9931978c73/templates/fish.txt#L76).
> > Can you try pasting this function after you call `zoxide init fish | source`? After this, try running the completion again, and then check the output of `/tmp/zoxide.log`:
> > ```fish
> > function __zoxide_z_complete
> >     set -l tokens (commandline --current-process --tokenize)
> >     set -l curr_tokens (commandline --cut-at-cursor --current-process --tokenize)
> > 
> >     if test (count $tokens) -le 2 -a (count $curr_tokens) -eq 1
> >         # If there are < 2 arguments, use `cd` completions.
> >         __fish_complete_directories "$tokens[2]" ''
> >     else if test (count $tokens) -eq (count $curr_tokens)
> >         # If the last argument is empty, use interactive selection.
> >         set -l query $tokens[2..-1]
> >         set -l result (zoxide query -i -- $query)
> > 
> >         echo $status > /tmp/zoxide.log
> >         echo $result >> /tmp/zoxide.log
> > 
> >         commandline --current-process "$tokens[1] "(string escape $result)
> >         commandline --function repaint
> >     end
> > end
> > ```
> 
> typed `z dwm <TAB>` then selected the first one below
> 
> ![image](https://user-images.githubusercontent.com/12210746/157408404-f87c7ca5-cb82-4791-8d68-3d5c8f9dc4de.png)
> 
> then selected the first one below
> 
> zoxide.log
> 
> ```
> 0
> /home/nextalone/Documents/Repos/Cpp/dwm
> ```
> 
> then go home and selected the second one
> 
> zoxide.log
> 
> ```
> 0
> /home/nextalone/.local/share/dwm
> ```
> 
> but still go into `/home/nextalone/Documents/Repos/Cpp/dwm` which is the first one

and there is no additonal content added to commandline from the beginnign to the end. Instead zsh add the path to commandline

**Comment by ajeetdsouza** [comment]
What's the output of `fish --version`?

Can you change the function to this and try again:

```fish
function __zoxide_z_complete
    commandline --current-process "foobar"
    commandline --function repaint
end
```

**Comment by NextAlone** [comment]
fish, version 3.3.1-1093-g959e17fac


https://user-images.githubusercontent.com/12210746/157428982-22132ec5-32e7-4710-8822-9a864bd23579.mp4

**Comment by NextAlone** [comment]
failed, but if i bind the function to a key, it works

> This is looking like a Fish bug rather than a zoxide one. Does simply writing `commandline --current-process "foobar"` in your Fish shell do anything?
> 
> Try this script. Does `foo<space><tab>` change your command to `this is foo`?
> 
> ```fish
> function foo
> end
> 
> function _foo_complete
>   commandline --current-process "this is foo"
> end
> 
> complete -c foo -e
> complete -c foo -f -a '(_foo_complete)'
> ```

**Comment by NextAlone** [comment]
and if it works on your fish version?

**Comment by ajeetdsouza** [comment]
I have the same version of Fish, it seems to be working fine for me. I created an issue for you on Fish's tracker.

**Comment by NextAlone** [comment]
> I have the same version of Fish, it seems to be working fine for me. I created an issue for you on Fish's tracker.

oh, thanks for your work, and i will follow this issue

**Comment by NextAlone** [comment]
> I have the same version of Fish, it seems to be working fine for me. I created an issue for you on Fish's tracker: [fish-shell/fish-shell#8771](https://github.com/fish-shell/fish-shell/issues/8771)

according to fish shell developer, commandline in completion won't implement

**Comment by NextAlone** [comment]
Is there a way to implement it now?

**Comment by ajeetdsouza** [comment]
Might be. This would need some experimentation.

**Comment by antoyo** [comment]
Same issue here.

Any known workarounds?

**Comment by NextAlone** [comment]
Any improvement?

**Comment by NextAlone** [comment]
I have an idea and tested. Considering that rare file and dir named with `#`. And i will make a pr for you.
```fish
function __zoxide_z
    set argc (count $argv)
    if test $argc -eq 0
        __zoxide_cd $HOME
    else if test "$argv" = -
        __zoxide_cd -
    else if test $argc -eq 1 -a -d $argv[1]
        __zoxide_cd $argv[1]
    else
# changes below this
        if string match '*#*' $argv &>/dev/null
            set target (string match '*#*' $argv &>/dev/null | string replace \# '')
        else
            set target $argv
        end
        set -l result (command zoxide query --exclude (__zoxide_pwd) -- $target)
# changes above this
        and __zoxide_cd $result
    end
end
```

```fish
function __zoxide_z_complete
    set -l tokens (commandline --current-process --tokenize)
    set -l curr_tokens (commandline --cut-at-cursor --current-process --tokenize)

    if test (count $tokens) -le 2 -a (count $curr_tokens) -eq 1
        # If there are < 2 arguments, use `cd` completions.
        __fish_complete_directories "$tokens[2]" ''
    else if test (count $tokens) -eq (count $curr_tokens)
        # If the last argument is empty, use interactive selection.
        set -l query $tokens[2..-1]
# changes below this
        set -l result (zoxide query -i -- $query)
        and echo \#(string escape $result)
        commandline --function repaint
# changes above this
    end
end
```

When interactively selected a path, commandline shows like this
```fish
 z gram \#/home/nextalone/Workspace/telegram
```

**Comment by Zesko** [comment]
The version 0.8.2 works now for me using Fish shell version 3.4.1. Thanks!
