### ISSUE TITLE
Update Nushell script to support engine-q

### ISSUE THREAD

**Issue by ajeetdsouza** [ajeetdsouza/zoxide#345]
Nushell is upgrading to a new engine with numerous backward-incompatible changes, which breaks zoxide's initialization script. The script would have to be updated accordingly.

CC @fdncred

**Comment by fdncred** [comment]
indeed. we've tried to list most of the [breaking changes here](https://github.com/nushell/engine-q/issues/522) but I'm guessing we've missed a few.

**Comment by fdncred** [comment]
we might find some inspiration from Kubouch's update of the virtualenv scripts he's been working on.
https://github.com/kubouch/virtualenv/tree/engine-q-update/src/virtualenv/activation/nushell

**Comment by fdncred** [comment]
we also made a working prototype here - https://github.com/nushell/nu_scripts/blob/main/engine-q/prompt/zoxide-eq.nu

**Comment by hustcer** [comment]
Any update on this?

**Comment by ajeetdsouza** [comment]
I'm waiting for Nushell 0.60.0 to come to [nixpkgs](https://github.com/NixOS/nixpkgs), I can do a release once that happens. The script is (mostly) ready.

**Comment by pedoc** [comment]
@fdncred 
Hi,thank you for your work.

Is it possible to display git branche in prompt? It was displayed by default in versions before 0.44, but it is not displayed now

**Comment by fdncred** [comment]
Yes, it's built into the prompt in the oh-my.nu script which is in the nu_scripts repo.

**Comment by hamburger1984** [comment]
> I'm waiting for Nushell 0.60.0 to come to [nixpkgs](https://github.com/NixOS/nixpkgs), I can do a release once that happens. The script is (mostly) ready.

https://github.com/NixOS/nixpkgs/pull/165473 just got merged to master nixpkgs.

**Comment by krageon** [comment]
I'm currently using 

```
# =============================================================================
#
# Hook configuration for zoxide.
#

# Hook to add new entries to the database.
export def __zoxide_hook [] {
    shells | where active == true | each { |it| if (do -i {$it | get path | path exists} | length) != 0 { $it }} | get path | each { |it|
        zoxide add -- $it
    }
}

# =============================================================================
#
# When using zoxide with --no-aliases, alias these internal functions as
# desired.
#

# Jump to a directory using only keywords.
export def-env z [...rest:string] {
    let arg0 = ($rest | append '~' | first 1);
    cd (if ($rest | length) <= 1 && ($arg0 == '-' || ($arg0 | path expand | path exists)) {
       $arg0
    } else {
       let result = $'(zoxide query --exclude (pwd) -- $rest | str trim -r -c (char newline))'
       $result
    })
}

# Jump to a directory using interactive search.
export def-env zi  [...rest:string] {
    cd (zoxide query -i -- $rest | str trim -r -c (char newline))
}
```

and adding `use ~/.config/nushell/zoxide.nu [z,zi,__zoxide_hook]` to my config.nu, with `__zoxide_hook | ignore` in my prompt command definition.

**Comment by Nytelife26** [comment]
Another thing, can this be fixed? nushell doesn't have `ls -p`, so when using nushell and `zi`, you get this error.

![image](https://user-images.githubusercontent.com/22531310/164533793-50a01d50-1311-4bac-b59d-bc92d2b0b172.png)

**Comment by krageon** [comment]
I do not get that error. What versions of zoxide and nu do you have? What is the script for your zi command?

**Comment by ajeetdsouza** [comment]
@Nytelife26 this is fixed in https://github.com/ajeetdsouza/zoxide/pull/329.
