### ISSUE TITLE
_ZO_FZF_OPTS reset to default if changed in fish shell

### ISSUE THREAD

**Issue by jayrc2026** [ajeetdsouza/zoxide#347]
I changed the setting of _ZO_FZF_OPTS in my config.fish to _ZO_FZF_OPTS "--preview 'lsd {}' and now my zi command show a full screen fzf and says lsd: <dir-name> no such file or dir (os error 2) please let me know to reset _ZO_FZF_OPTS to default

**Comment by ajeetdsouza** [comment]
You can just remove the `_ZO_FZF_OPTS` variable. Is `lsd` not in your `$PATH`? What does `which lsd` return?

**Comment by jayrc2026** [comment]
which lsd returns /usr/bin/lsd
and I did return _ZO_FZF_OPTS but it won't return back to normal

**Comment by jayrc2026** [comment]
I tried uninstalling zoxide but that did not reset the any settings what more can I do I really like zoxide but I'm not able to get it back to default

**Comment by ajeetdsouza** [comment]
What is the output of `env | grep _ZO_`?

**Comment by jayrc2026** [comment]
env | grep _ZO_ output is blank just a new line and my prompt again

**Comment by jayrc2026** [comment]
Even when I echo $_ZO_FZF_OPTS I get a blank line

**Comment by ajeetdsouza** [comment]
Are you on the latest version of zoxide?

```sh
zoxide --version
```

**Comment by jayrc2026** [comment]
zoxide v0.8.0

**Comment by ajeetdsouza** [comment]
Can you run:

```fish
set -e _ZO_FZF_OPTS
zoxide query -i
```

and take a screenshot?

**Comment by jayrc2026** [comment]
![zoxide_fixed](https://user-images.githubusercontent.com/79093203/152542924-07d51465-0b41-4d84-ba21-603dead220d9.png)

**Comment by jayrc2026** [comment]
It is back to normal thank you......!!!!!!!!
May I know what was wrong

**Comment by ajeetdsouza** [comment]
`_ZO_FZF_OPTS` was still set, you can erase environment variables using `set -e`.

**Comment by jayrc2026** [comment]
Thank you now I understand why there was no change even after uninstalling
