### ISSUE TITLE
Feature request: add support for yash

### ISSUE THREAD

**Issue by ixnij** [ajeetdsouza/zoxide#349]
> Yash, yet another shell, is a POSIX-compliant command line shell written in C99 (ISO/IEC 9899:1999). Yash is intended to be the most POSIX-compliant shell in the world while supporting features for daily interactive and scripting use. 

Please see https://yash.osdn.jp/index.html.en, I really want to use zoxide in yash, thank you for this powerful program!

**Comment by ajeetdsouza** [comment]
Hi @ixnij, zoxide already does support POSIX shells. Add this to your rcfile:

```sh
eval "$(zoxide init posix --hook prompt)" 
```

**Comment by ixnij** [comment]
> Hi @ixnij, zoxide already does support POSIX shells. Add this to your rcfile:
> 
> ```shell
> eval "$(zoxide init posix --hook prompt)" 
> ```
👍
