### ISSUE TITLE
Jumping to directories results in error status in fish shell

### ISSUE THREAD

**Issue by cole-h** [ajeetdsouza/zoxide#35]
The recent `_ZO_ECHO` changes made `fish` shell return an error status after jumping to any directory (see the below screenshot). This doesn't affect functionality, but is certainly annoying and wrong behavior, considering it didn't behave like this before.

![image](https://user-images.githubusercontent.com/28582702/76728220-56694300-6713-11ea-9b27-4aace3a41bf4.png)

(I've verified the issue is unrelated to `direnv`, to assuage any concerns)

Bisected to:

```
f4cd1159c5419ece11b1d0147c23dba1c7579edc is the first bad commit
commit f4cd1159c5419ece11b1d0147c23dba1c7579edc
Author: Ajeet D'Souza <98ajeet@gmail.com>
Date:   Sun Mar 15 17:44:23 2020 +0530

    Add $_ZO_ECHO to echo match before navigating

 src/subcommand/init.rs | 26 +++++++++++++++++---------
 1 file changed, 17 insertions(+), 9 deletions(-)
```

Disclaimer: this may be present in other shells, but I only use `fish`.

**Comment by ajeetdsouza** [comment]
I tried it with

**Comment by ajeetdsouza** [comment]
The error happens due to `and [ -n _ZL_ECHO]`, resulting in an error code.

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/146e5709fbbf2e0428591105401ed8d294e81d6a. Thanks for pointing this out!

**Comment by cole-h** [comment]
Thanks, works perfectly! Hopefully you cut a new release soon, so those using the Nixpkgs package won't have to deal with that annoying (but cosmetic) issue for much longer... ;)

**Comment by ajeetdsouza** [comment]
There's still a few kinks to iron out with the exit codes, but I'm working on it!

**Comment by ajeetdsouza** [comment]
@cole-h, could you check that the latest commit works as expected for you?

**Comment by cole-h** [comment]
Works fine for me: still no error status!
