### ISSUE TITLE
zoxide unable to create data directory

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#351]
I'm trying to use tihs in nushell in wsl. I thought I had ran it here before but I'm not really sure.

This is what i get 
```
zoxide: unable to create data directory: /Users/fdncred/.local/share/zoxide

Caused by:
    Permission denied (os error 13)
```

That path does not exist. I figured it would be in /home/fdncred/blah

```
> which zoxide
╭───┬────────┬─────────────────────────────────┬─────────╮
│ # │  arg   │              path               │ builtin │
├───┼────────┼─────────────────────────────────┼─────────┤
│ 0 │ zoxide │ /home/fdncred/.cargo/bin/zoxide │ false   │
├───┼────────┼─────────────────────────────────┼─────────┤
│ # │  arg   │              path               │ builtin │
╰───┴────────┴─────────────────────────────────┴─────────╯
```

**Comment by ajeetdsouza** [comment]
That's interesting. I use WSL too, I've never seen this problem before.

What's the value of the following environment variables?
- `$_ZO_DATA_DIR`
- `$XDG_DATA_HOME`
- `$HOME`

What OS are you running in WSL?

Also, as a temporary workaround, you can set `_ZO_DATA_DIR='/home/fdncred/.local/share/zoxide'` for now.

**Comment by fdncred** [comment]
the first 2 don't exist but `$HOME` is wrong - pointing to `/Users/fdncred`. i wonder how that happened.

**Comment by ajeetdsouza** [comment]
No problem!
