### ISSUE TITLE
autocompletions aren't working

### ISSUE THREAD

**Issue by xenoterracide** [ajeetdsouza/zoxide#352]
So, I'm not sure if this is a bug, zsh "extension" conflict, or misunderstanding of the feature. If I do `cd ~/.config/yadm; cd; cd yadm` it works. If I then do `cd ya<tab>` nothing is completed or suggested. This is my full dotfiles which you could pull down with yadm.

This is the relevant line which is composed into my `~/.zshrc` by `yadm` https://github.com/xenoterracide/dotfiles/blob/master/.config/yadm/extra/alias.zsh#L16 `zi` in this case refers to https://z-shell.pages.dev/

I have tried doing this by hand after the initial prompt, including clearing ad reinitializing compinit.

```
❯ zoxide --version
zoxide v0.8.0
❯ zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
```

versions may be different on my Manjaro box, but both are experiencing the same problem. I also tried using the Oh My Zsh plugin for zoxide.

```zsh
for command completion in ${(kv)_comps:#-*(-|-,*)}
do
    printf "%-32s %s\n" $command $completion
done | grep zox
zoxide                           _zoxide
```

**Comment by ajeetdsouza** [comment]
Fuzzy completions are enabled with `<space><tab>`. Did you try `cd ya<space><tab>`?

**Comment by xenoterracide** [comment]
huh, no. Also surprising I was just expecting `ya<tab>` to do it, or even `cd <tab>` to give me at least some in addition to whatever is immediately there. Is any of that possible as a feature maybe?

**Comment by ajeetdsouza** [comment]
The idea is that `<tab>` invokes the same completions as the builtin `cd` command, but `<space><tab>` invokes zoxide's fuzzy completions. See the [GIF](https://github.com/ajeetdsouza/zoxide#getting-started) in the README.

Could you try loading it without `zi`? You can add this line right at the end of your `.zshrc`:

```sh
eval "$(zoxide init zsh --hook prompt --cmd cd)"
```

**Comment by xenoterracide** [comment]
no it works if I knew what I was doing, I'm just questioning whether there should, at least, be an option to do `cd <tab>`

**Comment by ajeetdsouza** [comment]
At the moment, there's no such option. However, the existing completion code can just be modified to suit your use case. Just add this after calling `eval "$(zoxide init zsh)"`:

```sh
function __zoxide_z_complete() {
    # Only show completions when the cursor is at the end of the line.
    [[ "${#words[@]}" -eq "${CURRENT}" ]] || return

    local result
    if result="$(zoxide query -i -- ${words[2,-1]})"; then
        __zoxide_result="${result}"
    else
        __zoxide_result=''
    fi
    printf '\e[5n'
}

function __zoxide_z_complete_helper() {
    local result="${__zoxide_z_prefix}${__zoxide_result}"
    [[ -n "${__zoxide_result}" ]] && LBUFFER="${LBUFFER} ${(q-)result}"
    zle reset-prompt
}
```
