### ISSUE TITLE
@Q for bash completion not available before Bash 4.4

### ISSUE THREAD

**Issue by nugend** [ajeetdsouza/zoxide#353]
Got a bad substitution error on my bash currently at 4.2

Wrote the bash completion out manually and removed the `@Q` and it worked mostly fine (I think, just trying it out now, not sure what expected behavior is).

I did a quick search and saw that this was added in 4.4 (not 100% sure, didn’t find a change log entry, just a mention)

**Comment by ajeetdsouza** [comment]
I updated the script to avoid adding completions below Bash 4.4+. Thanks for reporting this!
