### ISSUE TITLE
[macOS] Started getting `Failed to read /dev/tty` after brew upgrade

### ISSUE THREAD

**Issue by Dentrax** [ajeetdsouza/zoxide#356]
See the follow-up issue here: https://github.com/junegunn/fzf/issues/2745

Disabling the `eval "$(zoxide init zsh)"` in `~/.zshrc` fixed the issue.

```
zoxide v0.8.0
```

Any ideas on this?

**Comment by ajeetdsouza** [comment]
Could you check if this is the same issue as https://github.com/ajeetdsouza/zoxide/issues/321?

**Comment by Dentrax** [comment]
Oh, exact same issue I think. 🙈 Closing this now.
