### ISSUE TITLE
webi installer picks the wrong release

### ISSUE THREAD

**Issue by jacobo-diaz** [ajeetdsouza/zoxide#359]
When installing on Linux, web installer detects the right arch (Linux/x86_64), but downloads the wrong release (macOS):

```bash
[root@xxx]~# curl -sS https://webinstall.dev/zoxide | bash

Thanks for using webi to install 'zoxide@stable' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers

Downloading zoxide from
https://github.com/ajeetdsouza/zoxide/releases/download/v0.8.0/zoxide-v0.8.0-x86_64-apple-darwin.tar.gz

Saved as /root/Downloads/webi/zoxide/0.8.0/zoxide-v0.8.0-x86_64-apple-darwin.tar.gz
Extracting /root/Downloads/webi/zoxide/0.8.0/zoxide-v0.8.0-x86_64-apple-darwin.tar.gz
Installing to /root/.local/opt/zoxide-v0.8.0/bin/zoxide
zoxide@stable-bootstrap.sh: line 247: /root/.local/bin/pathman: cannot execute binary file: Exec format error
zoxide was installed successfully. Next, you'll need to set it up on your shell:

- For bash, add this line to ~/.bashrc:
    eval "$(zoxide init bash)"

- For fish, add this line to ~/.config/fish/config.fish:
    zoxide init fish | source

- For zsh, add this line to ~/.zshrc:
    eval "$(zoxide init zsh)"

- For any other shell, see the instructions at https://github.com/ajeetdsouza/zoxide.
```

**Comment by candrewlee14** [comment]
Try [webman](https://github.com/candrewlee14/webman).

It's an easy way to install zoxide and tools like it. Just run `webman add zoxide` :)

I built webman because of pain points with webi. It functions in a similar way but is a lot easier to work with. Check it out and let me know what you think.

**Comment by ajeetdsouza** [comment]
Hey, zoxide now ships its own installer once again. Sorry this took so long!

**Comment by coolaj86** [comment]
I believe this was related to an issue with os detection using `uname -a`, which included the system hostname, which would sometimes match OS strings when users would give their computers names like **Win**kle or **Darwin**ian or **Mac**Ostrich, etc.

Webi has since switched to using `uname -srm` which still works on both macOS and Linux, but sends only the necessary information.
