### ISSUE TITLE
panic in tmux

### ISSUE THREAD

**Issue by fundon** [ajeetdsouza/zoxide#36]
### CMD

```
tmux new-session -t a \; new-window
```

### Error mesg

```
could not move temporary database file: No such file or directory (os error 2)
```

**Comment by ajeetdsouza** [comment]
I tried this with `tmux 2.9a` on my system and it seems to work fine. Are you getting this error consistently?

**Comment by fundon** [comment]
```
λ tmux -V
tmux 3.0a
λ zoxide --version
zoxide 0.2.1
```

**Comment by ajeetdsouza** [comment]
Could you check if https://github.com/ajeetdsouza/zoxide/commit/b3470de7997f54cf22ebfa3d2e739caa4d4d9691 fixes this?

If you have Cargo installed, this should be as simple as `cargo install --git https://github.com/ajeetdsouza/zoxide --force`.

**Comment by fundon** [comment]
Still have this problem.

**Comment by ajeetdsouza** [comment]
@fundon, I've made some changes to the way temporary database files are handled in v0.3.0. Could you check if this fixes your issue?

**Comment by fundon** [comment]
Goog job! It's working.
