### ISSUE TITLE
Aliasing cd to z causes terminal to hang and crash

### ISSUE THREAD

**Issue by B1T3X** [ajeetdsouza/zoxide#360]
Hi,
I hope opening this issue is ok. I have been using Zoxide on my Mac (MacOS Monterey) and have been very happy with it using bash 5.1.16(1)-release, I have remapped `cd` to `z` and it has been working flawlessly.

Recently I have installed it on my PC running Pop!_OS and using bash 5.1.8(1)-release and I have aliased `cd` to `z` as well, although in the case of my PC every time I invoke `cd` the terminal hangs for a few seconds and then crashes and closes.
I would like to point out that I followed the configuration guide and my .bashrc contains the eval line initializing zoxide.
Using `z` after aliasing `cd` to it also causes the terminal to crash, the only way to use Zoxide is to unalias `cd` and invoke `z`.

### Specs:
**OS:** Pop!_OS 21.10
**Shell:** bash 5.1.8(1)-release
**Terminal:** Built-in terminal

### Steps to reproduce:
1. alias `cd` to `z`
2. invoke `cd`

Any help would be appreciated.
Thanks,
Orel

**Comment by ajeetdsouza** [comment]
What version of zoxide are you running? Is it fixed on the latest release?

**Comment by B1T3X** [comment]
> What version of zoxide are you running? Is it fixed on the latest release?

I'm using version `zoxide v0.4.3-unknown`, accodring to `zoxide -V`.
`apt list | grep zoxide` claims the version is `zoxide/impish,now 0.4.3-2 amd64` and is the latest one.

**Comment by ajeetdsouza** [comment]
The latest version is actually 0.9.0, Ubuntu repositories don't update very often. Instead, try directly downloading the binary from the release pages, or use the curl-based install script for now:

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

**Comment by B1T3X** [comment]
> The latest version is actually 0.9.0, Ubuntu repositories don't update very often. Instead, try directly downloading the binary from the release pages, or use the curl-based install script for now:
> 
> ```shell
> curl -sS https://webinstall.dev/zoxide | bash
> ```

Yup, this method works. Ugh.

Thanks for your quick and helpful response! Maybe it's worth adding a note in the README? I can do it myself if you'd like :)

Thanks again,
Orel

**Comment by ajeetdsouza** [comment]
No problem! I don't see much use of adding it to the README - there are too many bugs like this that are eventually fixed in later releases. Instead, there's a CHANGELOG.md to document them.
