### ISSUE TITLE
Database Error - Could not read from database (database is zero bytes long)

### ISSUE THREAD

**Issue by Cobular** [ajeetdsouza/zoxide#361]
On zoxide version 0.7.9, I've encountered a similar bug to #98 . The error text has changed somewhat, it's now the following:
```
zoxide: could not read from database: /home/cobular/.local/share/zoxide/db.zo

Caused by:
    Permission denied (os error 13)
```
The error is thrown on every `cd` or `z` call. 

The database is also 0 bytes:
```
$ pwd
/home/cobular/.local/share/zoxide
$ ls -ain
total 16
769400 drwxr-xr-x  2 1000 1000 4096 Mar  6 02:12 .
 68946 drwx------ 14 1000 1000 4096 Mar  6 02:07 ..
   358 -rw-------  1    0    0 7315 Mar  6 02:12 db.zo
```

and if I rename the database to something else, the issue goes away but unfortunately I've obviously now lost my database.

Other system notes: 
* WSL 2 under Windows 10
* Ubuntu 18.04
* Fish shell, tide prompt

If there's any other logs or something I can send that'd be great!

**Comment by ajeetdsouza** [comment]
The file permissions appear to have been changed, not sure how that happened. Can you try `chmod a+rw db.zo` on your file?

**Comment by Cobular** [comment]
Oh my god, the last `ls` command in my history was `-ain` not `-al` like I usually use and I misread the response!! It clearly still has size, it was somehow set to root ownership and that seems to have broken it, `chown`ing it back to me fixed it on the old database. Sorry to bother you!!

**Comment by ajeetdsouza** [comment]
Perhaps this was caused by https://github.com/ajeetdsouza/zoxide/issues/181. I'll push a fix for it once I have the time.

**Comment by Cobular** [comment]
Ah yep, that's probably it! Thanks for working on this awesome tool!!
