### ISSUE TITLE
Match prefix only (or: insert "/" at the start of pattern)

### ISSUE THREAD

**Issue by mizlan** [ajeetdsouza/zoxide#363]
I would like an option to only match from the start of the last component. As far as I know from my usage, this is effectively making this:
```
z hi
```
to:
```
z /hi
```

**Comment by ajeetdsouza** [comment]
To clarify, you want a command where `zi hi` matches `/foo/history` but NOT `/foo/myhistory`, correct? Which shell are you on?

**Comment by mizlan** [comment]
Yes. I'm on zsh

**Comment by ajeetdsouza** [comment]
That seems easy enough to do. Try adding this to your shell:

```sh
eval "$(zoxide init zsh --no-aliases)"

function z() {
  __zoxide_z "/$1"
}
```

`__zoxide_z` is a function defined exactly so that you can configure `z` to your individual liking.

**Comment by mizlan** [comment]
This breaks things such as `$ z` and `$ z -` though, and I'm not sure what else.

**Comment by ajeetdsouza** [comment]
Then the function becomes a bit larger:

```sh
function z() {
    if [[ "$#" -eq 0 ]]; then
        cd ~
    elif [[ "$1" = '-' ]]; then
        cd -
    elif [[ -d "$1" ]]; then
        cd "$1"
    else
        local result
        result="$(zoxide query --exclude "$PWD" -- "/$1")" && cd "$result"
    fi
}
```

**Comment by mizlan** [comment]
Thank you!
