### ISSUE TITLE
`z --version` zoxide: no match found

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [ajeetdsouza/zoxide#365]
I installed zoxide on Manjaro Linux 21.2.5 "Qonos" with pamac, which is the same as `pacman -S zoxide`. Then [added](https://codeberg.org/LifeSymbiont/dotfiles/commit/5ee34da6a12d71c52ba912a3c5aab80bfab7dd7d) `eval "$(zoxide init zsh)"` in my `.zshrc` after the call to `source "$ZSH/oh-my-zsh.sh"`. After `omz reload` when I use `z --version` I get `zoxide: no match found`. I don't know where oh-my-zsh keeps `.zcompdump` so I couldn't do `rm ~/.zcompdump*; compinit`. I already have `fzf` installed.

Do I need to do something else before I start using zoxide?

**Comment by ajeetdsouza** [comment]
`z --version` won't work because `z` is a shell function installed by zoxide. You want to use `zoxide --version` instead.

It sounds like you've installed it correctly, is it not working for you?
