### ISSUE TITLE
Error when cd-ing into any directory in fish shell

### ISSUE THREAD

**Issue by martindzejky** [ajeetdsouza/zoxide#37]
Hello, I installed `zoxide` according to the instructions in the README file. I also initialized it for `fish` shell.

Now, when I `cd` into any directory, I get this error:

```
error: Found argument '--add' which wasn't expected, or isn't valid in this context

USAGE:
    zoxide query [FLAGS] [keywords]...

For more information try --help
```

```
zoxide --version
zoxide 0.2.1

fish --version
fish, version 3.0.2
```

Any help with this?

**Comment by cole-h** [comment]
What is the output of `type _zoxide_hook` and `type z`? What is the actual command you're running before you encounter this error? Does this still happen if you run `zoxide init fish | source` in a pre-existing fish instance and start `cd`ing/`z`ing around?

**Comment by ajeetdsouza** [comment]
Have you aliased `zoxide`, by any chance?

**Comment by martindzejky** [comment]
I don't know what happened but today I started my computer and this issue was no longer present 🤷‍♂ . I am not only hitting #35 which is not a big deal and will probably be fixed in the next release.

Again, not sure why it did not work before, but it works now (and whoa, it is fast!). So I'm closing this. Thanks 🙂

**Comment by ajeetdsouza** [comment]
No problem! And the error codes have been fixed already, they'll be added in the next release!
