### ISSUE TITLE
[zsh] interactive compleition with z <term><space><tab> requires addittional <CR> after selection

### ISSUE THREAD

**Issue by ibhagwan** [ajeetdsouza/zoxide#374]
zsh 5.8.1, fzf 0.29

**`zi` works as expected.**

When using the same search term with `<space><tab>` the selected directory gets filled in the prompt but requires additional `<CR>` to process, to illustrate:

Running `z nv<space><tab>`:
![image](https://user-images.githubusercontent.com/59988195/161408946-4c026cd5-31fc-4387-9aaf-2be611fc57c7.png)

After pressing `<CR>`:
![image](https://user-images.githubusercontent.com/59988195/161408973-86935602-549e-47d2-8164-d4fe7bc0891d.png)

Pressing `<CR>` again cd's into the correct folder:
![image](https://user-images.githubusercontent.com/59988195/161408993-09304da8-e581-417a-9a36-ed057d07a1cd.png)

**Comment by ajeetdsouza** [comment]
That's by design, it's similar to how I've seen other interactive selection tools operate.
