### ISSUE TITLE
Question: is it possible to execute a hook when entering a directory?

### ISSUE THREAD

**Issue by Integralist** [ajeetdsouza/zoxide#376]
I have the following in my `.bashrc`:

```bash
function cd {
  command cd "$@"
  RET=$?
  ls
  return $RET
}
```

When using `z` to switch directories I'd like to be able to do something similar where I can run arbitrary commands once the directory has switched. Is this possible at the moment or would this be something that could be added to a 'new feature' list?

Thanks.

**Comment by ajeetdsouza** [comment]
Hey @Integralist, you can replace the `__zoxide_cd` command to do this.

**Comment by Integralist** [comment]
@ajeetdsouza aha! awesome, that worked perfectly. Thank you! 🙂 

```bash
function __zoxide_cd {
  # Original implementation...
  # https://github.com/ajeetdsouza/zoxide/blob/df148c834fa0eb4a99cac18720e05059bf771430/templates/bash.txt#L17-L21
  command cd "$@"
  RET=$?
  ls
  return $RET
}
```
