### ISSUE TITLE
zoxide man page not found

### ISSUE THREAD

**Issue by tapyu** [ajeetdsouza/zoxide#378]
Dears, it is probably a silly issue, so sorry in advance... But I cannot find the `man zoxide`....

I installed using `cargo`, as usual. I know that there is a [directory](https://github.com/ajeetdsouza/zoxide/tree/main/man/man1) in this repo that has the zoxide man page files, but I am not sure what I should do with it as I never faced a problem with the man pages.

Thank you.

**Comment by ajeetdsouza** [comment]
Hey @tapyu, `cargo install` does not install manpages: https://github.com/rust-lang/cargo/issues/2729

The workaround is to either install using your system's package manager, or to download and copy the manpages of that specific release over to `$MANPATH`.

**Comment by gennaro-tedesco** [comment]
> The workaround is to either install using your system's package manager

I tried on a Mac and `brew install zoxide` does not install the man page either.

**Comment by ajeetdsouza** [comment]
@gennaro-tedesco opened a bug for you here: https://github.com/Homebrew/homebrew-core/issues/108485

**Comment by ajeetdsouza** [comment]
@gennaro-tedesco update: the fix is merged into homebrew, you can get them with `brew update && brew reinstall zoxide`.

**Comment by gennaro-tedesco** [comment]
Thank you very much, I confirm I can now access `man zoxide`!

<img width="1273" alt="Screenshot 2022-08-20 at 19 17 33" src="https://user-images.githubusercontent.com/15387611/185758945-60bde067-6da5-49a3-b48e-87880206a43a.png">
