### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by sylvestre** [ajeetdsouza/zoxide#380]
it would be nice to have a new release. 
Unlike the current trunk, 0.8.0 depends on clap beta. Some packaging tooling (Debian packages for example) refuse to depend on beta version.

thanks!

**Comment by jeremiahpslewis** [comment]
Would be lovely to bump zoxide on homebrew as well, now that it supports the latest nushell

**Comment by ajeetdsouza** [comment]
Released v0.8.1.

**Comment by sylvestre** [comment]
Many thanks!
