### ISSUE TITLE
nushell .zoxide.nu script

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#381]
Hey @ajeetdsouza,
Thanks for landing some changes and landing functionality to support nushell today. Sorry we're breaking things all the time. :) I pinged you in a separate nushell issue that you opened but had another question about the .zoxide.nu script from today's commits. 

1. It's working great! so far. No issues whatsoever following your instructions about env.nu and config.nu. (glad we added that env.nu, it makes a few things easier)
2. I noticed that you're doing `str trim -r -c "\n"` in a few places. While that works great, I just wanted to let you know that you may be able to get away with just `str trim -r` since `\n` is one of the default characters (called delimiters below). This is a snippet from trim_.rs in nushell.

```rust
    let delimiters = match char_ {
        Some(c) => vec![c],
        // Trying to make this trim work like rust default trim()
        // which uses is_whitespace() as a default
        None => vec![
            ' ',    // space
            '\x09', // horizontal tab
            '\x0A', // new line, line feed
            '\x0B', // vertical tab
            '\x0C', // form feed, new page
            '\x0D', // carriage return
        ], //whitespace
    };

...
        s.trim_end_matches(&delimiters[..]).to_string()
```

There's no harm in leaving it the way you have it and if you are specifically and only looking for `\n` then what you have is right.

Once again, thanks so much for continuing to support us. I, for one, love zoxide. Keep up the good work! :)

**Comment by ajeetdsouza** [comment]
Thank you, I appreciate it! It's always an interesting challenge to look at the Nushell changelog and wonder, "how can I hack zoxide into this now?"

> I noticed that you're doing `str trim -r -c "\n"` in a few places.

That's intentional. I don't mind writing a bit more code as long as it's "correct" -- specifying the `\n` explicitly now means that zoxide would work with directory names that have trailing spaces.

**Comment by fdncred** [comment]
head's up https://github.com/nushell/nushell/pull/5301 should fix the `cd -` issue. Also, another breaking change is inbound, `source`, `use`, `register` now have `!` at the end after this PR lands https://github.com/nushell/nushell/pull/5300.

**Comment by ajeetdsouza** [comment]
That's great, thanks!
