### ISSUE TITLE
integration with neovim dirictories

### ISSUE THREAD

**Issue by SamDc73** [ajeetdsouza/zoxide#383]
i use neovim a lot, and i want to make zoxide to remember the files/directories that i open using the nvim command.
is that possible ?

**Comment by ajeetdsouza** [comment]
What shell do you use?

**Comment by SamDc73** [comment]
zsh

**Comment by ajeetdsouza** [comment]
Should be a simple zsh function:

```zsh
function nvim() {
  for opt in "$@"; do
    [[ -d "$opt" ]] && zoxide add "$opt"
  done
  command nvim "$@"
}
```
