### ISSUE TITLE
Nushell / Zoxide integration ./

### ISSUE THREAD

**Issue by jeremiahpslewis** [ajeetdsouza/zoxide#389]
Nushell version 0.60+ seems to prepend / postpend slashes as part of its autocomplete, e.g.`./micro/` or `./filename.txt`, which seems to create issues for zoxide's index building / finding appropriate matches. Is there any way that zoxide could strip out the 'contentless' `./` when doing input matching?

**Comment by ajeetdsouza** [comment]
Could you explain what exactly you're trying to do?

**Comment by jeremiahpslewis** [comment]
For foldername `test`:

```nu
z tes
```
opens up the test directory

```nu
z ./tes
```

does not.

The latter is weird and not a typical input **except** that the nushell tab completion has a tendency to prepend `./`

**Comment by ajeetdsouza** [comment]
I don't think queries are supposed to work with tab completion. If you try to `z ./tes`, zoxide will try to look for a `tes` in the current working directory, which of course doesn't exist. This seems like intended behavior to me.
