### ISSUE TITLE
use XDG compatible locations for the database/configs?

### ISSUE THREAD

**Issue by qmx** [ajeetdsouza/zoxide#39]
It'd be nice to use standard config folders for this tool instead of just dropping configs and the database at the home folder for a user.

if you're interested about having this implemented, crates [like this one](https://crates.io/crates/dirs) can be used to accomplish this easily.

Happy to work on a PR if there's interest.

**Comment by qmx** [comment]
also this crate I mentioned solves #7 in a cross-platform way

**Comment by ajeetdsouza** [comment]
This has been discussed in https://github.com/ajeetdsouza/zoxide/issues/16, our conclusion was not to change anything for now as it breaks current setups.

If a major change in the future breaks compatibility unavoidably, I would be open to doing this.

**Comment by ajeetdsouza** [comment]
This has been added in https://github.com/ajeetdsouza/zoxide/pull/46/commits/0617571807c461df094ad5e8dc95a154a587db65, and will be released with `zoxide v0.3`!
