### ISSUE TITLE
Adding new visited dirs to PATH

### ISSUE THREAD

**Issue by taupezen** [ajeetdsouza/zoxide#390]
Hi,

i've recently found that zoxide adds newly visited dirs to my path.

- zoxide v0.8.1 (installed by cargo)
- ubuntu 20.04
- Fishshell

```
$ mkdir TESTZOXDIR
$ echo $PATH | string split " " | rg 'TESTZOXDIR'
$ cd TESTZOXDIR
TESTZOXDIR $ cd ..
$ echo $PATH | string split " " | rg 'TESTZOXDIR'
/home/fabrice/TESTZOXDIR
```

Regards,
Fabrice

**Comment by ajeetdsouza** [comment]
I don't think that's zoxide. zoxide does not modify `$PATH` at all:

```console
$ zoxide init fish | rg PATH
```

You may want to check the rest of your configuration.

**Comment by taupezen** [comment]
Indeed, no modification in the hook functions.

But there seems to be a mismatch of scope using universal fish_user_paths variable, maybe in an underlying behavior.

It's like there would be an automatic append in Fish's fish_user_paths, which are then added automatically by the shell in the PATH env-var. It's hard to pin-point who exactly is causing this but it appeared that my PATH got modified when i brought zoxide in.

Would you like me to test something ?

**Comment by ajeetdsouza** [comment]
I would have suggested using `set fish_trace 1`, but unfortunately, it doesn't work with commands inside hooks (https://github.com/fish-shell/fish-shell/issues/8966).

- Have you verified that this does not occur when zoxide is disabled?
- The only function that is run when you change directories is `__zoxide_hook`. Does running it change your $PATH?

**Comment by taupezen** [comment]
Hi,

Yes, indeed, I verified that the behavior did not reproduce in bash and zsh.

__zoxide_hook did not changed my path ; nor did any additional test. No more of that strange behavior since I changed my fish path config from : e.g. `fish_add_path -p "$GHCUP/bin"` to `fish_add_path -P -p "$GHCUP/bin"` ([fish_add_path](https://fishshell.com/docs/current/cmds/fish_add_path.html) `-P` manipulate path var directly), and purged my path. Afterwards, the problem does not occur, up to now.

**Comment by ajeetdsouza** [comment]
I see, closing this issue then.
