### ISSUE TITLE
Feature Request: add support for increment/decrement subcommands

### ISSUE THREAD

**Issue by JS-Zheng** [ajeetdsouza/zoxide#392]
# Background
Our team has a large project, which has multiple branches located in different paths (has the same directory structures), for example: 
- /branch_a/device/driver/
- /branch_b/device/driver/
- /branch_c/device/driver/

Therefore, a directory name is not an effective factor for this case, adjusting rank/weight is a very useful feature for us.

# FR
Add an **inc(rement)** subcommand and a **dec(rement)** to update rank/weight manually.

For example:
```sh
# increment rank by default value
zoxide inc /branch_a/device/driver/  

# decrement rank by default value
zoxide dec /branch_b/device/driver/     

# increment rank by the specified value
zoxide inc=10 /branch_c/device/driver/ 
```

**Comment by ajeetdsouza** [comment]
Have you tried the `<SPACE><TAB>` completions that ship with zoxide v0.8.0+? They seem ideal for this kind of structure.

In case you're not familiar with how it works, there's a GIF in the [README](https://github.com/ajeetdsouza/zoxide#getting-started).

**Comment by JS-Zheng** [comment]
Yes, I usually use `<SPACE><TAB>` fzf completions. However,  I want to increase the rank of the recently developed branches, or reduce the rank of the outdated branches that has entered the maintenance cycle, so that the order of the fzf completions is more effective.

**Comment by ajeetdsouza** [comment]
Closing in favour of https://github.com/ajeetdsouza/zoxide/issues/453.
