### ISSUE TITLE
Initialization error?

### ISSUE THREAD

**Issue by chrisgrieser** [ajeetdsouza/zoxide#397]
I installed via Homebrew (`brew install zoxide`), and even after Terminal restart, there doesn't seem to be any `z` or `zi` command registered. Trying to set anything via `zoxide init` also does not work, bur rather results in some error, where I do not really understand what's going on. (the `$SHELL` env variable does exist.)

```zsh
z
# result: zsh: command not found: z
zoxide init
# result: error: The following required arguments were not provided: <SHELL>
```

**Comment by ajeetdsouza** [comment]
See the [README](https://github.com/ajeetdsouza/zoxide#installation). zoxide is a shell plugin, and needs to be set up on your shell first.

**Comment by chrisgrieser** [comment]
Uggh, my bad. Have only read `zoxide --help`, and not the README here. 

(Might be a good idea to add some more info to that error message though, alone it is a bit confusing)
