### ISSUE TITLE
Bash tab completion: Whitespace not escaped

### ISSUE THREAD

**Issue by imambungo** [ajeetdsouza/zoxide#398]
![image](https://user-images.githubusercontent.com/34421249/169538884-31676368-1a78-41fe-8ca2-be228981b9ab.png)

`New World/` vs `New\ World/`

**Comment by name-snrl** [comment]
This can be fixed by adding `complete -o dirnames j` to a bash configuration file such as .bashrc. Hopefully this will be fixed soon
