### ISSUE TITLE
The latest z.lua is 4-5 times faster than zoxide now.

### ISSUE THREAD

**Issue by skywind3000** [ajeetdsouza/zoxide#40]
[z.lua](https://github.com/skywind3000/z.lua) is now 4-5 times faster than zoxide, with the power of a [native module](https://github.com/skywind3000/czmod) written in c.

As a portable script, `z.lua` will not run everytime the prompt display, but only when you change your current directory. So I still recommend the pure lua script directly for portability and flexibility.

For someone who really care about 10ms or 1ms, `czmod` can help them to gain the ultimate speed.

performance:

Average performance:

| Name | czmod | zoxide |
|-|-|-|
| **Update Time** | 1.6ms | 7.1ms |
| **Query Time** | 1.5ms | 5.8ms |
| **Binary Size** | 102 KB | 2.2 MB |

Benchmark with `hyperfine` for updating:

![](https://skywind3000.github.io/images/p/czmod/i-add.png)

and searching:

![](https://skywind3000.github.io/images/p/czmod/i-query.png)

--

According to this, the README of this project is totally outdated and needs an update.

**Comment by ajeetdsouza** [comment]
Once again, I don't see the need for your unwarranted aggression, using phrases like "totally outdated" minutes after the release of `czmod`. I agree that the `czmod` specific functions does perform faster than `zoxide`, but:

- I really don't see the sense in creating a barebones implementation that falls back to `z.lua` for everything else - it needlessly increases complexity for the user.
- In your table, you fail to count the size of the `lua` binary - I had to install Lua just to run this
- You yourself recommend not using `czmod`, which means the average user is still stuck on the (much slower) Lua implementation.

This comes across to me as rather petty, but all the same, if it eases your mind, I will remove that line from the README.
