### ISSUE TITLE
cd:1: maximum nested function level reached; increase FUNCNEST? zoxide

### ISSUE THREAD

**Issue by niksingh710** [ajeetdsouza/zoxide#403]
i get this when i use 
`eval $(zoxide init --cmd cd zsh)`

**Comment by ajeetdsouza** [comment]
What's the output of `zsh --version`?

**Comment by niksingh710** [comment]
> What's the output of `zsh --version`?

`zsh 5.8.1 (x86_64-ubuntu-linux-gnu)`

**Comment by niksingh710** [comment]
> What's the output of `zsh --version`?

I have used apt to install zoxide.

**Comment by niksingh710** [comment]
It was an old zoxide issue that i had installed using `apt` installing it via script solved it.

**Comment by ktzsolt** [comment]
@ajeetdsouza Hi! I just installed zoxide on ubuntu 22.04 with apt as per the zoxide install documentation, and has the same problem. the version apt installs is 
```
zoxide --version
zoxide v0.4.3-unknown
```

```
sudo apt install zoxide
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  aspnetcore-runtime-6.0 aspnetcore-targeting-pack-6.0 docker-scan-plugin dotnet-apphost-pack-6.0 dotnet-hostfxr-6.0
  dotnet-runtime-6.0 dotnet-targeting-pack-6.0
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  zoxide
0 upgraded, 1 newly installed, 0 to remove and 33 not upgraded.
Need to get 346 kB of archives.
After this operation, 999 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 zoxide amd64 0.4.3-2 [346 kB]
Fetched 346 kB in 1s (404 kB/s)
Selecting previously unselected package zoxide.
(Reading database ... 190235 files and directories currently installed.)
Preparing to unpack .../zoxide_0.4.3-2_amd64.deb ...
Unpacking zoxide (0.4.3-2) ...
Setting up zoxide (0.4.3-2) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...
```

How am I supposed to install the new version of zoxide with apt? Thanks!

**Comment by atomjack** [comment]
I came across this problem as well, on Ubuntu 22.04.1. I had used apt to install zoxide, and like @ktzsolt I had v0.4.3-unknown. The fix is to remove zoxide with apt, then use the curl command in the instructions to re-install a newer version of zoxide. Then, I was able to have z aliased to cd and everything works fine.

It might be a good idea to make a note in the instructions for Ubuntu that the apt version is out of date.

**Comment by ajeetdsouza** [comment]
> How am I supposed to install the new version of zoxide with apt?

Unfortunately, apt repositories are super out of date, the recommended way is to use the install script:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

> It might be a good idea to make a note in the instructions for Ubuntu that the apt version is out of date.

Done: https://github.com/ajeetdsouza/zoxide/commit/90c66df2a872d7b66339561370512a8b9aa682df

**Comment by ktzsolt** [comment]
I eventually did remove the apt package and installed with the curl script and it works fine, great project! Also thanks for the clarification!
