### ISSUE TITLE
cannot update from powershell zoxide version 0.8.1

### ISSUE THREAD

**Issue by tourmaline3333** [ajeetdsouza/zoxide#407]
I have same issue  #301.
but I use zixide 0.8.1

- scoop nstall zoxide
- vi $PROFILE
---
# For zoxide v0.8.0+
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd'
 }
    (zoxide init --hook $hook powershell | Out-String)
})
---

database was updated from nushell.

**Comment by tourmaline3333** [comment]
I fix the $PROFILE delete below and solved.
---
Invoke-Expression (&starship init powershell)
---

I don't find the solution both script yet.

**Comment by ajeetdsouza** [comment]
Hey @tourmaline3333 , could you share your $profile script? starship+zoxide seem to be working fine for me.

Also, what version of Starship are you on?

**Comment by tourmaline3333** [comment]
Thank you for your help.
But I solved the issue,when I copy the $PROFILE just a while ago...

starship : 1.8.0

- faile
- --
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } e { 'pwd' }
    (zoxide init --cmd j --hook $hook powershell | Out-String)
})

- oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\powerlevel10k_l.omp.json" | Invoke-Expression
---

-success
---
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\powerlevel10k_l.omp.json" | Invoke-Expression

Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } e { 'pwd' }
    (zoxide init --cmd j --hook $hook powershell | Out-String)
})
---

I just changed the order

**Comment by ajeetdsouza** [comment]
Makes sense. I'll close this, then.
