### ISSUE TITLE
Could not deserialize database

### ISSUE THREAD

**Issue by Tchoupinax** [ajeetdsouza/zoxide#41]
Hello,

i have an error that i do not know to resolve. I guess it can be an error about the storage, maybe i should remove the file ?

```
あ→ z
Error: could not deserialize database

Caused by:
    io error: failed to fill whole buffer
```

Some information
```
あ→ uname -a
Linux DESK-HOME 5.5.9-arch1-2 #1 SMP PREEMPT Thu, 12 Mar 2020 23:01:33 +0000 x86_64 GNU/Linux
```

**Comment by ajeetdsouza** [comment]
Looks like your database file is corrupted! Removing the file will fix the issue, although you'll lose your current entries. By any chance, did you create/edit the file manually?

**Comment by Tchoupinax** [comment]
Oh, thank you for your very quickly answer !

Yeah, i removed the files and it works again. However, i know i tried to remove file both (`~/.zo` and `~/.zo.tmp`) several times and they did not disapear... but they had size = 0 bytes.

Now all is ok.

I did not edit the file neither create it manually.

I created this issue to notice to you in case there is a identified issue you could fix anyway it is ok for me. For other people, the solution is:

```Removing the file will fix the issue```
