### ISSUE TITLE
[Bug] (eval):1: parse error near 'then'

### ISSUE THREAD

**Issue by luiz00martins** [ajeetdsouza/zoxide#411]
Executing `eval $(zoxide init zsh)` yields that error. However, copying the output of `zoxide init zsh` and pasting directly on the zsh terminal executes fine.

I'm using PopOS, zoxide v0.4.3, and zsh 5.8.1.

**Comment by ajeetdsouza** [comment]
That's a very old version of zoxide. Could you try using the install script directly?

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

**Comment by luiz00martins** [comment]
Debian Moment™. That worked, thank you.

On a sidenote, how would I uninstall zoxide using this method?

**Comment by ajeetdsouza** [comment]
It's a portable binary, you can just delete it:

```sh
rm "$(which zoxide)"
```
