### ISSUE TITLE
Unable to locate package zoxide.

### ISSUE THREAD

**Issue by BadWolf47** [ajeetdsouza/zoxide#414]
When i do an `apt install zoxide`, it returns a '`Unable to locate package`'.

OS: Linux Mint 20.3

**Comment by ajeetdsouza** [comment]
Use the generic installer:

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

Linux Mint 20 is based on Ubuntu 20.04, and zoxide is only available on Ubuntu 21.04+.
