### ISSUE TITLE
Use `nushell` v0.63 `PWD` hook instead of custom prompt

### ISSUE THREAD

**Issue by leroycep** [ajeetdsouza/zoxide#416]
In v0.63 of nushell, they introduced [environment change hooks](https://www.nushell.sh/blog/2022-05-24-nushell_0_63.html#hooks-jt). This means `zoxide` can listen for `PWD` changes directly:

```nu
hooks: {
    env_change: {
        PWD: [{|before, after|
            zoxide add $after
        }]
    }
}
```

**Comment by ajeetdsouza** [comment]
Blocked on https://github.com/nushell/nushell/issues/5951.
