### ISSUE TITLE
Accents are not supported

### ISSUE THREAD

**Issue by fnuttens** [ajeetdsouza/zoxide#417]
If an accent exists in a stored path (e.g. `D:\Documents\Dev\foobàr\baz`), then an error occurs, here with `z baz`:

```powershell
Set-Location:
Line |
  17 |          Set-Location -LiteralPath $dir -Passthru -ErrorAction Stop
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\Documents\Dev\foob├ár\baz' because it does not exist.
```

I observed this behavior with 'é' and 'à'. I use PowerShell 7 on Windows.

**Comment by ajeetdsouza** [comment]
This appears to be a bug in PowerShell, I've filed an issue for you here: https://github.com/PowerShell/PowerShell/issues/18119

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/9d9bcfcac29610e3d4d36243ef7bc8a4765f67f0.
