### ISSUE TITLE
POSIX sh support

### ISSUE THREAD

**Issue by emersion** [ajeetdsouza/zoxide#42]
Would be nice to have POSIX sh support instead of just Bash. Would allow people to use zoxide on a wide variety of shells.

The Bash init script doesn't seem too far from being POSIX.

**Comment by cole-h** [comment]
ShellCheck reports the following:

```
In posixify line 16:
        result="$(zoxide query $@)" || return "$?"
                               ^-- SC2068: Double quote array expansions to avoid re-splitting elements.


In posixify line 19:
                _z_cd "${result:7}" || return "$?"
                       ^---------^ SC2039: In POSIX sh, string indexing is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, string indexing is u...
```

Is this all that's necessary, or is there more that it missed?

**Comment by ajeetdsouza** [comment]
Support for PWD hooks in POSIX shells has been added in  https://github.com/ajeetdsouza/zoxide/commit/7532fe98d88532022a95d387c4d21928b7026336.
