### ISSUE TITLE
Add MPR installation instructions to README

### ISSUE THREAD

**Issue by hwittenborn** [ajeetdsouza/zoxide#423]
Hi! I've recently added zoxide to the [MPR](https://mpr.makedeb.org/packages/zoxide), and I was wondering if you'd be fine with having installation instructions for it in the README.

The MPR is a platform similar to the AUR on Arch Linux, except that the files on the MPR instead build `.deb` packages. It would function fairly similar to the Debian/Ubuntu installation methods currently in the README, but the zoxide package on the MPR can be updated as soon as a release is made, which isn't the case for the standard Debian/Ubuntu methods.

Is this something you'd be interested in?

**Comment by ajeetdsouza** [comment]
Hey @hwittenborn, MPR looks really cool! Unfortunately, MPR doesn't seem to have a lot of mainstream adoption at the moment, so I can't merge this just yet. That said, something like MPR was long overdue on Debian systems, so I'm really happy this has happened and I'd be happy to revisit this once it becomes more popular!

**Comment by ajeetdsouza** [comment]
On an unrelated note, when I tried to explore the repo by seeing what other packages you maintain, I was asked to sign up first (why?). I couldn't sign up either, because I'm on Fedora and don't have `makedeb` installed, which is how the website seems to block automated account creation:

> To protect the MPR against automated account creation, we kindly ask you to provide the output of the following command (required):
>
> ```sh
> makedeb --mpr-check | sed -r 's#[0-9]+#47b#g' | md5sum | cut -c1-6
> ```

The question seems to be the same every time too, so I imagine bots shouldn't have too much trouble getting around this.

**Comment by hwittenborn** [comment]
> when I tried to explore the repo by seeing what other packages you maintain, I was asked to sign up first (why?)

I'm not sure myself - the MPR is based on the codebase of the AUR, and I'm thinking it might be from there. Could I ask what URL you were on right before you were brought to the sign up page? You should be able to view the packages a user maintains [here](https://mpr.makedeb.org/packages?O=0&SeB=m&K=hwittenborn&outdated=&SB=p&SO=a&PP=10&submit=Go) though.

> The question seems to be the same every time too, so I imagine bots shouldn't have too much trouble getting around this.

The `sed` part of the command should change after a new user signs up, resulting in a new command for each valid sign up. This also originated in the AUR and I still think a bot could be programmed to work around that fairly easily, so I plan on dropping a captcha complete at some point, or at least using a different solution that's less invasive towards the user.

**Comment by ajeetdsouza** [comment]
I clicked on your username and was redirected to the login page: https://mpr.makedeb.org/account/hwittenborn

It seems reasonable to expect that I should be able to look up a user without signing in. Perhaps you could hide the user's email in such a situation.

**Comment by hwittenborn** [comment]
> I clicked on your username and was redirected to the login page: https://mpr.makedeb.org/account/hwittenborn

That makes sense, I remember it being supposed to behave like that.

> It seems reasonable to expect that I should be able to look up a user without signing in. Perhaps you could hide the user's email in such a situation.

I agree that you should be able to view user pages too, I'll make an issue in the project's bug tracker, but I'm working on some other stuff with makedeb at the moment so I can't give a time on how long it'll take.
