### ISSUE TITLE
zoxide prevents use of zsh cd shortcuts to dirstack elements

### ISSUE THREAD

**Issue by grimm26** [ajeetdsouza/zoxide#430]
zsh cd allows you to use cd +n or cd -n to cd to the directory at that position in the dirstack.
man zshbuiltins excerpt:

> The third form of cd extracts an entry from the directory stack, and
> changes to that directory. An argument of the form '+n' identifies a
> stack entry by counting from the left of the list shown by the dirs com‐
> mand, starting with zero. An argument of the form '-n' counts from the
> right. If the PUSHD_MINUS option is set, the meanings of '+' and '-' in
> this context are swapped. If the POSIX_CD option is set, this form of
> cd is not recognised and will be interpreted as the first form.

the zoxide zsh init template does not recognize this and tries to match the literal name -2 or +3 or whatever as an actual directory name.

[PR 429](https://github.com/ajeetdsouza/zoxide/pull/429) fixes this

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/pull/429
