### ISSUE TITLE
Double forward slashes when used with Bash tab completions

### ISSUE THREAD

**Issue by hwittenborn** [ajeetdsouza/zoxide#434]
Whenever I'm using the Bash completions to fill in a folder name in my current directory, I'm getting double backslashes:

```
hunter@hwittenborn-desktop:~$ cd D
Desktop//   Documents// Downloads// 
hunter@hwittenborn-desktop:~$ cd D
```

I haven't tested this on any other shells, so I'm not sure if they're affected.

I'm on Ubuntu 22.04, and am using zoxide 0.8.2. I'm initializing zoxide like this:

```sh
export _ZO_ECHO=1
eval "$(zoxide init bash --cmd cd)"
```

**Comment by reallybigballsozoz** [comment]
The offending line is 

`compgen -A directory -S / -- "${COMP_WORDS[-1]}"`

The `-S` adds a suffix ... I checked an old init backup, does not even grep on compgen. but removing the suffix makes no difference so go ahead I would say and remove `-S /` ...
