### ISSUE TITLE
string match: Unknown option '--groups-only' on fish

### ISSUE THREAD

**Issue by Gorthog** [ajeetdsouza/zoxide#436]
![image](https://user-images.githubusercontent.com/15230040/183920747-9279e549-08e9-406a-87a6-66717ac46146.png)

also tried to downgrade to version 0.7.9
same error

**Comment by Gorthog** [comment]
closing this issue as this was a local issue with my installation. somehow i had two version of fish installed. the running instance was version 3.3.1. after i figured it out and removed it everything works fine

**Comment by kescobo** [comment]
I was just getting this error as well, and did not have 2 fish versions. However, I was also on v3.3.1, and it wasn't auto-updating. I'm 95% sure I'd added the ppa repo before (this is on pop!_os), but [redoing this](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) got me up to fish 3.5.1, and am no longer getting this zoxide error. Would never have occurred to me, thanks @Gorthog !

**Comment by XXiaoA** [comment]
I met the same problem in fish. I can be sure that my fish and zoxide is the lastest
