### ISSUE TITLE
zoxide not adding to DB unless explicitly commanded

### ISSUE THREAD

**Issue by ehawman** [ajeetdsouza/zoxide#437]
Using Windows 11 with Nushell.

Attempt:
``` nu
>z ~/Documents/Programming/Python
>z
>z Python
zoxide: no match found
```

Contents of the zoxide db directory: *Zip, zilch, nada.*

Troubleshooting:
``` nu
>zoxide add "C:\Users\ehawman\Documents\Programming\Python"
>z py
>echo $env.PWD
C:\Users\ehawman\Documents\Programming\Python
```

Contents of the zoxide db directory: `db.zo`

Ok let's attempt again:
``` nu
>z
>z Documents/Programming
>z
>z Programming
zoxide: no match found
```

So obviously zoxide knows where to put the db, and it has the proper read/write access to do so, but it isn't doing it under normal operation. I can't find anybody else with this problem.

Notably, on the same machine my WSL implementation with Fish is happy as a clam. On my Mac at home the same is true for both Nushell and Fish.

## Environment

In Nushell's `env-path`, I have the following:
``` nu
let-env _ZO_DATA_DIR = "C:\\Users\\ehawman\\.config\\zoxide"
zoxide init nushell --hook prompt | save ~/.config/nu/zoxide.nu
```

In `config-path`:
``` nu
## Zoxide
source ~/.config/nu/zoxide.nu
```

Thanks for the great tool and thanks for your time :)

**Comment by ehawman** [comment]
Solved it! I was initializing Zoxide before Oh-My-Posh. Zoxide captures the existing prompt, which meant it was capturing the default. When OMP initialized, it broke this connection.

I would add a quick blurb to the readme specifying that any prompt changes need to be initialized before Zoxide.

**Comment by ajeetdsouza** [comment]
Hey @ehawman, I'm glad you were able to fix your issue! The README does mention to add it to the end of your configuration file for exactly this reason, although I realize that it's not a very clear instruction. However, now that the Nushell team has added hooks, I'm hoping that future releases won't have this problem.

**Comment by ehawman** [comment]
@ajeetdsouza oh wow I see that now. In hindsight it makes sense, but "put this text at the bottom of X file" is so stupendously generic that I don't blame past me for reading it simply as "put this text in X file".

Are you referring to #416 and nushell/nushell#5951? Has there been progress on that front?

**Comment by ajeetdsouza** [comment]
Yeap. Unfortunately, I haven't seen any progress on that from the Nushell team. If I have a bit of free time this weekend I'll try and find a workaround for it.
