### ISSUE TITLE
oh-my-zsh zoxide not found

### ISSUE THREAD

**Issue by Nivethan-Ar** [ajeetdsouza/zoxide#443]
i installed zoxide on my ubuntu using this command
`curl -sS https://webinstall.dev/zoxide | bash
`
i added zoxide into my plugins
```
plugins=(
  git
  zoxide
)
```

Then i added this as last as in my .zshrc file
```
autoload -Uz compinit
compinit -i
eval "$(zoxide init zsh)"
```

rm ~/.zcompdump*; compinit

but i still get the following error oh-my-zsh zoxide not found, please install it from https://github.com/ajeetdsouza/zoxide

**UPDATE**
zoxide is working but i still  get the error message on the top!

**Comment by ajeetdsouza** [comment]
You just need the eval statement at the end of your .zshrc, the rest of the changes can be safely deleted.

**Comment by Nivethan-Ar** [comment]
@ajeetdsouza thanks forr the reply, its already at the end, so u mean i don't need the
```
autoload -Uz compinit
compinit -i
```
these lines?

**Comment by Nivethan-Ar** [comment]
i removed those above 2 lines and also removed zoxide from plugins array, and now that error is gone!

**Comment by ajeetdsouza** [comment]
Yeap, that's what I meant. Glad your issue is solved!
