### ISSUE TITLE
Allow customization of directory preview

### ISSUE THREAD

**Issue by melkster** [ajeetdsouza/zoxide#444]
I would like to use [`exa`](https://github.com/ogham/exa) instead of `ls` for the previewer. I also kinda preferred having the preview on the right instead of the bottom, which was recently changed. It would be sweet if the arguments passed to Fzf's `--preview` (and perhaps also `--preview-window`) could be customized by the user.

**Comment by melkster** [comment]
Thank you, that works!

**Comment by ajeetdsouza** [comment]
Closing as fixed. zoxide provides a bunch of default options for fzf, it's hard to provide customizability for every one of them.
