### ISSUE TITLE
Will support to import ZLocation database?

### ISSUE THREAD

**Issue by pplmx** [ajeetdsouza/zoxide#445]
As title. [ZLocation](https://github.com/vors/ZLocation)

![image](https://user-images.githubusercontent.com/26994103/186446568-8ad17111-a32a-4b7d-9118-4e78e4154ab1.png)

![image](https://user-images.githubusercontent.com/26994103/186446661-403ae77a-783a-4222-aa92-840ba5230d13.png)

**Comment by ajeetdsouza** [comment]
@pplmx could you try the following commands?

```powershell
$db = New-TemporaryFile
(Get-ZLocation).GetEnumerator() | ForEach-Object { Write-Output ($_.Name+'|'+$_.Value+'|0') } | Out-File $db
zoxide import --from z $db
```

**Comment by pplmx** [comment]
Hi, @ajeetdsouza 
Works fine. Thanks a lot. :)
