### ISSUE TITLE
zoxide adds 300+ milliseconds to the startup time of Powershell

### ISSUE THREAD

**Issue by zhengweidi** [ajeetdsouza/zoxide#447]
I used PSProfiler to measure the startup time of Powershell and the results are as follows
![image](https://user-images.githubusercontent.com/31889177/187178834-15251f7f-e2ec-4ffc-95d0-eec8c53cfcd6.png)
I don't know if this is as expected.

**Comment by ajeetdsouza** [comment]
Binary startup times on Windows are just higher on average, there's not much that I can reduce there. If you want to reduce startup time, you can always pipe the output of `zoxide init` to a file and source the file instead. The reason I haven't made that the default installation method is that users would have to remember to run this every time they update zoxide.
