### ISSUE TITLE
Man link to issue goes to 404

### ISSUE THREAD

**Issue by corneliusroemer** [ajeetdsouza/zoxide#448]
In the man pages, you have a link to the issue tracker - but that link ends in `.` so when clicking it you end up on a 404 page:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/25161793/187435645-286d6e56-0550-439d-b725-3c5d9f7fcf8f.png">

Just remove the period in the end to fix.

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/118a37f57666203fbd5cf02c6a9f923ba0ec99e8, thanks!
