### ISSUE TITLE
New preview window: ls illegal option

### ISSUE THREAD

**Issue by kaihowl** [ajeetdsouza/zoxide#454]
Mac OS 10.15.7
Using zsh.
Zoxide 0.8.3

With "z" tab completion, I see the following in the preview window:

![image](https://user-images.githubusercontent.com/474193/188835526-a603a873-432e-477b-a940-6b2e833c7f8e.png)

I understand that this might be too little information to go on. Please let me know, what I can provide to help analyze the issue.

**Comment by ajeetdsouza** [comment]
That's very strange, it works on macOS for me. What's the value of `which ls`?

**Comment by kaihowl** [comment]
```
$ which ls
> /bin/ls
```

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/pull/460.

**Comment by kaihowl** [comment]
@ajeetdsouza thank you for fixing this! What are your plans for a new release? :)

**Comment by aldanor** [comment]
Looking forward to the version bump as well as the `ls` error is pretty frustrating.
