### ISSUE TITLE
Better output than "no match found" when already in the only match

### ISSUE THREAD

**Issue by NorthIsUp** [ajeetdsouza/zoxide#458]
what happens:
```
$ z some-project
/home/src/some-project
$ z some-project
zoxide: no match found
```

it would be nice to have some output for the second command like `already in /home/src/some-project` or just the same as a regular match of `/home/src/some-project`

**Comment by Blonteractor** [comment]
Can I work on this?

**Comment by Blonteractor** [comment]
Maybe add something like this to `zoxide query`?

```rust
let excluded_dir = self.exclude.as_ref().map_or(PathBuf::new(), |path| PathBuf::from_str(path).unwrap());
let try_dir = stream.next();

let dir = match try_dir {
    Some(dir) => dir,
    None => {
     // Current Directory is passed as excluded in __zoxide_z
     if excluded_dir == env::current_dir()? {
     try_dir.context("already in the matched directory.")?
     } else {
           try_dir.context("no match found")?
       }
    }
};

```

**Comment by raguay** [comment]
I get this message everything I change directories. I'm on a MacBook Pro M1 system with Ventura using the fish shell. My cd command works fine, it just always prints this message.

**Comment by ajeetdsouza** [comment]
@raguay could you file a separate issue for that, along with your config file? While this is not intended behaviour, it's not related to the current issue.

**Comment by raguay** [comment]
I opened a new issue with my problem. Sorry, I thought this was the same issue.

**Comment by ljshwyykl** [comment]
same

**Comment by dagadbm** [comment]
this is really annoying for sure. I was just testing this out to move from z to zoxide and this behaviour sure is weird.
