### ISSUE TITLE
Feature request: Trigger Zsh's `chpwd` hook or echo its output if it does already

### ISSUE THREAD

**Issue by selfagency** [ajeetdsouza/zoxide#464]
Zsh supports a handful of [hooks](https://stephencharlesweiss.com/zsh-hooks) that allow you to execute custom code at the time the hook is triggered.

One of those hooks is `chpwd` which triggers when the current working directory is changed via the `cd` command.

Unfortunately, if you invoke Zoxide with `eval $(zoxide init zsh --cmd cd)` in your `.zshrc`, it doesn't appear to trigger the `chwpwd` hook when you `cd` to another directory.

If you could update your Zsh integration so that it triggers that hook, that would be rad. If it _is_ triggering that hook, then for some reason the output isn't being echoed back to the user.

For example, my hook runs [`onefetch`](https://github.com/o2sh/onefetch) and [`lsd`](https://github.com/Peltoche/lsd) every time I `cd` into a Git repo. But I never see the output of `onefetch` or `lsd`.

```zsh
autoload -Uz add-zsh-hook

function custom_chpwd() {
  if [[ -f ".nvmrc" ]]; then
    nvm use
  fi

  if [[ -d ".git" ]]; then
    onefetch
  fi

  lsd -a
}

add-zsh-hook chpwd custom_chpwd

eval "$(zoxide init zsh --cmd cd)"
```

**Comment by hacker-DOM** [comment]
I also do something similar to `lsd` and would love if `zoxide` triggers chpwd :-)

**Comment by hacker-DOM** [comment]
Fwiw, [zsh-z](https://github.com/agkozak/zsh-z) does work with `chpwd`, I just migrated

**Comment by ajeetdsouza** [comment]
Are you on the latest version of zoxide? The custom chpwd hook works seamlessly with zoxide for me.

**Comment by selfagency** [comment]
@ajeetdsouza zoxide v0.8.3

@hacker-DOM i would tend to think a compiled rust application would be faster at doing this work than a series of awk scripts
