### ISSUE TITLE
[Bug] If the first parameter of zoxide query is ., then all results should start with $PWD. 

### ISSUE THREAD

**Issue by JediMaster25** [ajeetdsouza/zoxide#465]
> If the first parameter of zoxide query is ., then all results should start with $PWD.

I've just tried this on version 0.8.3 like `zoxide query -l .` and I didn't get any directories for the current directory. I got one in the home folder and two in a directory on the same level as the current one, a sibling directory.

This worked fine though:
```
zoxide query -l | grep "${PWD}*"
```

I'll just make an alias for now.

**Comment by ajeetdsouza** [comment]
I think you're referring to this comment: https://github.com/ajeetdsouza/zoxide/issues/459#issuecomment-1250126601

This was a suggested feature, it isn't the current behaviour.
