### ISSUE TITLE
Match subfolders the same way as previously visited folders

### ISSUE THREAD

**Issue by JediMaster25** [ajeetdsouza/zoxide#472]
When I'm in a directory and I write a lowercase letter to go to an upper case folder it doesn't work. But if I've visited that folder before it works just fine. Could you make zoxide check the subfolders of the current directory the same way it does for its list of scored directories?

**Comment by ajeetdsouza** [comment]
This seems out of scope for zoxide -- if you want to `cd` into a subdirectory, I think tab completion works better than zoxide does.
