### ISSUE TITLE
The z foo<space><TAB> doesn't work in tmux window

### ISSUE THREAD

**Issue by ananth1996** [ajeetdsouza/zoxide#479]
On the login node of our cluster the `z foo<space><tab>` works as intended showing a interactive selection. However, once I tmux into a session and then perform the same command it end up not working. I am using a MacBook Pro to ssh into a Linux server. I think this might be a tmux issue as it is capturing the input differently. Are there any easy fixes?

**Comment by ajeetdsouza** [comment]
I tried with a local tmux session + zsh and it worked without any issue. Could you try a local tmux session and see if it really is a tmux issue?

**Comment by avysk** [comment]
Does not work for me in Windows Terminal with PowerShell either. Tab just completes stuff from the current directory.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/130091/211755039-94a6da1b-f1a6-4137-a396-4a20774ef91c.png">

**Comment by avysk** [comment]
SSH to FreeBSD 13.1 (bash, zoxide 0.6.0, fzf 0.35) produces the same result — Tab shows the list of the stuff in the current directory. By the way, `zi` works both on Windows and FreeBSD.

**Comment by avysk** [comment]
As far as I can see neither `zoxide init powershell` nor `zoxide init bash` has any code for completions.

**Comment by ajeetdsouza** [comment]
@avysk as mentioned in the README, `<space>+<tab>` completions only work on zoxide v0.8.0+, and on bash/zsh/fish shells.

@ananth1996 could you verify the zoxide version on your Linux server?

**Comment by avysk** [comment]
@ajeetdsouza Indeed. I stand corrected.

**Comment by avysk** [comment]
@ajeetdsouza FYI: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268885

**Comment by avysk** [comment]
FreeBSD port is updated to 0.9.0 and it works as exected.

**Comment by ajeetdsouza** [comment]
Awesome, closing this then.

**Comment by ananth1996** [comment]
Hi @ajeetdsouza. Sorry for the late reply. I can confirm that the error is similar to what @avysk sees. My `zoxide` version on the cluster is `zoxide v0.8.3`. Would it be fixed if I pull the newer version?

**Comment by ananth1996** [comment]
> Hi @ajeetdsouza. Sorry for the late reply. I can confirm that the error is similar to what @avysk sees. My `zoxide` version on the cluster is `zoxide v0.8.3`. Would it be fixed if I pull the newer version?

Ok I think I am stupid. It seems to work now.

**Comment by ananth1996** [comment]
> > Hi @ajeetdsouza. Sorry for the late reply. I can confirm that the error is similar to what @avysk sees. My `zoxide` version on the cluster is `zoxide v0.8.3`. Would it be fixed if I pull the newer version?
> 
> Ok I think I am stupid. It seems to work now.

Hmm. I take it back. It works sometime. So for example 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/21953717/219627124-67d4e1bb-f145-4cc6-a57e-386f6d62d6e3.png">

But then based on which directory it is in there is some issues
<img width="755" alt="image" src="https://user-images.githubusercontent.com/21953717/219627701-ba6dfcbe-4206-47a0-8b1d-f6768ecbe7da.png">

**Comment by ananth1996** [comment]
> > > Hi @ajeetdsouza. Sorry for the late reply. I can confirm that the error is similar to what @avysk sees. My `zoxide` version on the cluster is `zoxide v0.8.3`. Would it be fixed if I pull the newer version?
> > 
> > 
> > Ok I think I am stupid. It seems to work now.
> 
> Hmm. I take it back. It works sometime. So for example
> 
> <img alt="image" width="763" src="https://user-images.githubusercontent.com/21953717/219627124-67d4e1bb-f145-4cc6-a57e-386f6d62d6e3.png">
> 
> But then based on which directory it is in there is some issues <img alt="image" width="755" src="https://user-images.githubusercontent.com/21953717/219627701-ba6dfcbe-4206-47a0-8b1d-f6768ecbe7da.png">

Again. To further see how it is dependent on the directory I ask from. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/21953717/219628606-6d197dc1-e372-4068-abb8-6fc41ca84754.png">

**Comment by ajeetdsouza** [comment]
Yeah, that's a feature - it doesn't show the current directory as a recommendation.

**Comment by ananth1996** [comment]
Ok, then I can mark this as closed as well.
