### ISSUE TITLE
Debian package outdated

### ISSUE THREAD

**Issue by mhbkamaei** [ajeetdsouza/zoxide#481]
zoxide package in all repositories (even debian testing and debian sid) is too old (0.4.3-4)!
I was not sure if I should ask debian maintainers or open an issue here, so I did both.

**Comment by ajeetdsouza** [comment]
Hey @mhbkamaei,

I don't maintain the Debian package, so there's unfortunately not a lot I can do about that. I'd suggest using the official installer listed on the README, as it always points to the latest version:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

Alternatively, the [Releases](https://github.com/ajeetdsouza/zoxide/releases/tag/v0.8.3) page has DEB files that you can install manually.

**Comment by Susensio** [comment]
Hi @ajeetdsouza , who should we talk to for the debian package to be updated?

**Comment by ajeetdsouza** [comment]
The Debian page for zoxide has a section for its maintainers, you could perhaps try mailing them:

https://packages.debian.org/unstable/zoxide
