### ISSUE TITLE
Zoxide query: "query: " prefix in result hinders composability in shell commands

### ISSUE THREAD

**Issue by Emerentius** [ajeetdsouza/zoxide#49]
I request that `zoxide query` simply result the path without a `query: ` prefix.

That way you can use the result immediately as argument to other commands.

My primary interest is that I want to easily open VSCode on various codebases. Currently it's easiest if I run `z <keyword>; code .` in a new terminal and then close it again, but it would be easier if I could instead just do `code $(zq <keyword>)`. As this doesn't modify the current directory of the terminal, I could execute this from any of the terminals I already have open.

**Comment by ajeetdsouza** [comment]
I did consider this, but it comes with problems:

- `zoxide query` sometimes needs to print other things to `stdout`, such as in the case of invalid usage, or passing the `--help` flag. This could result in strange behaviour if you're using a naive `code $(zq <keywords>)` command.
- If there is any error while performing the query (eg. no match found), we print an error message to `stderr`, but nothing to `stdout`. Here, too, this may cause confusing behaviour.

Currently, the `"query: "` prefix allows us to keep the `z` function logic rather straightforward - it saves the output of `zoxide`, and if it starts with `"query: "`, it `cd`s into it.

However, this is a very valid usecase, and is one that I too would love to see `zoxide` fulfill - so do tell me if you have any ideas about how to solve this!

**Comment by Emerentius** [comment]
An alternative would be to offer a utility that would execute a given command with the results of a `zoxide query` interpolated in certain places, for example:  
`zoxide execute code {<keyword>...}` (alias: `ze`)

That gives you control over the entire command and you can skip execution if an error occurs. Things tend to get a bit complicated when you have multiple utilities with this behaviour (e.g. [rust-parallel](https://gitlab.redox-os.org/redox-os/parallel), [fd with it's `--exec` option](https://github.com/sharkdp/fd)) that call each other as you now have to escape the special syntax for each, possibly multiple times. I can't estimate how much of a problem that would be as I don't a usecase in mind that would require that.

Personally, I'd have no issue with the command behaving a bit optimistically with the occasional confusion. Shell environments don't tend to have good fallback behaviour in general, so you're keeping yourself to a much higher standard than most, especially in the case where someone passes `--help` but tries to use the output as a path. I certainly don't intend to use this in combination with dangerous commands like `rm -rf`.

I can't say much about the complexity of the implementation as I'm not familiar with the internals.

**Comment by ajeetdsouza** [comment]
You make a fair point, I will work on this.

**Comment by ajeetdsouza** [comment]
I've added this in https://github.com/ajeetdsouza/zoxide/commit/d3e49bde66db260ff84643db42a31ae053baf3a4, it will be released with v0.3.1. Thanks!

**Comment by Emerentius** [comment]
Thanks a lot!

As an aside, I'd wanted to have a way to navigate different paths with less typing for a long time before you posted about this tool on reddit. I just want to thank you for that.  
Anything I would have built wouldn't have been nearly as useful as this. I realize it's inspired by other projects, but I couldn't have trusted a large shell codebase and not having to install lua makes setup easier as well. That's useful cause you can bet I'm going to install this on any PC and server of mine.

**Comment by ajeetdsouza** [comment]
Thank you, that means a lot!
