### ISSUE TITLE
nushell and save

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#490]
@ajeetdsouza In case you haven't heard, with nushell version 0.72.0, which we just released, the `save` command is safer now. It will not overwrite existing files unless the `--force`/`-f` flag is passed. I've been updating my `zoxide` configurations by adding `-f`. Just thought I'd pass this along.

**Comment by ajeetdsouza** [comment]
I'm on Nushell v0.72.1, and my `save` command throws an error if I pass `-f`. Is this an upcoming feature?

**Comment by fdncred** [comment]
yes. https://github.com/nushell/nushell/pull/7262

**Comment by ajeetdsouza** [comment]
Done. Thanks for the heads up!
