### ISSUE TITLE
nushell && and ||

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#494]
@ajeetdsouza On our next release, `boolean and` has changed from `&&` to `and` and `boolean or` has changed from `||` to `or`. We're considering using those operators the way bash does. However, we haven't made that leap yet.

I just had to change the zoxide.nu script that is generated and wanted to pass this information on. Our next release is scheduled for Dec 20th.

**Comment by ajeetdsouza** [comment]
Fixed, thanks!
