### ISSUE TITLE
How to remove the unwanted paths from zi

### ISSUE THREAD

**Issue by c02y** [ajeetdsouza/zoxide#499]
For instance, I use `zi abc` to list and choose the path I needed, but there are a few other paths in the list that are not frequently accessed, I need to remove those paths from the db so I can jump to `abc` directly without interactively choosing one.

But `zoxide remove -i abc` will list hundreds of paths, and it is difficult to filter the paths I needed.

Is there anything can I do to remove the paths from `zi abc` without listing all the paths in db?

**Comment by mattiasbonte** [comment]
I found the least time consuming endeavor to be, removing the existing database and start from scratch..

For example on Mac..`~/Library/Application Support/zoxide` the database file can be found here, but I don't recommend cleaning it manually.

Cheers.

**Comment by ajeetdsouza** [comment]
@c02y there is a way to remove directories via a script (`zoxide remove`) as well as interactively (`zoxide remove -i`). Both let you delete multiple entries in one go.

I didn't fully understand -- how do you think this process could be made faster? As @mattiasbonte said, if you're looking to purge the whole database, you may as well delete the database file itself and start over.

**Comment by c02y** [comment]
I only need `zoxide remove -i` (or maybe with extra flag) to list all and only paths in `zi`, since `zoxide remove -i` will list all the paths in db including the keyword in the middle of the path unlike `zi abc` only lists paths when abc is in the last part of the paths.

**Comment by c02y** [comment]
a fish shell function:
```
function zd
    set path (zoxide query -i -- $argv)
    test $path; and zoxide remove $path
end
```
