### ISSUE TITLE
get the path as the argument for any command

### ISSUE THREAD

**Issue by zhuzhzh** [ajeetdsouza/zoxide#500]
I want to use the path for `cp`/`rm`/`awk`/...

for ex:
```
cp $(zoxide query -i)<tab>
```
then it will list the path as `zi`,  I will input the key word and select the path, it becomes

```
cp /some/path
```

current, it will break the line. for ex.
```
/hcp /home/harriszh/.config/nvim/init.lua
```

I think it will extent zoxide's usage for smart jump, but path selection for any command.

**Comment by zhuzhzh** [comment]
I totally don't know zle. but I emulate fzf's key-binding.

```zsh
  zoxide-history-widget-accept() {
    local selected
    selected=( $(zoxide query --list |fzf) )
    local ret=$?
    echo -n "$selected"
    return $ret
  }
  zle    -N    zoxide-history-widget-accept
  bindkey '^[o' zoxide-history-widget-accept
```

It doesn't work.

**Comment by ajeetdsouza** [comment]
@zhuzhzh I'm no zsh expert, but this is how I fixed it:

```sh
zoxide-history-widget-accept() {
  res="$(zoxide query -i)" # interactive zoxide query
  LBUFFER+="${(q)res}" # push the result to the input buffer
  zle reset-prompt # redraw the prompt
}
```

**Comment by zhuzhzh** [comment]
Thanks a lot!  It works .
