### ISSUE TITLE
Installation failed forarchitecture: x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by dhruvinsh** [ajeetdsouza/zoxide#502]
On Ubuntu 20.04 server I am trying to install with below command, but it is failing
```
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

Failed message:
``` 
Detected architecture: x86_64-unknown-linux-musl
Error: zoxide has not yet been packaged for your architecture (x86_64-unknown-linux-musl), please file an issue at https://github.com/ajeetdsouza/zoxide/issues
```

**Comment by dhruvinsh** [comment]
Found an issue,
in `download_zoxide` the release_url is set to api URL: ``

but the reponse that I get is,
```json
{
    "message": "API rate limit exceeded for 72.142.91.80. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

That is what causing the issue.

**Comment by ajeetdsouza** [comment]
Any idea why GitHub is rate limiting your requests? According to the link in that message, they provide 60 requests per hour, which means that even if you exceeded it by accident, it should have worked an hour later.

**Comment by dhruvinsh** [comment]
I guess in corporate network lot if requests are being made to github that is why I always run in to this issue.

**Comment by ajeetdsouza** [comment]
I don't know if there's much I can do about GitHub rate limiting your requests. What do you typically do when you run into this issue?

Some suggestions:

- Use your distro's package manager to install zoxide.
- If you're on Debian/Ubuntu, the distro's version is likely very outdated - use the DEB installer from the [Releases](https://github.com/ajeetdsouza/zoxide/releases) page.
- Install via Cargo: `cargo install zoxide --locked`
- Download the tarball from the [Releases](https://github.com/ajeetdsouza/zoxide/releases) page, and copy the binary to `~/.local/bin` (this is what the installer does anyway).

**Comment by dhruvinsh** [comment]
That is true that for rate limit you can no do anything.

But yes one minor change is good in the installation script. Where the installation says certain binary not found, instead it could say actual error which would be hitting a rate limit and can not able to download the binary file.

**Comment by ajeetdsouza** [comment]
Done: https://github.com/ajeetdsouza/zoxide/commit/2555870c3174894e5bb287f0bf1506bbf6d24ddc

**Comment by ZzEeKkAa** [comment]
Actually there is a way to bypass it. User must be logged in to use personal rate limit versus general. There are different methods - one to use `gh` (github client) or another - set authorization token to curl https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28 . Could you reopen the issue to add option to provide authorization token or use gh client to access api?
