### ISSUE TITLE
Tag New Version for 0.73 nushell compatibility

### ISSUE THREAD

**Issue by jeremiahpslewis** [ajeetdsouza/zoxide#505]
Hey! Thanks for the awesome package, love using it. Would it be possible to tag a new version off of the `main` branch so that the homebrew recipe can be bumped to support nushell 0.73?

**Comment by vedkothavade** [comment]
@jeremiahpslewis until this happens, do you know if there is a way to have brew build the main branch, or is installing with `cargo --git` my best bet?

**Comment by jeremiahpslewis** [comment]
AFAIK you can only have hombrew (re-)build existing formulas from source, but without a version bump, there's no formula for the new version so your `cargo` approach sounds like a good bet.

**Comment by vedkothavade** [comment]
> AFAIK you can only have hombrew (re-)build existing formulas from source, but without a version bump, there's no formula for the new version so your `cargo` approach sounds like a good bet.

Thanks!

**Comment by ajeetdsouza** [comment]
Just released. Sorry about the delay!

**Comment by jeremiahpslewis** [comment]
Thanks!
