### ISSUE TITLE
Install via Brew

### ISSUE THREAD

**Issue by quintrino** [ajeetdsouza/zoxide#51]
Hi, 

It would be awesome to be able to install via homebrew
https://github.com/ajeetdsouza/zoxide

Project looks really good!

**Comment by ellsclytn** [comment]
Looks like the Homebrew formula has already been made https://github.com/ajeetdsouza/homebrew-zoxide/pull/1

**Comment by quintrino** [comment]
@ellsclytn I haven't gone through the process of getting something added into the core homebrew list rather than via a tap. Is it difficult to process?

**Comment by ellsclytn** [comment]
Wouldn't have a clue I'm afraid. I'd suggest the Brew maintainers themselves for answering that question.

**Comment by cole-h** [comment]
See https://github.com/ajeetdsouza/zoxide/issues/18#issuecomment-598181634 and https://github.com/Homebrew/homebrew-core/pull/51674#issuecomment-598565860.

**Comment by ajeetdsouza** [comment]
@cole-h @ellsclytn thank you for resolving the issue!

@quintrino, I don't know exactly what the core maintainers would define as notable, but I'll be sure to keep trying.
