### ISSUE TITLE
nushell windows error

### ISSUE THREAD

**Issue by yashamon** [ajeetdsouza/zoxide#511]
nu is version 7.3 and zoxide ver 9.0 both installed via scoop. 
Platform: Win11

I am getting the following error:

```
× Extra positional argument.
    ╭─[.zoxide.nu:12:1]
 12 │   let-env config = ($env.config | default {} hooks)
 13 │   let-env config = ($env.config | update hooks ($env.config.hooks | default {} env_change))
    ·                                          ──┬──
    ·                                            ╰── extra positional argument
 14 │   let-env config = ($env.config | update hooks.env_change ($env.config.hooks.env_change | default [] PWD))

```

**Comment by ajeetdsouza** [comment]
I'm not able to reproduce this and your error isn't rendering properly on GitHub. Could you upload a screenshot of the error instead?

**Comment by yashamon** [comment]
Weirdly if manually source .zoxide i get no error.

**Comment by yashamon** [comment]
I figured it out. I had a custom def for update function. Although, this looks like nu bug, there should be a warning about update function existing.
