### ISSUE TITLE
[macOS] zoxide creates "$HOME" folder in every folder I cd into

### ISSUE THREAD

**Issue by jan-schaeffer** [ajeetdsouza/zoxide#512]
I have zoxide installed from brew. Every time I cd into a folder, zoxide creates a folder named "$HOME" in that folder. What could be the reason for this?

**Comment by ajeetdsouza** [comment]
What shell are you using? What does `echo "$HOME"` output?

**Comment by jan-schaeffer** [comment]
I'm using zsh. echo `"$HOME"` returns `/Users/janschaeffer`

**Comment by ajeetdsouza** [comment]
Can you share your shell configuration? Does the problem go away once you remove zoxide?

**Comment by jan-schaeffer** [comment]
So the problem has disappeared somehow... But yes, when deinstalling zoxide or when I remove the alias to cd, the problem disappeared.

**Comment by ajeetdsouza** [comment]
If the problem has gone, I'll close the issue. Feel free to reopen if it happens again.
