### ISSUE TITLE
the operators `||` and `&&` don't work on the newest vr. of null shell (0.74.0)

### ISSUE THREAD

**Issue by beari22** [ajeetdsouza/zoxide#518]
this breaks the file `~/.zoxide.nu` on line 26,
just replace them `or` and `and`

**Comment by ajeetdsouza** [comment]
What version of zoxide are you on? The latest is v0.9.0 and should work with this.

**Comment by beari22** [comment]
oh i was on an older vr. (0.8.3), after updating its fixed, thx
