### ISSUE TITLE
[Fish Shell] Could not deserialize old database error

### ISSUE THREAD

**Issue by thomasharmon808** [ajeetdsouza/zoxide#52]
I'm using Fish for my shell and all of a sudden I started getting this error:

```
Error: could not deserialize old database

Caused by:
    io error: failed to fill whole buffer
```

Any idea why this might've started happening? I really loved zoxide btw so great work! Hopefully I can fix this because it's been getting annoying

**Comment by ajeetdsouza** [comment]
v0.2 and v0.3 databases are incompatible. There is a migration script to automatically convert your database to the new format, but it seems like it is failing on your system. I will try to investigate, but for a quickfix, you can try removing your old database file:

```shell
rm ~/.zo
```

Sorry about that!

**Comment by thomasharmon808** [comment]
Thank you! That worked. I'm assuming I must've updated it without realizing, so I was surprised but the sudden failure. I'm assuming a lot of other people might end up having this issue, so you might want to add this as a note to your readme.
