### ISSUE TITLE
`__zoxide_z` not recognized

### ISSUE THREAD

**Issue by ThePython10110** [ajeetdsouza/zoxide#520]
I installed Zoxide via chocolatey on Windows 10, and whenever I run `z <folder>` (in PowerShell 7), I get the following error:
```
z: The term '__zoxide_z' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
The same thing happens with `zi`. I did edit my `$profile` file to match the instructions.

**Comment by ajeetdsouza** [comment]
Can you share the entire $profile file?

**Comment by ThePython10110** [comment]
Turns out I only needed the v0.8.0+ half of this. After deleting the "older versions" part, it works fine now. It sure looked like I was supposed to copy the whole thing in there... Maybe change the instructions to make it more clear.

```
# For zoxide v0.8.0+
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd' }
    (zoxide init --hook $hook powershell | Out-String)
})

# For older versions of zoxide
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd' }
    (zoxide init --hook $hook powershell) -join "`n"
})
```
