### ISSUE TITLE
Prefer "leaf" directories even if one of the parents match

### ISSUE THREAD

**Issue by tgross35** [ajeetdsouza/zoxide#521]
Hello,

I'm not 100% sure how exactly to quantify this, but for example: with a tree like this:

```
~/myproj/          # whenever in this dir, almost immediately cd to a subdirectory
  myproj-source/   # visited 80% of the time when in ~/myproj
  myproj-docs/     # visited 15% of the time
  myproj-misc/     # visited 5% of the time
```

entering `z myproj` from elsewhere seems to always take you to the top level `~/myproj`. Instead, I would expect it to take you to the most visited leaf that that matches, maybe if it is visited at least 50% of the time that the parent directory is visited. I believe that [jump](https://github.com/gsamokovarov/jump) does this

My real use case has these scores:

```
  56 C:\Users\me\Documents\code\proj1-name
  36 C:\Users\me\Documents\code\proj1-name\proj1-name-src-12345
```

And typing `z proj1` always brings me to the parent directory instead of the inner directory, even though it seems like I directly navigate to the `src` directory every time I'm there (and would prefer it to just jump there in the first place)

**Comment by ajeetdsouza** [comment]
This is the kind of problem where solving for one use case breaks another. If jump favors leaf directories, I'm sure a lot of people will run into problems where they wanted to go to the parent directory.

AFAIK, all z-clones have the same problem. The way zoxide attempts to fix this is:

- Interactive completions via `<space>+<tab>`, so you can choose the directory when you know that the result is ambiguous
- There are 3 subcommands that allow you to change the scores of entries in the database: add, remove, and edit

In your case though, I would simply change the query to something like `z pro 123`.
