### ISSUE TITLE
v0.9.0: Space TAB results in "unknown option: --scheme=path" error

### ISSUE THREAD

**Issue by timkgh** [ajeetdsouza/zoxide#522]
zoxide v0.9.0, zsh 5.8.1 on Ubuntu 22.04: hitting `<space><TAB>` now results in an error `unknown option: --scheme=path`

Edit: The problem is `fzf 0.29 (devel)` which is what Ubuntu ships with and doesn't have a `--scheme` option.

**Comment by brajnacs** [comment]
I just installed it and found the same problem. fzf version is 0.20.0 though.

**Comment by ajeetdsouza** [comment]
Hey, zoxide now requires fzf 0.33.0+. The new path-based scoring scheme is very useful for programs like zoxide.
