### ISSUE TITLE
Hiding zoxide: no match found

### ISSUE THREAD

**Issue by ProfessorManhattan** [ajeetdsouza/zoxide#526]
I set up zoxide and aliased cd to it with the built in alias feature. It works as expected except when opening the terminal and when navigating to uncharted directories, I get a message that says:

```
zoxide: no match found
```

Is there a way I can suppress this?

**Comment by ProfessorManhattan** [comment]
Yeah... Since I'm using it as a replacement for cd, if the directory is not
in zoxides database, it currently shows a message that looks like an error.
I'm wondering if there's a way I can hide the message in this case

**Comment by ajeetdsouza** [comment]
Based on your shell, you can write a custom function for this. On zsh, it might look something like this:

```sh
eval "$(zoxide init zsh --no-cmd)" # use --no-cmd so that `z` is not created
function z() { __zoxide_z "$@" 2> /dev/null } # redirect errors to /dev/null
```

**Comment by ProfessorManhattan** [comment]
Hey @ajeetdsouza -- thanks for this tip. This works kind of but I think it will hide errors that occur after the shell is already loaded. My goal is to only hide the error message when the terminal first loads --- something is trying to run `cd` after `~/.zshrc` loads and I ensured that the `zoxide init zsh` is the last thing that loads

**Comment by megalithic** [comment]
Came here wondering the same thing; when using zoxide as part of a script to get the resolved directory path for a given partial string; if it doesn't find one from zoxide's history, then have it return "" perhaps? (naive approach i know)

**Comment by ajeetdsouza** [comment]
Could you create a fresh issue and describe the exact problem? I'm not sure what you mean by hiding errors after the shell is loaded.
