### ISSUE TITLE
Jobs indicator shows up even when there are no background jobs

### ISSUE THREAD

**Issue by imgnue** [ajeetdsouza/zoxide#527]
I'm using the [starship](https://github.com/starship/starship) prompt and this happens when changing directory. The indicator (✦) disappears when you issue other commands or press enter.

https://user-images.githubusercontent.com/12945959/214809326-d464e6b0-44ba-4ff0-ae8f-fe665d176326.mp4

**Comment by ajeetdsouza** [comment]
This looks more like a Starship bug than a zoxide one. zoxide doesn't start any background processes, it just uses the chpwd hook provided by zsh. Please report it on the Starship issue tracker and tag this issue.

**Comment by imgnue** [comment]
Will post it there, thanks!

**Comment by ajeetdsouza** [comment]
Awesome, closing this issue then.

**Comment by ajeetdsouza** [comment]
Tracking this here, too: https://github.com/starship/starship/issues/5159

This is caused by a bug in Bash, but we've found a workaround and it should be fixed soon.
