### ISSUE TITLE
Oh-my-zsh init fail

### ISSUE THREAD

**Issue by jinleileiking** [ajeetdsouza/zoxide#531]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/93968/217715256-2f68859d-461d-449c-b4ca-822c0a34b875.png">
<img width="984" alt="image" src="https://user-images.githubusercontent.com/93968/217715278-66c296d9-9509-4954-a6d7-9c3359c8c3d1.png">

**Comment by ajeetdsouza** [comment]
What version of zoxide/zsh are you on?

**Comment by jinleileiking** [comment]
I add ohmyzsh z plugin ( which is missleading) 

This plugin cause this problem.

Then I change to zoxide plugin.

https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zoxide


seem failed too.

If I use ohmyzsh. Should I use offical zoxide plugin  ?

**Comment by jinleileiking** [comment]
@ajeetdsouza

**Comment by ajeetdsouza** [comment]
It's recommended to use eval.
