### ISSUE TITLE
zoxide can't go to directory named `py_dex`

### ISSUE THREAD

**Issue by rew1nter** [ajeetdsouza/zoxide#533]
![report to github](https://user-images.githubusercontent.com/64508791/219116391-50ebb4e9-9e7d-4cc0-980b-dfedfdf14a74.png)

As you can see it works fine when you wanna switch to `js` by typing `z js`. For some unknown reason it never memorizes the `py_dex` directory and always fails to cd with `py` :/

**Comment by ajeetdsouza** [comment]
Have you excluded `py_dex` via the `$_ZO_EXCLUDE_DIRS` environment variable? I don't see any reason why zoxide would ignore a particular directory and work for others.

**Comment by rew1nter** [comment]
No I haven't added any env vars like that. Just went with the default installation.

**Comment by ajeetdsouza** [comment]
Is py_dex a symlink or a regular directory? The `file` command should give you the information.

**Comment by rew1nter** [comment]
`file` command:
![image](https://user-images.githubusercontent.com/64508791/222694995-c1f76f3a-cc58-4bef-8dd7-da4c702796f8.png)

`zoxide add` didn't work:
![image](https://user-images.githubusercontent.com/64508791/222695197-8f8b4b10-c473-4af7-bf1a-9c4cf1894ebf.png)

`zoxide query --all -ls |grep py_dex`:
Shows the full path to `py_dex`

**Comment by ajeetdsouza** [comment]
To clarify - are you saying it shows up under `zoxide query --all -ls` but not under `zoxide query -ls`?

If this is the case, this means Rust is somehow returning false for `std::fs::metadata("./py_dex").is_dir()`.

**Comment by rew1nter** [comment]
> To clarify - are you saying it shows up under zoxide query --all -ls but not under zoxide query -ls?

No.
`zoxide query --all -ls` and `zoxide query -ls` both shows the file `py_dex`. Yet you can't cd with `py` .

**Comment by ajeetdsouza** [comment]
This is quite bizarre. zoxide should handle both directories the same way - I tried creating a directory called `py_dex` and it's working fine for me.

- Does it show up with `zoxide query --all py`?
- Does it show up with `zoxide query py`?
- Can you think of anything unusual about this directory which would cause the behaviour to be different?
