### ISSUE TITLE
No option to import from fasd

### ISSUE THREAD

**Issue by tangestani** [ajeetdsouza/zoxide#534]
I just installed zoxide -- migrating from fasd -- and I wanted to import my fasd db to zoxide...

Even though the README mentions that this option should be possible, the latest version of zoxide (0.9.0) claims it's not possible.

```sh
> zoxide import --from fasd

error: 'fasd' isn't a valid value for '--from <FROM>'
  [possible values: autojump, z]

For more information try '--help'
```

Am I missing something here?

**Comment by hasssan** [comment]
I was facing the same issue, tried with `--from=z` for fasd and it works

```sh
zoxide import --from=z ~/.fasd
```

**Comment by ajeetdsouza** [comment]
fasd uses the same format as z, which is why you're supposed to use the `--from=z` command. It is listed in the README, but I'll add an alias for `--from=fasd` in future releases.
