### ISSUE TITLE
List files automatically when jumping to a directory

### ISSUE THREAD

**Issue by XhstormR** [ajeetdsouza/zoxide#536]
Whenever I use the z command to jump to a directory, I need to execute the `ls` command to view the files in the current directory. 

Can you add an environment variable setting so that zoxide can automatically list the files in the current directory after jumping?
Or we can customize the callback command?

**Comment by ajeetdsouza** [comment]
Which shell are you using?

**Comment by ajeetdsouza** [comment]
The `z` function is actually just an alias to `__zoxide_z`. The reason it is implemented this way is so that users can add custom functionality.

You can use something like this:

```fish
function z
  __zoxide_z $argv && ls
end
```
