### ISSUE TITLE
De-noise scores column: remove all the decimals

### ISSUE THREAD

**Issue by eugenesvk** [ajeetdsouza/zoxide#540]
I have the following output of `zoxide query -ls` 
```
4100.0
2280.0
1390.0
 772.0
  ...
  80.0
  ...
   9.0
  ... many identical tiny numbers
   1.0
   1.0
   1.0
  ...
   0.8
   0.8
  ...
   0.8
  ... a gazillion of even smaller essentially identical 0 numbers
```

To me the post-decimal numbers are just useless noise, there is no difference between a hundred of folders with `0.2`, `0.1`, etc. vs `0`, so there is no reason to be this precise.
So I'd prefer to completely drop all the decimals and to denoise the output to something like this:
```
4100
...
   1
   0
...
```
Ideally this should be the default, but and extra flag is also fine

**Comment by ajeetdsouza** [comment]
The decimals were added so that all the similarly ranked directories are sorted correctly. This ordering significantly improves the search experience on fzf, which is why there are no plans to take it out.
