### ISSUE TITLE
zoxide won't remember paths in nushell

### ISSUE THREAD

**Issue by kyoobey** [ajeetdsouza/zoxide#546]
![screenshot_2023-03-26-214033](https://user-images.githubusercontent.com/61683653/227788945-8788ec38-5a08-4961-af30-4b20acee8e84.png)

**Comment by maxim-uvarov** [comment]
+1

**Comment by kaifastromai** [comment]
I can confirm I am encountering this issue as well, with the same  z 0.9.0

**Comment by ajeetdsouza** [comment]
Just released v0.9.1. Could you see if this solves your issue?

**Comment by kyoobey** [comment]
just updating did not solve the issue, however i made some changes to the init script which fixed it
```
if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
  let-env __zoxide_hooked = true
  let-env config = ($env | default {} config).config
  let-env config = ($env.config | default {} hooks)
  let-env config = ($env.config | update hooks ($env.config.hooks | default {} env_change))
  let-env config = ($env.config | update hooks.env_change ($env.config.hooks.env_change | default [] PWD))
  let-env config = ($env.config | update hooks.env_change.PWD ($env.config.hooks.env_change.PWD | append {|_, dir|
    zoxide add -- $dir
  }))
}
```
```
if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
  let-env config = ($env.config | upsert hooks {
    env_change: { PWD: [
      {|_, dir|
        zoxide add -- $dir
      }
    ]}
  })
}
```

**Comment by kyoobey** [comment]
turns out i was being dumb and didn't follow the installation instructions properly which clearly mentions that `source ~/.zoxide.nu` has to be in `config.nu` and **not** in `env.nu`

**Comment by maxim-uvarov** [comment]
> turns out i was being dumb and didn't follow the installation instructions properly which clearly mentions that source ~/.zoxide.nu has to be in config.nu and not in env.nu

I set up zoxide according to the instructions from the very beginning (see screenshot below), but it won't work for me. I guess there might be a bug in Nushell since a line's order sometimes matters, as discussed here: https://discord.com/channels/601130461678272522/1097889380087124100


<img width="568" alt="image" src="https://user-images.githubusercontent.com/4896754/236735354-f3ba2149-9231-40d6-9124-524290dd4c6e.png">

**Comment by ajeetdsouza** [comment]
Does it work when it is the only thing in your config? Does it work when you source it manually?

**Comment by maxim-uvarov** [comment]
> Does it work when it is the only thing in your config? Does it work when you source it manually?

Yes, changing the order of lines makes zoxide work. Thanks. I am investigating now what breaks it.
