### ISSUE TITLE
zoxide: unsupported version (got 0, supports 3)

### ISSUE THREAD

**Issue by iEverX** [ajeetdsouza/zoxide#550]
any zoxide command report error
`zoxide: unsupported version (got 0, supports 3)`

version: 0.9.0
os: 6.2.8-arch1-1, x86_64

**Comment by iEverX** [comment]
`rm ~/.local/share/zoxide/db.zo` solve the probolem.
Mabye #498 is not incompatible with old version

**Comment by pansila** [comment]
The database will be corrupted if computer got shutdown suddenly due to like power loss
