### ISSUE TITLE
disabling cd on fish broke zoxide

### ISSUE THREAD

**Issue by stephane-archer** [ajeetdsouza/zoxide#553]
Hi, I wanted to "disable cd" for interactive use to change my muscle memory.
type this in your shell and it works!
```
function cd
    if status is-interactive
          echo "Use z"
          return 1
	end
	builtin cd $argv
end
```
cd is disabled and z works!
let's `funcsave cd` then start a new terminal
cd is disabled but z says now "Use z"...

PS: in my config file I have the following:
```
if status --is-interactive
        zoxide init fish | source
end
```

System info:
```
fish, version 3.6.1
zoxide v0.9.0
Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
screen-256color
```

**Comment by stephane-archer** [comment]
I found a workaround by defining the following `function __zoxide_cd_internal; builtin cd $argv; end`
but this is an issue because `zoxide init fish` output is not right.
please see this detail answer: https://github.com/fish-shell/fish-shell/issues/9733#issuecomment-1505640125

**Comment by ajeetdsouza** [comment]
zoxide uses the fish cd function under the hood, so the solution is simply to change the cd function _after_ calling zoxide:

```fish
if status --is-interactive
        zoxide init fish | source
end

function cd
    if status is-interactive
        echo "Use z"
        return 1
    end
    builtin cd $argv
end
```

**Comment by sascha-wi** [comment]
> zoxide uses the fish cd function under the hood, so the solution is simply to change the cd function _after_ calling zoxide:
> 
> ```fish
> if status --is-interactive
>         zoxide init fish | source
> end
> 
> function cd
>     if status is-interactive
>         echo "Use z"
>         return 1
>     end
>     builtin cd $argv
> end
> ```

Doesn't work for me, if I use z instead it still says "Use z".

**Comment by ajeetdsouza** [comment]
@sascha-wi could you create a separate issue for this?
