### ISSUE TITLE
Can we record both absolute and relative paths in the db.zo?

### ISSUE THREAD

**Issue by dclong** [ajeetdsouza/zoxide#555]
And make absolute paths take precedences when matching users' navigation paths. This will make it much easier to migrate db.zo from system to another.

There's one situation where zoxide isn't really usable. I personally have to work in cloud IDEs. Each instance (called a workspace) of a cloud IDE have different prefixes. Each workspace is for a small task and might get discard very soon. This means even I have same folder structures, but the path prefixes are constantly changing. Record both absolute and relative paths into db.zo would make zoxide usable in this situation.

**Comment by ajeetdsouza** [comment]
This is a fairly niche feature, I'd say this is out of scope for zoxide for now.
