### ISSUE TITLE
Paths with spaces break completion in fish

### ISSUE THREAD

**Issue by kbmad** [ajeetdsouza/zoxide#560]
```
$ uname -sr
Darwin 22.4.0

$ fish --version
fish, version 3.6.1

$ zoxide --version
zoxide v0.9.0
```

To reproduce the issue:

```
$ fish --no-config
$ zoxide init fish | source
$ mkdir -p 'this/path/contains space/chars'
$ z this/path/contains\ space/<tab>
```

The final `tab` should autocomplete "chars" but returns no completions.

Try again with preceding quote:

```
$ z 'this/path/contains space/<tab>
```

Same result, no completions.

This only happens with space chars, paths with other special chars work as expected, and it only affects fish – both zsh and bash work as expected.

**Comment by ajeetdsouza** [comment]
Fixed, thanks!
