### ISSUE TITLE
Used together with starship can fail to auto save

### ISSUE THREAD

**Issue by gzmorell** [ajeetdsouza/zoxide#570]
When used together starship.rs, at least under windows, zoxide init must be called after starship init, if not
zoxide do not add new dirs automatically.
It seems that zoxide hook depends on prompt which starship changes.

**Comment by ajeetdsouza** [comment]
The README does mention this:

> Add this to the **end** of your config file (usually `~/.zshrc`):

If there is any way you think this could be clearer, I'd love to know - this is a very common issue people have with zoxide.

**Comment by gzmorell** [comment]
I'm not a native english speaker, but it seems more an indication than an advice to avoid problems.
Something like "To avoid conflicts with other programs add this to the end ..."?
