### ISSUE TITLE
Sorting query by score

### ISSUE THREAD

**Issue by joshmedeski** [ajeetdsouza/zoxide#574]
For https://github.com/joshmedeski/t-smart-tmux-session-manager/issues/25

I'd like to recreate `zoxide query -i` ability to sort fzf results by the sort value.

How is this achieved? I basically have my own fzf function that chooses from tmux sessions or zoxide results to manage tmux sessions.

**Comment by ajeetdsouza** [comment]
Ironically enough, you do that using `zoxide query -ls | fzf --no-sort` 😄 

In case you'd like to see the rest of the flags, here are some links:

- https://github.com/ajeetdsouza/zoxide/blob/c6ab1012e43cf452d529749419f2154d8c8c4bd0/src/cmd/query.rs#L81
- https://github.com/ajeetdsouza/zoxide/blob/c6ab1012e43cf452d529749419f2154d8c8c4bd0/src/util.rs#L41
- https://github.com/ajeetdsouza/zoxide/blob/c6ab1012e43cf452d529749419f2154d8c8c4bd0/src/util.rs#L62

**Comment by joshmedeski** [comment]
Thanks, look like `--no-sort` was the main thing I needed. A little counter-intuitive but I get why it works :)
