### ISSUE TITLE
Zoxide v9 database doesn't update (Windows - PowerShell)

### ISSUE THREAD

**Issue by Samwell9854** [ajeetdsouza/zoxide#586]
# Issue
(Following OS reinstall of computer) Installed zoxide latest version 0.9.1. Regular usage of zoxide does not populate the database. The database does get created under `%LOCALAPPDATA%\zoxide`, but it remains empty. `zoxide query -l` doesn't return anything.

# Setup
* OS: Windows 11 Pro
* Shell: PowerShell Core 7.3.4
* Install command: `winget install ajeetdsouza.zoxide --source winget --scope=machine`
* zoxide is invoked via `z`

# Additional tests
1. Using the command `zoxide add <PATH>` does work, then invoking the relative path via `z` also works.

2. Manually replacing the files with zoxide v0.8.3 fixes the issue.
Folder replaced: `C:\Program Files\WinGet\Packages\ajeetdsouza.zoxide_Microsoft.Winget.Source_8wekyb3d8bbwe`

3. Uninstalling zoxide v0.9.1, then reinstalling the same version with regular command `winget install zoxide` installs under `%LOCALAPPDATA%` instead of `%ProgramFiles%`, but doesn't fix the issue.

4. Running PowerShell Core with or without elevation both have the issue.

**Comment by mtfu** [comment]
I have the same issue, that the database won't upgrade with new entries.
Zoxide (Installed with chocolatey).
OS: Windows 10
Shell: Powershell Core 7.3.4

**Comment by TzviPM** [comment]
Same issue. Version info:

```
> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

To clarify, does this issue affect anyone not using windows? If not, can we update the issue title to clarify that?

**Comment by TzviPM** [comment]
I just installed the latest powershell on my computer and switched to powershell 7 from windows powershell and all is working as expected.

```
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Samwell9854** [comment]
I've moved the database and tried again with PS 7.3.5 and zoxide v0.9.1, same problem. Database file in `%LOCALAPPDATA%\zoxide` does get created.
```
~#@❯  zoxide query -l
~#@❯  z Favorites
~#@❯  z some/other/folder
~#@❯  zoxide query -l
~#@❯  z Favorites
zoxide: no match found
~#@❯  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

~#@❯  zoxide -V
zoxide v0.9.1
```

**Comment by ajeetdsouza** [comment]
Can you verify that the `zoxide init` is at the bottom of your configuration file? If you're using a custom prompt or something similar, it might clash with zoxide's initialization function.

**Comment by Samwell9854** [comment]
This is the content of my PowerShell profile:
```
[...]
# Load zoxide
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd' }
    (zoxide init --hook $hook powershell) -join "`n"
})

# Use posh-git
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme slimfat

Write-Host "Custom PowerShell Environment Loaded"
```
I've changed the order so that the block 'Load zoxide' comes after 'Use posh-git', but remains before the last 'Write-Host' line. This has fixed the issue. Version 0.9.1 now properly adds automatically new entries to the database and is usable. Thank you for the help!
