### ISSUE TITLE
zoxide query keyword -l It is not possible to list all matches

### ISSUE THREAD

**Issue by webxmsj** [ajeetdsouza/zoxide#593]
zoxide query keyword -l It is not possible to list all matches

**Comment by ajeetdsouza** [comment]
Could you elaborate?

**Comment by webxmsj** [comment]
This is the result of my two queries using the command, why only one piece of data is matched the second time

<img width="449" alt="image" src="https://github.com/ajeetdsouza/zoxide/assets/40289489/287ef33a-705f-4a0f-aaea-2ca1f8df2e39">

**Comment by ajeetdsouza** [comment]
This is expected behaviour, see the matching algorithm [here](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm#matching).

If you want to see subdirectories of `company`, you could use `zoxide query -l company /`.
