### ISSUE TITLE
Nushell let-env deprecation

### ISSUE THREAD

**Issue by ehawman** [ajeetdsouza/zoxide#599]
They have settled on removing `let-env` in favor of just `$env.FOO = "BAR"`. That affects lines 10-15 of the generated init script.

https://www.nushell.sh/blog/2023-07-25-nushell_0_83.html

nushell 0.83.1
zoxide v0.9.1

Until then I'm just running `sd -s 'let-env ' '$env.' ~/.config/nu/functions/zoxide.nu` after the init line

**Comment by charlesroper** [comment]
Or you could use the built-in `str replace` command:

`zoxide init nushell | str replace --string --all 'let-env ' '$env.' | save -f ~/.zoxide.nu`

**Comment by ehawman** [comment]
@charlesroper ooh much more slick. Ty!

**Comment by charlesroper** [comment]
For info: https://www.nushell.sh/blog/2023-07-30-nushell_0_83_1.html#what-will-the-hot-fix-release-not-address

**Comment by PhilVoel** [comment]
The issue has already been fixed in #587. We just have to wait for the next release to publish those changes. In the meantime you can use [@charlesroper's fix](https://github.com/ajeetdsouza/zoxide/issues/599#issuecomment-1659120147)

**Comment by ehawman** [comment]
@PhilVoel oh man I searched for this issue but I must not have had the right terms. Didn't mean to make a dupe! 

Thanks for letting me know!

**Comment by ajeetdsouza** [comment]
Released in 0.9.2.
