### ISSUE TITLE
Breaking change in nushell breaks zoxide

### ISSUE THREAD

**Issue by daniel-g-gagnon** [ajeetdsouza/zoxide#601]
The new release of nushell (0.83 on 2023-07-25) has a breaking change that deprecates `let-env VAR = ` and replaces it with `$env.VAR = `. There is no transition period between both syntaxes and nushell integration breaks with the latest nushell.

https://www.nushell.sh/blog/2023-07-25-nushell_0_83.html

**Comment by notohh** [comment]
Resolved in #587

**Comment by ajeetdsouza** [comment]
Fixed in 0.9.2.
