### ISSUE TITLE
support path alias?

### ISSUE THREAD

**Issue by pedoc** [ajeetdsouza/zoxide#608]
For example, can I do

```
zoxide add C:\aaaa\bbbbb\cccc\dddd nice-name
z nice-name //This will jump to C:\aaaa\bbbbb\cccc\dddd
```

**Comment by ajeetdsouza** [comment]
This seems much better served by just a regular alias:

```bash
alias nice-name='cd "C:\aaaa\bbbbb\cccc\dddd"'
```

That way, you can also back it up with the rest of your dotfiles. zoxide is meant to be automatic - the user should not have to think about setting up aliases manually.

**Comment by dkmar** [comment]
https://github.com/ajeetdsouza/zoxide/issues/1002#issuecomment-3126830152
> regarding Path Aliases (608), for fish shell users we can do it with [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html). Sometimes for jumping to my Documents folder I type `z docs` which previously didnt work since it's not a substring of "documents".

> I can add an abbreviation that substitutes "docs" in the context of the "z" command with "documents" like so:
`abbr --add --command z -- docs documents`

> In this way we can do zoxide-specific aliasing/nicknaming.

This abbreviation means when you execute `z docs`, the commandline will be replaced with `z documents` before being ran.

**Comment by azaleacolburn** [comment]
> That way, you can also back it up with the rest of your dotfiles. zoxide is meant to be automatic - the user should not have to think about setting up aliases manually.

@ajeetdsouza Does this mean you are not in favor of adding the bookmark command in #1019?
