### ISSUE TITLE
Installation instructions to Debian and derivatives

### ISSUE THREAD

**Issue by lfromanini** [ajeetdsouza/zoxide#612]
Hi, I added `zoxide` to [pacstall](https://pacstall.dev/), with is available by default to the new Ubuntu rolling release [Rhino](https://rhinolinux.org/). It works fine for Debian and all derivatives (amd64 or arm64). Please, consider adding this alternative to the [installation page](https://github.com/ajeetdsouza/zoxide#installation).

Direct link to zoxide in pacstall is:
[https://pacstall.dev/packages/zoxide-deb](https://pacstall.dev/packages/zoxide-deb)

Simplified instructions:
```bash
sudo bash -c "$( curl -fsSL https://pacstall.dev/q/install )"
pacstall --install zoxide-deb
```

Reasoning: the zoxide version available at official repos is very old.

**edit:** added reasoning

**Comment by ajeetdsouza** [comment]
Done: https://github.com/ajeetdsouza/zoxide/commit/9cbd029438f888b52d2babda97460e39e25dd38d
