### ISSUE TITLE
Fuzzy finding: use `nucleo`

### ISSUE THREAD

**Issue by tgross35** [ajeetdsouza/zoxide#617]
The `helix` team announced [`nucleo`](https://github.com/helix-editor/nucleo) this week, which is a Rust alternative to `fzf` and is apparently even more performant. The library portion is available as [`nucleo-matcher`](https://docs.rs/nucleo-matcher/0.2.0/nucleo_matcher/). Since it is maintained by Helix, it will likely be well supported.

Could this be added to do fuzzy finding, rather than needing a separate install `fzf`?

**Comment by ajeetdsouza** [comment]
`nucleo` appears to be just a matching library. Much more work would be needed to replicate the fzf TUI.

From the README, it looks like they do have plans to build a TUI app. If they build an embeddable library for this that is cross-platform and has the fzf features we use (no sort, reverse, preview), I'd be willing to switch over.

**Comment by tgross35** [comment]
Thanks for the quick response. Isn't fzf also used without the TUI to find inexact matches in the database?

**Comment by ajeetdsouza** [comment]
Nope. When there are very few characters, fzf doesn't work as well as a specialized algorithm.

**Comment by vipierozan99** [comment]
Still, wouldn't it make sense to support fuzzy matching without the TUI?

example:
- I wanna go to `/app/services/`
- I type `servces`
- It's the closest match in the database
- it goes there?
