### ISSUE TITLE
Custom alias function combining exa and zoxide

### ISSUE THREAD

**Issue by JxJxxJxJ** [ajeetdsouza/zoxide#623]
Hi. I've been trying to make the following function work 
```sh

function cs () {
    z "$@" && exa --color=auto --icons --group-directories-first -a
  }
alias cd='cs'

``` 
the problem is the following 

![image](https://github.com/ajeetdsouza/zoxide/assets/103049321/5c21f85c-9ace-4929-a182-8b7421e634ac)

I installed zoxide but somehow the command `z` is not recognized

**Comment by ajeetdsouza** [comment]
Did you follow the [installation instructions](https://github.com/ajeetdsouza/zoxide#installation)?

**Comment by ajeetdsouza** [comment]
There's very likely an issue with your configuration - either `eval "$(zoxide init zsh)"` is not being called or it's being overwritten by some other command. If you could share your config files, I could take a look.

**Comment by JxJxxJxJ** [comment]
Probably, thank you for your help. My config is the following: 

First in `~/.zshenv` I have 
```zsh 
ZDOTDIR="$HOME/.config/zsh"

# vim:ft=zsh
. "$HOME/.cargo/env"
```

Then that `zsh` folder looks like this 
![image](https://github.com/ajeetdsouza/zoxide/assets/103049321/7b3a63d1-6f55-4a91-a986-8feca695bc29)
And in `options.zsh` I had 

```zsh
command -v zoxide &>/dev/null && eval "$(zoxide init zsh)"
```

note that I tested with both 

```zsh
command -v zoxide &>/dev/null && eval "$(zoxide init zsh)"
```  
and just `eval "$(zoxide init zsh)"`. 

Another thing I think it's worth mentioning is that I have the `z` command working, it's just when trying to do the alias that it doesn't recognize it. In `alias.zsh` I have 
```zsh

function cs () {
    z "$@" && exa --color=auto --icons --group-directories-first -a
  }
alias cd='cs'
```

And this shows the following behaviour 
![image](https://github.com/ajeetdsouza/zoxide/assets/103049321/c7cf2710-88eb-4e1d-922a-a39eb791c4a6)

**Comment by ajeetdsouza** [comment]
Try aliasing to `__zoxide_z` instead of `z`. Does it work then?

**Comment by JxJxxJxJ** [comment]
It works, yes. Thank you
