### ISSUE TITLE
Zoxide fails when the database is a symblic links

### ISSUE THREAD

**Issue by thisismygitrepo** [ajeetdsouza/zoxide#628]
I'm moving the database from its default location to somewhere in my dotfile manager, so I can sync it with other machines etc.
However, zoxide fails, eventhough I created a symlink in the default location pointing to the actual database.
The error is: `corrupt database`.

I have similar issue on both linux and windows machines (separate databases).

**Comment by elmoteroloco** [comment]
I have my `Temp` folders on a `RAM disk` via symbolic link and Zoxide just won't install (`An unexpected error occurred while running the command: weakly_canonical: unknown error: "R:\Temp\WinGet\ajeetdsouza.zoxide.0.9 .4\extracted\zoxide.exe"`)

**Comment by ajeetdsouza** [comment]
Fixed in https://github.com/ajeetdsouza/zoxide/commit/cca399e176f0cf9cf6a39f0e623e5ef189692856.
