### ISSUE TITLE
nushell breaking changes

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#630]
Heads-up @ajeetdsouza, With https://github.com/nushell/nushell/pull/10566 we will deprecate the `def-env` syntax in nushell. Our next release 0.86.0 on Oct-17 will allow both old and new syntax but the next release, 4 weeks later, [will produce a warning](https://github.com/nushell/nushell/pull/10715).  The new syntax is `def --env`.

**Comment by marcelarie** [comment]
Thanks this was really helpful!

**Comment by fdncred** [comment]
@lpnh This last part has nothing to do with zoxide.
```
Error:   × Config record contains invalid values or unknown settings

Error:   × Error while applying config changes
     ╭─[/home/user/.config/nushell/config.nu:152:1]
 152 │
 153 │ ╭─▶     cd: {
 154 │ │           abbreviations: false # allows `cd s/o/f` to expand to `cd some/other/folder`
 155 │ ├─▶     }
     · ╰──── $env.config.cd is an unknown config setting
 156 │
     ╰────
  help: This value will not appear in your $env.config record.
```
$env.config.cd.abbreviations was removed from nushell in favor of using our path completions that work similarly now. You just need to comment that out of your config.nu (or remove that part).

**Comment by acidghost** [comment]
As far as I can see the only two places where zoxide needs to be updated are https://github.com/ajeetdsouza/zoxide/blob/073500cbdf8ba211e5115fc6e51411cf2468fc5b/templates/nushell.txt#L42-L61

I think it's just a matter of replacing `def-env` with `def --env`.

**Comment by Mickychen00** [comment]
Hello. I have notice there is a fix commit "f537a4e6d2f8c2eb84c63f79e290a6d1b16eeb71" in zoxide. How can I install this dev version of zoxide?

**Comment by marcelarie** [comment]
Not sure but it might be `brew install --HEAD zoxide` in macOS

**Comment by Slushee-a** [comment]
When will this be pushed to crates.io? Currently having to install from git.

**Comment by Aarkon** [comment]
Nushell has just published their update, removing `def-env` altogether. As far as I understand, this breaks zoxide entirely in nu. Providing a fixed release on crates.rs anytime soon has become somewhat urgent now, I’d say.

**Comment by dtscherer** [comment]
For now I'm just using this in my env.nu
```Nushell
zoxide init nushell | str replace "def-env" "def --env" --all | save -f ~/.config/nushell/modules/.zoxide.nu
```

**Comment by dc740** [comment]
Hey, the list of incompatibilities grew longer. 

```
❯ z 3d_designs
Error:   × Automatically spreading lists is deprecated
    ╭─[/home/user1/.zoxide.nu:30:1]
 30 │   } else {
 31 │     (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
    ·                                         ──┬──
    ·                                           ╰── Spreading lists automatically when calling external commands is deprecated and will be removed in 0.91.
 32 │   }
    ╰────
  help: Use the spread operator (put a '...' before the argument)


[WARN] - (starship::utils): Executing command "/usr/bin/git" timed out.
[WARN] - (starship::utils): You can set command_timeout in your config to a higher value to allow longer-running commands to keep executing.
```

Which can also be added as a workaround because there are two places where `-- $rest` is used

    zoxide init nushell | str replace "-- $rest" "-- ...$rest" --all | str replace "def-env" "def --env" --all | save -f ~/.zoxide.nu
