### ISSUE TITLE
Completion not working in Zsh when following Installation Guide

### ISSUE THREAD

**Issue by ImmanuelHaffner** [ajeetdsouza/zoxide#633]
I installed Zoxide on ArchLinux with Pacman and set up my zshrc as specified in the Install Guide by appending the following line *at the very end of the file*:
```bash
eval "$(zoxide init zsh)"
```

Completions don't work at all. When I enter `z` in the terminal and press `<Tab>`, I am suggested a hyphen `-`. Pressing `<Tab>` once more, I get a list of CLI args:
```plain
-1  -- remove only consecutive duplicates from group
-2  -- preserve all duplicates
-A  -- populate array with expanded matches instead of adding them
-D  -- delete elements from array corresponding to non-matching candidates
-F  -- specify array of ignore patterns
-I  -- specify ignored suffix
-J  -- specify match group
-M  -- specify matching specifications
-O  -- populate array with matches instead of adding them
-P  -- specify prefix
-Q  -- disable quoting of possible completions
-R  -- specify function for suffix autoremoval
-S  -- specify suffix
-X  -- specify explanation
-i  -- specify ignored prefix
-n  -- hide matches in completion listing
-o  -- specify order for matches by match string not by display string
-p  -- specify hidden prefix
-q  -- make suffix autoremovable
-r  -- specify character class for suffix autoremoval
-s  -- specify hidden suffix
-x  -- specify unconditional explanation
```

I checked that `z` is really Zoxide:
```bash
$ where z
z: aliased to __zoxide_z
```

In my `.zshrc`, I also have
```bash
autoload -U compinit
```
and
```bash
antigen bundle zsh-users/zsh-completions
```
I tried w/o these lines, but same behavior.

I expected completions for the directories I've saved with Zoxide, e.g. I did `z ~/Documents/Work`. Then, entering `z Wo` and pressing `<Tab>` should complete to `z Work`, but nope.
I also read through some issues here and found that there was work on completing directories when entering a path, e.g. `z Documents/`, then `<Tab>`, should list directories within `~/Documents` for completion.

**Comment by Rozkalns** [comment]
I am having the same issue described here.

**Comment by yamcodes** [comment]
I'm also experiencing a similar issue with Zsh on an M1 Max, glad to see I'm not alone. Installed using[ zim modules](https://github.com/kiesman99/zim-zoxide), got the exact same interface as `cd` (not completing anything other than the immediate children of the current directory).

Thought it was a problem with the zim module, removed it, installed through the official guide using Homebrew and directly as the last line of `.zshrc`, and still the same result. Oof.

**Comment by ImmanuelHaffner** [comment]
Brilliant, thanks!  I now have the following lines at the end of my `.zshrc`:
```zsh
if [ -x "$(which zoxide)" ];
then
    function z () {
      __zoxide_z $@
    }
    compdef z="_z"

    eval "$(zoxide init zsh --no-cmd)"
fi
```
