### ISSUE TITLE
Hilbish support

### ISSUE THREAD

**Issue by tsukki9696** [ajeetdsouza/zoxide#635]
Is it possible to add zoxide support/instructions for the [Hilbish shell](https://github.com/Rosettea/Hilbish) -- which is a shell configured in Lua --, currently the only zoxide-like app there is `jump`, which is in my opinion very inferior compared to zoxide. I'd like to know if using zoxide in hilbish is possible or not, thanks in advance.

**Comment by ajeetdsouza** [comment]
For now, this would be hard to support ofiicially - Hilbish is a very new shell and does not appear to have a lot of users. However, if you'd like to write your own zoxide plugin, this is very easy to do - for example, the official Fish plugin is just 57 lines of code (not counting comments).

- Every `cd` command must call `zoxide add $PWD` after completion.
- Implement a `z` command that calls `zoxide query $args`, and `cd` into the result.

If you're familiar with the syntax of any supported shell, you can get some inspiration from running `zoxide init $SHELL` and checking the output.

I'll close this issue for now, but if you do end up building it, I'd be happy to review it and add a link to the README!
