### ISSUE TITLE
Complete replacement for fasd with keybindings

### ISSUE THREAD

**Issue by timkgh** [ajeetdsouza/zoxide#641]
Any way to make zoxide a complete replacement for fasd that works for both files and directories?

What about these keybindings?
https://github.com/clvv/fasd#tab-completion

```
bindkey '^X^A' fasd-complete    # C-x C-a to do fasd-complete (files and directories)
bindkey '^X^F' fasd-complete-f  # C-x C-f to do fasd-complete-f (only files)
bindkey '^X^D' fasd-complete-d  # C-x C-d to do fasd-complete-d (only directories)
```

Right now I run both fasd and zoxide in zsh and these completions don't work anymore:

> Word mode completion can be triggered on any command. Word completion is triggered by any command line argument that starts with , (all), f, (files), or d, (directories), or that ends with ,, (all), ,,f (files), or ,,d (directories).

It would be nice to make zoxide do all of the above so I can retire fasd.

**Comment by ajeetdsouza** [comment]
zoxide does not support files. I've seen the fasd project and have considered it, but when it comes to fuzzy matching, I would much rather have a flow where I can `cd` into a directory, potentially correct it if zoxide guessed wrong, and open the correct file myself. Having the wrong file open up (in an editor / video player / etc) just seems cumbersome IMO.

That said, you can set up keybindings for zoxide pretty easily - check out `zoxide query --help`.
