### ISSUE TITLE
[powershell] I've changed the prompt on powershell, and now zoxide won't add the path to the database when I used the `z` command.

### ISSUE THREAD

**Issue by yisuixinq** [ajeetdsouza/zoxide#644]
- What version of zoxide are you running?
zoxide 0.9.2

- What command are you using to initialize zoxide?
```
Invoke-Expression (& {
    $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd' }
    (zoxide init --hook $hook powershell) -join "`n"
})
```

- the powershell prompt function:
```
function prompt
{
# $host.UI.RawUI.WindowTitle = Get-Location
  $tmp=($pwd.path -split "\\")

  if ($tmp[-1] -eq "")
  {
    $prompts=$tmp[0]
  }
  elseif($tmp[-1] -ne "")
  {
    $prompts=$tmp[-1]
  }
  "PS: $prompts> "
}
```

when I disable the `function prompt`, the zoxide works well.

**Comment by ajeetdsouza** [comment]
Are you calling `zoxide init` before initializing your prompt? If yes, that's probably your issue - you can fix this by moving zoxide to the end of your config file.

**Comment by yisuixinq** [comment]
> Are you calling `zoxide init` before initializing your prompt? If yes, that's probably your issue - you can fix this by moving zoxide to the end of your config file.

No, I Call the `zoxide init` at the end of powershell config file.

**Comment by NoahELE** [comment]
> Are you calling `zoxide init` before initializing your prompt? If yes, that's probably your issue - you can fix this by moving zoxide to the end of your config file.

It solves the problem for me. Did you call the prompt function after the zoxide init?

Also it seems that the setup script has been updated to `Invoke-Expression (& { (zoxide init powershell | Out-String) })`. I wonder if this would be the problem.

**Comment by ajeetdsouza** [comment]
@yisuixinq would you mind sharing your PowerShell config, and what version of PowerShell you're using?
