### ISSUE TITLE
PowerShell warning: Invoke-Expression is used. Please remove Invoke-Expression...

### ISSUE THREAD

**Issue by stax76** [ajeetdsouza/zoxide#656]
VS Code shows this WARNING:

Invoke-Expression is used. Please remove Invoke-Expression from script and find other options instead.PSScriptAnalyzer(PSAvoidUsingInvokeExpression)

How do I get rid of this warning?

**Comment by ajeetdsouza** [comment]
zoxide generates an initialization script which is evaluated by PowerShell using `Invoke-Expression`. It's the same mechanism used by similar tools like `atuin`, `starship`. etc.

`Invoke-Expression` can be unsafe when run on untrusted text input, but in this case it's perfectly fine to use.
