### ISSUE TITLE
Generated .zoxide.nu has incorrect syntax

### ISSUE THREAD

**Issue by SirLarion** [ajeetdsouza/zoxide#661]
I'm using Arch Linux with Nushell 0.88.1. After `zoxide init nushell | save -f ~/.zoxide.nu` and `source ~/.zoxide.nu` I get the following:

```
Error: nu::shell::external_command

  × External command failed
    ╭─[/home/sirlarion/.zoxide.nu:25:1]
 25 │ # Jump to a directory using only keywords.
 26 │ def-env __zoxide_z [...rest:string] {
    · ───┬───
    ·    ╰── did you mean 'let-env'?
 27 │   let arg0 = ($rest | append '~').0
    ╰────
  help: No such file or directory (os error 2)

```

Then I manually change the offending parts in .zoxide.nu to `let-env` as recommended by the error but then I get:

```
Error: nu::parser::expected_keyword

  × Expected keyword.
    ╭─[/home/sirlarion/.zoxide.nu:25:1]
 25 │ # Jump to a directory using only keywords.
 26 │ let-env __zoxide_z [...rest:string] {
    ·                    ────────┬───────
    ·                            ╰── expected =
 27 │   let arg0 = ($rest | append '~').0
    ╰────

```

This one I was not able to fix.

Environment is:
Kernel: 6.6.10-arch1-1
Terminal: Konsole 23.08.4
Shell: Nushell 0.88.1
Zoxide version 0.9.2

**Comment by azzamsa** [comment]
> Hmm, looks like the latest `templates/nushell.txt` does have the correct syntax of `def --env` rather than `def-env`. Somewhy I'm still getting the wrong generated code from the latest version

What you are seeing is a `master`, not the latest release of `0.9.2` https://github.com/ajeetdsouza/zoxide/blob/1bfcdfacf22fe22ff05ad2813aac7c0d14dfba36/templates/nushell.txt#L42

To solve the issue you have to 1) compile from source, or 2) ask the maintainer to cut a release.

**Comment by dvbnrg** [comment]
> Hmm, looks like the latest `templates/nushell.txt` does have the correct syntax of `def --env` rather than `def-env`. Somewhy I'm still getting the wrong generated code from the latest version

That fixed everything! Thank you good sir!

**Comment by ReallySnazzy** [comment]
To be clear for anyone else facing this issue:

If you're using nushell 0.89.0 and inside ~/.zoxide.nu you see def-env, then you can replace the 2 instances of `def-env` with `def --env` to resolve the "No such file or directory (os error 2)"

**Comment by apraga** [comment]
@ReallySnazzy fix also solves the second issue with `[ ... rest:string]`.

**Comment by ajeetdsouza** [comment]
Fixed.

**Comment by ajeetdsouza** [comment]
Please upgrade your version of zoxide.
