### ISSUE TITLE
Nushell 0.89 deprecation

### ISSUE THREAD

**Issue by Zuruuh** [ajeetdsouza/zoxide#662]
Context: since [nushell 0.89](https://www.nushell.sh/blog/2024-01-09-nushell_0_89_0.html), the `...` operator can be applied to params passed to a command; and it is deprecated not to do so (giving the following output when using zoxide):
```
Error:   × Automatically spreading lists is deprecated
    ╭─[/home/zuruh/dotfiles/.config/nushell/plugins/zoxide.nu:30:1]
 30 │   } else {
 31 │     (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
    ·                                         ──┬──
    ·                                           ╰── Spreading lists automatically when calling external commands is deprecated and will be removed in 0.91.
 32 │   }
    ╰────
  help: Use the spread operator (put a '...' before the argument)
```

**Comment by CarterLi** [comment]
I compiled zoxide with newest fix for Windows in case someone needs: https://github.com/CarterLi/zoxide/releases/tag/nufix2

**Comment by krestomantsi** [comment]
any updates on this? It still doesnt work on Arch and nushell.

**Comment by binhtran432k** [comment]
I found a workaround by myself.
```nushell
zoxide init nushell | str replace "$env.PWD -- $rest" "$env.PWD -- ...$rest" --all | save -f ~/.zoxide.nu
```

**Comment by krestomantsi** [comment]
doesnt work for me. Do I have to add this command on my env file?

**Comment by binhtran432k** [comment]
> doesnt work for me. Do I have to add this command on my env file?

yes it is just same as the config you put in your env, the solution is just replace the deprecated code with new one before save it to `~/.zoxide.nu`

**Comment by fnuttens** [comment]
@binhtran432k your workaround doesn't cover interactive zoxide calls (`zi`). I suggest this one:

```nu
zoxide init nushell | str replace --all "-- $rest" "-- ...$rest" | save -f ~/.zoxide.nu
```

**Comment by st-clair-clarke** [comment]
I am using zoxide v0.4.3-unknown on Linux Mint Debian Edition - none of the above suggestion works. I keep receiving the following error:

error: 'nushell' isn't a valid value for '<shell>'
        [possible values: bash, fish, posix, powershell, zsh]


USAGE:
    zoxide init <shell> --cmd <cmd> --hook <hook>

**Comment by mati865** [comment]
@st-clair-clarke you should update to newer version.

**Comment by st-clair-clarke** [comment]
After updating I receive the same error as described above - the fix did not work.

**Comment by fnuttens** [comment]
@st-clair-clarke you mean your version of zoxide still rejects nushell as a shell? Are you sure you're using zoxide `0.9.2`?

**Comment by st-clair-clarke** [comment]
I am using the correct one. With the help of the nushell guys at discord it was solved as shown below:

zoxide init nushell | str replace --all "-- $rest" "-- ...$rest" | str replace --all "def-env" "def --env"  | save -f ~/.zoxide.nu

Note second replacement of the deprecated code. Thank you.
