### ISSUE TITLE
zoxide has not yet been packaged for your architecture (powerpc64le-unknown-linux-musl)

### ISSUE THREAD

**Issue by jmr533** [ajeetdsouza/zoxide#668]
Full message:

```
Detected architecture: powerpc64le-unknown-linux-musl
Error: zoxide has not yet been packaged for your architecture (powerpc64le-unknown-linux-musl), please file an issue: https://github.com/ajeetdsouza/zoxide/issues
```

I get this when trying to install zoxide on an RH8 machine on ppc64le. I haven't found a binary out there yet that works with this.

**Comment by ajeetdsouza** [comment]
Rust doesn't fully support `powerpc64le-unknown-linux-musl` yet: https://doc.rust-lang.org/nightly/rustc/platform-support.html

Closing this for now, but feel free to reopen once there is a way to compile Rust to this platform.
