### ISSUE TITLE
Have to compile from source when install with linuxbrew

### ISSUE THREAD

**Issue by sandangel** [ajeetdsouza/zoxide#67]
I installed zoxide with `brew install ajeetdsouza/zoxide/zoxide` 

The binary has to be compiled from source when I install with linuxbrew. Is that a bug? I think it should download the precompiled binary in the github release page.

**Comment by cole-h** [comment]
This is expected, see the recipe: https://github.com/ajeetdsouza/homebrew-zoxide/blob/e941d4aefa1132f0973be65b98fef2dbcbf1b340/zoxide.rb#L10.

This appears to be common for Rust packages; for example, `exa`: https://github.com/Homebrew/homebrew-core/blob/6a39dfa5a1b2c379f41b2a2f55c8baae75e0d553/Formula/exa.rb#L22.

**Comment by ajeetdsouza** [comment]
While Homebrew packages do require compilation by default, most official ones are also packaged into [bottles](https://docs.brew.sh/Bottles), which download precompiled binaries. For now, we aren't using bottles, but perhaps we could add it in to prevent compilation on common targets.

**Comment by sandangel** [comment]
It would be really nice. I had to install rust just to compile this. Thanks @ajeetdsouza . I'm learning rust so hopefully I could somehow contribute to this tool.

**Comment by ajeetdsouza** [comment]
Hey @sandangel,

zoxide is now officially part of homebrew-core. This should fix your issue!

**Comment by sandangel** [comment]
@ajeetdsouza when I install zoxide, I still need to compile it from source, brew downloaded and installed rust as a build dependency.

**Comment by ajeetdsouza** [comment]
@sandangel my bad, a bottle for Linuxbrew hadn't been built yet. I put in a bottle request issue on linuxbrew-core which has been fixed, so it should work now!
