### ISSUE TITLE
Filter results to subset. Maybe `_ZO_INCLUDE_DIRS`

### ISSUE THREAD

**Issue by theherk** [ajeetdsouza/zoxide#679]
I'd love to be able to call `query` but only return directories that contain `.git/` for example. Since I can already list those quite simply, it seems adding an "include" feature would allow me to select from the subset I seek.

Or is there another way to do this currently?

I want to search for all directories that are git roots using the scores as given in the zoxide data.

---

Worth noting, a simple workaround is to add something like ` | rg -Fxf ~/.projects`, but that only works with `query -l` not `query -i`.

**Comment by ajeetdsouza** [comment]
`zoxide query -l "/.git/"` would give you all entries within directories named `.git`, but not the `.git` directories themselves.

`zoxide query -l "/.git" "/"` would give you all entries within `.git` as well as `.git` itself.

**Comment by theherk** [comment]
Appreciate the follow up, but that doesn't seem to address what I seek; I was probably unclear. Imagine a list of directories:

- a
- b
- a/.git

From that list, I only want to find "a". That is the root of a git directory. But your solution allows me to find "a/.git", I believe. That is of course, similarly useful, but the trouble is "a" is the actual directory I need to find, and that has a correctly incremented score, as it is the directory I use.

What I'm doing at the moment is building a list of these project roots [here](https://github.com/theherk/commons/blob/main/bin/repocache.sh) with `fd -HI -d 6 "^\.git\$" $P | xargs dirname 2>/dev/null`, then using this as a filter for the response from `zoxide query -l`, but I can't use it interactively.
