### ISSUE TITLE
Intermittent database corruption

### ISSUE THREAD

**Issue by coljac** [ajeetdsouza/zoxide#68]
Twice in the last month, since I have started using zoxide, the database has become corrupted and I've lost my history.

This manifests as `zoxide: could not read from database` messages at each command prompt; `~/.zo` is zero bytes.

I think this has something to do with killing a process using ctrl-c but I haven't been able to reproduce this yet. I'm using oh-my-zsh.

**Comment by ajeetdsouza** [comment]
Could you check your zoxide version?

```sh
zoxide --version
```

There were some corruption issues that got fixed in `0.3.0`.

**Comment by coljac** [comment]
Apologies, my zoxide is out of date (0.1.1). Glad to hear it's fixed.
