### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by acidghost** [ajeetdsouza/zoxide#688]
This repository has been accumulating PRs and issues that have been going unanswered for months.
Breaking changes from upstream Nushell have not been taken care of, even if the PRs have 2 or 3 lines of trivial changes and have been open for months.

@ajeetdsouza, do you need new maintainers? Are you willing to move the repo under an org and give access to someone else? Do you have a contingency plan for this repository (e.g. in case you loose access to it)?

I understand that you may have lost interest, moved on of are just overwhelmed with other stuff. That's perfectly normal.

**Comment by ajeetdsouza** [comment]
Hey, sorry for the delay in response. I was out of town for a couple of months, and was unable to check the issue tracker. I'm putting out a release soon, that should fix the Nushell-related issues.

**Comment by lfrancke** [comment]
Welcome back and thank you very much for your work and the new release!
