### ISSUE TITLE
Store config in XDG_CONFIG_HOME directory

### ISSUE THREAD

**Issue by Lugoues** [ajeetdsouza/zoxide#7]
`XDG_CONFIG_HOME` provides a nice clean place to store config. Would be awesome if zoxide supported it by default.
https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by ajeetdsouza** [comment]
Technically, the `${HOME}/.zo` file isn't configuration; it's more similar to cache. Besides, we would need to use different folders across operating systems, since macOS (and Windows, if it ever gets support) don't follow the XDG standard, leading to inconsistency.

**Comment by Lugoues** [comment]
Ah true enough

**Comment by ajeetdsouza** [comment]
This has been added in https://github.com/ajeetdsouza/zoxide/pull/46/commits/0617571807c461df094ad5e8dc95a154a587db65, and will be released with `zoxide v0.3`!
