### ISSUE TITLE
zoxide is not working on Windows 11 running in pwsh (open source PowerShell)

### ISSUE THREAD

**Issue by Treit** [ajeetdsouza/zoxide#707]
I installed zoxide via `cargo install zoxide` and added the line to my PowerShell (pwsh) $profile per the installation instructions:

```ps
Invoke-Expression (& { (zoxide init powershell | Out-String) })
```

I can switch to directories but it doesn't seem to record them:

```ps
~ via 🐍 v3.11.8
[14:25:56] ✓ z tools

~/tools
[14:26:00] ✓ zoxide query
zoxide: no match found
```

Not sure how to troubleshoot it further.

**Comment by edzhangsy** [comment]
I encountered the same problem.
And it seems you are using the starship, too.
The powershell setup line should be added below the starship setup line.
After the change, open a new pwsh to test.
Then the zoxide should work.

**Comment by pybash1** [comment]
also facing this issue with the `zoxide` line at the bottom of my config

**Comment by Treit** [comment]
I can confirm that moving the zoxide init line to after the Starship init line seems to have fixed it.

```ps
Invoke-Expression (&starship init powershell)
Invoke-Expression (& { (zoxide init powershell | Out-String) })
```

**Comment by pybash1** [comment]
i dont have starship(i use oh-my-posh)...

**Comment by ajeetdsouza** [comment]
@pybash1 `oh-my-posh` is also a custom prompt and has the same issue. You can resolve this by moving `Invoke-Expression (& { (zoxide init powershell | Out-String) })` to the last line in your config.

**Comment by alex1yaremchuk** [comment]
Moving init to the end of pwsh config helped me too. 

Thanks!

**Comment by ajeetdsouza** [comment]
@alex1yaremchuk can you create an issue describing your problem?

**Comment by laciferin2024** [comment]
> I can confirm that moving the zoxide init line to after the Starship init line seems to have fixed it.
> 
> Invoke-Expression (&starship init powershell)
> Invoke-Expression (& { (zoxide init powershell | Out-String) })

magically fixed the problem
