### ISSUE TITLE
Zoxide binary not found when opening new session

### ISSUE THREAD

**Issue by MaximSrour** [ajeetdsouza/zoxide#708]
I'm running Ubuntu Server 22.04.3 and have installed Zoxide using the curl command,

```
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
source ~/.bashrc
```

If I do this, I can then use the z commands just fine. However, when I close the terminal completely and then SSH back in using a completely new session, the eval command in the bashrc (`eval "$(zoxide init --cmd cd bash)"`) gives the following message:

```
Command 'zoxide' not found, but can be installed with:
sudo apt install zoxide
```

The z commands seem to still work just fine, however this is a little annoying and I don't want to pipe it to /dev/null in case there is something else that goes wrong. Any idea what the cause is?

**Comment by fendis0709** [comment]
I'm also facing the same problem.
After executing `export PATH=$HOME/.local/bin` and open new terminal session, command `zoxide` is not found.

Here's my solution (using `.zshrc`):

1. Open text editor, e.g. `nano`

```
nano ~/.zshrc
```

2. Add this command in the file `.zshrc`

```
export PATH=$HOME/.local/bin:$PATH
eval "$(zoxide init --cmd cd zsh)"
```

3. Load the new `.zshrc` config

```
source ~/.zshrc
```

4. Check `zoxide` command

```
zoxide --version
```

Now, you should able to execute Zoxide command.
If you're using bashrc, you should  make a little bit adjustment to edit file `~/.bashrc` and execute `source `~/.bashrc`.

If you want to check the PATH, you can execute `echo $PATH`.
![image](https://github.com/ajeetdsouza/zoxide/assets/16249274/73e01e53-dfa6-474e-95e0-9360fd390580)

**Comment by aidandeli** [comment]
I was also facing that problem. After adding the line mentioned by @fendis0709, I no longer get the message about Zoxide missing, but I am now facing a different problem. I've outlined the different problem here: https://github.com/ajeetdsouza/zoxide/issues/723

**Comment by ajeetdsouza** [comment]
That's the correct solution - `export PATH=$HOME/.local/bin:$PATH` needs to be added to the `.zshrc` file before initializing zoxide. The install script usually warns about this: https://github.com/ajeetdsouza/zoxide/blob/e55e0b27e27930ab8af81999a91b56cf0cd6ff6f/install.sh#L71
