### ISSUE TITLE
Not in OpenBSD package manager.

### ISSUE THREAD

**Issue by DylanJava** [ajeetdsouza/zoxide#713]
`dylanjava$ doas pkg_add zoxide`
`doas (dylan@dylanjava.openbsd.amsterdam) password: `
`quirks-6.160 signed on 2024-02-18T08:58:12Z`
`Can't find zoxide`

**Comment by ajeetdsouza** [comment]
Unfortunately, adding zoxide to official repositories is upto maintainers of your distro. I would recommend requesting OpenBSD package maintainers to see if they can add zoxide.

In the meantime, I would suggest using the install script:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```
