### ISSUE TITLE
Error whilst installing zioxid in zsh on warp terminal

### ISSUE THREAD

**Issue by sneazy-ibo** [ajeetdsouza/zoxide#720]
I started by running the following command as instructed in the guide
```
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```
got a message that I need to add `/Users/ibo/.local/bin` to my path
I did that with nano and saved the line to my `~/.zshrc` file

![image](https://github.com/ajeetdsouza/zoxide/assets/41344259/6908026a-d3db-411f-94b2-980c7a794568)

next thing was configuring zoxide, however the command `compinit` was undefined for me and I could not get it defined

![image](https://github.com/ajeetdsouza/zoxide/assets/41344259/6275a744-ff15-4df7-9dec-9f9bb033dc0e)

after adding a new line called `eval "$(zoxide init zsh)"` to my `~/.zshrc` file as seen I ran `rm ~/.zcompdump*; compinit`and restarted my terminal

after all this procedure `which z` just gives me an z not found error
am I missing out on smth?

**Comment by ajeetdsouza** [comment]
You need to load `compinit` first:

```sh
autoload -Uz compinit
compinit
```

---

`which z` will not work, since `z` is defined as a function. Try using `z`, it should work.

**Comment by rod-stuchi** [comment]
I have similar issue with 0.9.4 on ZSH

![image](https://github.com/ajeetdsouza/zoxide/assets/19471811/80426b12-8071-4c83-aa3a-383f026fd18b)

My workaround was to downgrade to `0.9.2` export `zoxide init zsh` to a file
Upgrade to `0.9.4` and than source that file from `0.9.2`
`zoxide init zsh` is not working for me in ZSH
