### ISSUE TITLE
Any Good Issues for 1st Timers?

### ISSUE THREAD

**Issue by NamkhangNLe** [ajeetdsouza/zoxide#721]

**Comment by ajeetdsouza** [comment]
If you'd like to contribute, https://github.com/ajeetdsouza/zoxide/issues/706 is a great way to start. There's already an `import` implementation for `autojump` and `z` in this file: https://github.com/ajeetdsouza/zoxide/blob/main/src/cmd/import.rs

You could add another one for `jump`. If you'd like to work on this issue, do comment there - I can assign it to you.
