### ISSUE TITLE
Zoxide not adding to db.zo unless you run init again

### ISSUE THREAD

**Issue by aidandeli** [ajeetdsouza/zoxide#723]
_WSL2, kali linux version 2023.3, zoxide version 0.9.3_

I installed via the install script. Whenever I navigate anywhere after first opening a terminal window, I noticed the zoxide database doesn't create entries unless I run `eval "$(zoxide init --cmd cd bash)"` again. My `.bashrc` does have that line, yes. 

I can confirm that zoxide is working, as you can see at the second and third prompts in the image.

If we were to move to a brand new directory, we'd assume zoxide would add the new path to db.zo. However, if you look at the image below, you can see that zoxide doesn't update db.zo. 

Observe that, after I run `eval "$(zoxide init --cmd cd bash)"` again, that zoxide starts tracking the directories I go to, and the db file grows.

![image](https://github.com/ajeetdsouza/zoxide/assets/72891308/9993fdec-9bcf-4676-9f7b-4a28f191d4e1)

**Comment by ajeetdsouza** [comment]
It's possible something else is overriding the prompt. Could you try making `zoxide init` the last line in your shell config?

**Comment by kringalf** [comment]
For me, with my `history -a` addon, it helped setting the PROMPT_COMMAND to:
```
PROMPT_COMMAND="history -a ; __zoxide_hook;${PROMPT_COMMAND#;}"
```
Now the db file increases after using cd to a new dir

**Comment by aidandeli** [comment]
`eval "$(zoxide init --cmd cd bash)"` is the last line in my config file.

I added the line @kringalf mentioned but I'm still having no luck.

**Comment by aidandeli** [comment]
Ah yeah, the output was just `echo`

Adding `export PROMPT_COMMAND="__zoxide_hook;echo"` after `zoxide init`  in my config file fixed it.

**Comment by ajeetdsouza** [comment]
> Ah yeah, the output was just `echo`

That typically means something is running after `zoxide init` and overriding your `PROMPT_COMMAND`. You can use `set -x` in your `.bashrc` to debug this.

**Comment by slak44** [comment]
It might be a good idea to mention PROMPT_COMMAND in the documentation somewhere, as the reason why zoxide should be last. I set that variable in my bash config as well, and until @kringalf mentioned it in his comment, I didn't notice the order.
