### ISSUE TITLE
"no options following" not implemented

### ISSUE THREAD

**Issue by RomanoZumbe** [ajeetdsouza/zoxide#726]
When passing "--" as parameter to zoxide it can't switch to an absolute path given. This makes it somewhat difficult to use it as an alias for cd.

For example the yazi getting started guide uses a shell function which makes use of this and doesn't work when zoxide is used in place of cd.

config in ~/.zshrc:
eval "$(zoxide init --cmd cd zsh)"

example:

    > cd -- /var/log
    zoxide: no match found

**Comment by ajeetdsouza** [comment]
Fixed by https://github.com/ajeetdsouza/zoxide/pull/858.
