### ISSUE TITLE
Print database path in errors

### ISSUE THREAD

**Issue by TimoFreiberg** [ajeetdsouza/zoxide#73]
I had zoxide 0.1.1 installed and encountered the database corruption issue described in #68.
I installed the new version and received the following error message:
```
Error: could not deserialize old database

Caused by:
    io error: failed to fill whole buffer
```

I think zoxide should document the default database locations and also print the database file path when it can't be read.

**Comment by ajeetdsouza** [comment]
That's a valid point, I've been looking into this too. It is documented in the README, but I suppose it isn't very noticeable. The database location is decided by [this](https://docs.rs/dirs/2.0.2/dirs/fn.data_dir.html) function.

**Comment by TimoFreiberg** [comment]
I found that but it didn't help me in my case, the file I had to delete was `~/.zo`, which I only found out via #68 :)

**Comment by TimoFreiberg** [comment]
Looking at the current master, the specific failure I encountered is no longer there and I didn't find any places where the path was missing from `context` calls at a cursory glance, so I think this can be closed

**Comment by ajeetdsouza** [comment]
@TimoFreiberg yes, I've been working on improving zoxide's error messages. Hopefully, such confusions will not happen in future!
