### ISSUE TITLE
Feature request: Add an option to import from Oh My Zsh’s scd

### ISSUE THREAD

**Issue by rwmpelstilzchen** [ajeetdsouza/zoxide#738]
There is a similar plugin for [Oh My Zsh](https://ohmyz.sh/) called [scd](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/scd). I’d suggest to add an option to import previously visited directories from there, for the use of people like me who migrate from Z shell (with scd) to Nu shell (with zoxide). Thanks! 🌼

**Comment by ajeetdsouza** [comment]
Hey, it's difficult to justify maintaining something like this since scd doesn't seem to be very widely used.

**Comment by rwmpelstilzchen** [comment]
I understand, and appreciate the time you put into zoxide 🙂

If you change your mind in the future, the syntax of the relevant file (`~/.scdhistory`) is quite straightforward: IIUC basically each line is a Unix time followed by the path (plus some separating characters, `:` and `;`), with each one logging a single visit.
