### ISSUE TITLE
The database is not being created in Windows Powershell

### ISSUE THREAD

**Issue by shilangyu** [ajeetdsouza/zoxide#74]
## Steps to reproduce

- Install zoxide: `cargo install zoxide -f`
- Add the hook to `$PROFILE`
- Restart terminal
- Go to some dir with zoxide: `z some_dir`
- Check zoxide dir: `ls C:\Users\UserName\AppData\Local\zoxide` (Error! No such directory!)
- Try to match with zoxide: `z some` (Error! No matches!)
- Check zoxide dir again: `ls C:\Users\UserName\AppData\Local\zoxide` (Ok! Now it exists but there is still no db file) 

## Additional info

I am running the default powershell available on windows (`$PSVersionTable.PSVersion.Major` yields 5, thus the hook defaults to `'prompt'` according to the README powershell snippet)

**Comment by shilangyu** [comment]
I can confirm that using PowerShell Core (which is v6+) works with zoxide. So the problem most likely lies in the powershell code generated by `zoxide init --hook prompt powershell`

**Comment by shilangyu** [comment]
Found the culprit: [starship](https://github.com/starship/starship) hooks up to `prompt` overwriting zoxide's hook.

**Comment by ajeetdsouza** [comment]
Does calling `zoxide init` after initializing starship fix your issue?

**Comment by shilangyu** [comment]
It does, thanks

**Comment by ray-x** [comment]
I bumped into this issue today. But as I installed zoxide before starship, so the db file exists. However, it stopped updating after starship was installed.
Suggested to update the issue description to indicate it conflicts with starship.

**Comment by funkyfisch** [comment]
run into this myself today.

Installed starship before zoxide, 

running eval $(zoxide init ...) after starship doesnt help.

**Comment by funkyfisch** [comment]
I found a fix for my specific case - I had the following
```bash
PROMPT_COMMAND="export PROMPT_COMMAND=echo"
eval "$(starship init bash)"
```
It turned out the PROMPT_COMMAND was messing with zoxide somehow (I didnt want the initial newline created by starship, so I removed the newline option from its theme, but then there were no empty lines spacing the different invocations so this needs to be applied.

I changed this to:
```bash
PROMPT_COMMAND="export PROMPT_COMMAND=\$PROMPT_COMMAND;echo"
eval "$(starship init bash)"
```
and that worked for me.
