### ISSUE TITLE
Latest change to fish.txt template breaks zoxide

### ISSUE THREAD

**Issue by IThundxr** [ajeetdsouza/zoxide#741]
From the looks of it https://github.com/ajeetdsouza/zoxide/commit/012c67de635826af2b671f9d3ec82d9303224b36 has broken zoxide on fish, Reverting to to a release before that commit fixes this

zoxide 0.9.4-1
OS: Arch Linux
Kernel: 6.7.6-arch1-2
Shell: fish 3.7.0
DE: GNOME 45.4
WM: Mutter
Terminal: alacritty
CPU: Intel i9-9900K (16) @ 5.000GHz
GPU: NVIDIA GeForce RTX 3060

**Comment by ajeetdsouza** [comment]
Hey, why did you mark the issue as closed? Did you find what the issue was?

**Comment by IThundxr** [comment]
> Hey, why did you mark the issue as closed? Did you find what the issue was?

Seems it was caused by a crash I had when updating my packages a while back, seems pacman decided to break zoxide and reinstalling it with --overwrite="*" seems to have fixed it
