### ISSUE TITLE
tmux can't find zoxide 

### ISSUE THREAD

**Issue by majinaru** [ajeetdsouza/zoxide#749]
After installing zoxide I tried to run tmux and for some reason this happens: (first pic is my normal terminal working fine. Int the second one, tmux is running and can't find zoxide)

![image](https://github.com/ajeetdsouza/zoxide/assets/105825215/034314b3-8e1c-4623-bc01-c03327f9774b)

![image](https://github.com/ajeetdsouza/zoxide/assets/105825215/14a1a0fc-5d3d-4793-b357-258dde13d774)

I'm using zsh, but it also occurs in bash.

**Comment by ajeetdsouza** [comment]
What's the output of `echo $PATH` in both cases?

**Comment by majinaru** [comment]
terminal:
`/home/joao/.cargo/bin:/home/joao/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/joao/.fzf/bin`


tmux: 
`/home/joao/.nvm/versions/node/v21.7.0/bin:/home/joao/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/joao/.fzf/bin`

**Comment by ajeetdsouza** [comment]
Linux looks for executables (like zoxide) in `$PATH` - in the first case, I can see `/home/joao/.local/bin` is present, but it isn't there in the second case. Something is overriding your PATH here.

If you can't find what is overriding your PATH, I would add this line just before the `eval` statement that initializes zoxide:

```sh
export PATH="$HOME/.local/bin:$PATH"
```

**Comment by majinaru** [comment]
Thank you, it worked!
