### ISSUE TITLE
list best entries and fzf tweaks

### ISSUE THREAD

**Issue by syedelec** [ajeetdsouza/zoxide#75]
Hi,

It would be awesome to have the same ability as z.lua to list entries with/without scores, equivalent of `z -l` and `z -l -s`.

I was using these to have my own equivalent of
`zi foo      # cd with interactive selection using fzf`

since zoxide is taking care of it, I have some suggestions on this.

Practically, I never look/worry about scores, it would be great to be able to list entries with fzf without scores.

One nitpick also is to automatically cd to the directory if there is only one match which is not the case currently.

Thanks !

**Comment by ajeetdsouza** [comment]
I've added a `--list` option to `zoxide query` in https://github.com/ajeetdsouza/zoxide/commit/89da276eb7a1080e8c78c7c303d7129aa6f77890, which will print out matching directories in order of their scores. Could you explain your use case for printing out the scores too?

Regarding fzf options, zoxide deliberately uses almost no options to allow the user to customize fzf to their liking. I've added an environment variable `$_ZO_FZF_OPTS` in https://github.com/ajeetdsouza/zoxide/commit/12e9eabe306a3e48f919f2ba38505bfee5c5eb33 to ease this process.

**Comment by syedelec** [comment]
I tried the `next` branch and everything is working as expected for me, I am using the command `zoxide query -l`.

Also I did not have any use case using scores, sorry for misunderstanding.

I have tried the `_ZO_FZF_OPTS` export adding `--select-1` and it seems it overrides the flag `FZF_DEFAULT_OPTS`, do you think it's useful to merge/concatenate both of them if `FZF_DEFAULT_OPTS` is already defined.

On my side, I will be using `zoxide query -l | fzf -1 -0 +m` which works great !
Thanks !

**Comment by ajeetdsouza** [comment]
`_ZO_FZF_OPTS` intentionally overrides `FZF_DEFAULT_OPTS` when set to allow users to completely reset their default fzf options for zoxide if desired. However, it's easy enough to add them back:

```sh
export _ZO_FZF_OPTS="$_FZF_DEFAULT_OPTS --select-1"
```

Hope that helps!

**Comment by syedelec** [comment]
You're right, I missed this.

Everything works as expected, thanks for this tool.
