### ISSUE TITLE
WSL installation error: linker `cc` not found

### ISSUE THREAD

**Issue by mino9421** [ajeetdsouza/zoxide#750]
I am exploring wsl within my windows terminal and have been configuring and ricing it as per usual and wanted to try out zoxide
When I tried to install using 

`cargo install zoxide --locked`

it gave me the following output in the image below:

context:
I ran update/upgrade + rust/cargo updates and they are all up to date. Also provided `echo $PATH` output
Also did some search here and there and installed build-essential just trying things out and still same error output.

![image](https://github.com/ajeetdsouza/zoxide/assets/37200788/cf8c029f-9543-4b05-bd9f-e8618cb96c92)

Will be trying it on my linux machine tomorrow, might be a WSL only thing or I am missing something random

**Comment by ajeetdsouza** [comment]
`apt install build-essential` should fix that. Otherwise, you can use the install script given in the README:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```

**Comment by mino9421** [comment]
I followed all the steps again, and I had to add the PATH using 
export PATH="$PATH:/home/mino/.local/bin"
