### ISSUE TITLE
Interactive completions does not work 

### ISSUE THREAD

**Issue by dbarati-bf** [ajeetdsouza/zoxide#758]
`z foo<SPACE><TAB>` and `z foo` have exactly the same functions in my environment, which is `cd` into highest ranked directory matching foo. I expected `z foo<SPACE><TAB>` to show interactive completions as per the documentation. What am I doing wrong here?

fzf 0.47.0
zoxide 0.9.4

And I'm on zsh on MacOS 14.1.1.

.zshrc is sourced with 
```
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"
```

**Comment by ashleybartlett** [comment]
Do you have any directories in your database yet? If it matches a single path, it will go that one

**Comment by arjun810** [comment]
This used to work for me, but stopped working. I do have directories in my database.

**Comment by ajeetdsouza** [comment]
Closing as duplicate of https://github.com/ajeetdsouza/zoxide/issues/737.
