### ISSUE TITLE
error: The following required arguments were not provided

### ISSUE THREAD

**Issue by xscd** [ajeetdsouza/zoxide#77]
Bash version: bash 5.0.17
Zoxide version: zoxide v0.4.1-unknown

I use Manjaro and installed zoxide from AUR. I have added `eval "$(zoxide init bash)"` to my .bashrc file sourced it and also rebooted but zoxide init still can't recognize my shell. 

Picture from the error:
![Image](https://files.catbox.moe/f8n6d9.png)

**Comment by ajeetdsouza** [comment]
Hi, it looks like you're running `zoxide init` without specifying the shell. Assuming you're running Bash, the command to run is `zoxide init bash`.

**Comment by xscd** [comment]
Thanks I thought the `eval "$(zoxide init bash)"` line would help it to identify my shell. Last question is after I used `zoxide init bash` I see this: ![Image](https://files.catbox.moe/sbit8j.png)

Do I have to add these lines anywhere or is it usable now? Sorry about bothering you with my questions.

**Comment by ajeetdsouza** [comment]
That's not a problem!

The `init` command outputs a script that initializes your shell for use with zoxide. Using it with `eval` runs that script in Bash. So, to initialize zoxide automatically once you start a shell, add `eval "$(zoxide init bash)"` to your `~/.bashrc` file. Unless you're debugging something, you never need to run the `init` command manually.

**Comment by xscd** [comment]
Thanks I just understood the point of eval. And started to use zoxide, looks useful!
