### ISSUE TITLE
Interactive mode (space + tab) doesn't appear to be working on macOS

### ISSUE THREAD

**Issue by ThijmenDam** [ajeetdsouza/zoxide#778]
I have trouble getting the interactive mode to work using the space + tab keyboard shortcut. 

For instance, consider the command `z <some-dir> ` followed by a tab. Instead of going into interactive mode, my terminal shows the files/directories under the `z <some-dir>` command as if I had typed the `ls` command:

```
z <some-dir>
dir1 dir2 dir3
```

I have installed `zoxide` and `fzf` according to their installation instructions, i.e. my `~/.zshrc` file ends with the following two lines:

```
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
```

I use a fresh install of macOS 14.4.1. 

Does anybody else experience this issue?

**Comment by ashleybartlett** [comment]
I had also reported this, and think i've found the fix https://github.com/ajeetdsouza/zoxide/pull/785

**Comment by ajeetdsouza** [comment]
> For instance, consider the command z <some-dir>  followed by a tab.

`z foo<Tab>` will give you local directory completions. `z foo<Space><Tab>` will pull up interactive completions. Are you adding a `<Space>`?

Also, have you called `compinit` _before_ initializing zoxide?
- If `compinit` is not called, zoxide will not initialize completions
- If `compinit` is called after zoxide, it will reset the completions for zoxide

**Comment by ThijmenDam** [comment]
> `Are you adding a `<Space>`?

Yes, I use `z foo<Space><Tab>`

> Also, have you called `compinit` _before_ initializing zoxide?

Should I explicitly call this command in my `~/.zshrc` file? Currently, the file looks like this:

```
eval "$(starship init zsh)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"
```

**Comment by ajeetdsouza** [comment]
> Should I explicitly call this command in my `~/.zshrc` file?

Yup. Add this right at the start of your zshrc file:

```zsh
autoload -Uz compinit
compinit
```

**Comment by ThijmenDam** [comment]
> Yup. Add this right at the start of your zshrc file:
> 
> ```shell
> autoload -Uz compinit
> compinit
> ```

This has resolved the issue. Thank you very much for the support @ajeetdsouza!

**Comment by HaskellZhangSong** [comment]
Same issue here, I just use normal oh my zsh, is it possible to use this SPC TAB trick? May I ask what your shell config is? @ThijmenDam

**Comment by ThijmenDam** [comment]
@HaskellZhangSong 

```
# % cat ~/.zshrc

# necessary for z <path><space><tab> to work
autoload -Uz compinit
compinit

# Pytthon
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# ll command
alias ll='ls -la'

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(starship init zsh)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"
```

**Comment by rome-legacy** [comment]
Hey guys,

same issue with bash on macOS Sonoma 14.7
but instead i use bash. is there a solution for that too?

regards
rome

**Comment by ajeetdsouza** [comment]
These are very likely problems specific to your setup, please create separate issues for these.
