### ISSUE TITLE
Support fuzzy matching with skim

### ISSUE THREAD

**Issue by wezm** [ajeetdsouza/zoxide#78]
In keeping with the Rust theme it might be nice to support fuzzy matching with [skim](https://github.com/lotabout/skim) in addition to `fzf`.

**Comment by ajeetdsouza** [comment]
Skim currently lacks Windows support, which is why it hasn't been considered. See https://github.com/ajeetdsouza/zoxide/issues/3 and https://github.com/ajeetdsouza/zoxide/issues/31.

**Comment by wezm** [comment]
Ahh my apologies. I should have checked for existing issues first.

**Comment by ajeetdsouza** [comment]
Not a problem 😁
