### ISSUE TITLE
zoxide: no match found on startup

### ISSUE THREAD

**Issue by hat082** [ajeetdsouza/zoxide#782]
I'm using a wsl ubuntu on a windows machine. when i first start up my wsl, the cd command doesn't seem to work?

In my .bashrc:
```shell
# z to jump around directories
export _ZO_ECHO=1
eval "$(zoxide init --cmd cd bash)"
```

Weirdly it works after i either source the bashrc again, when i run `eval "$(zoxide init bash --cmd cd)"` manually, or when i remove the `--cmd cd`. Why is this the case?

**Comment by ajeetdsouza** [comment]
> the cd command doesn't seem to work?

Can you elaborate?

**Comment by ajeetdsouza** [comment]
P.S. you need cd to a directory the usual way at least once, so that zoxide can learn which directories you use. 

This video might help: https://www.youtube.com/watch?v=aghxkpyRVDY

**Comment by hat082** [comment]
I am so sorry for the late reply..
I'm new to github and didn't know how to check notifications...

I did use cd at least once, my understanding is that using `$(zoxide init bash --cmd cd)` aliases the z command with cd

but if I use this setup i can no longer use cd nor z?

**Comment by hat082** [comment]
![image](https://github.com/ajeetdsouza/zoxide/assets/129358687/c5c29f1e-66dd-4bfe-b1f5-e0496c3d6190)
as you can see, if i set this --cmd cd, on startup of the wsl I cannot use cd anymore

but if i source the .bashrc file manually 
![image](https://github.com/ajeetdsouza/zoxide/assets/129358687/bb031cff-8843-4c16-b647-fbac9625810c)

cd (or z's replacement for cd) now works as expected.

the `unknown option: --bash` is probably from some other line in the .bashrc file I think

**Comment by ajeetdsouza** [comment]
Something is definitely wrong with your bashrc configuration. If you can share it here, I can take a look.

**Comment by hat082** [comment]
Thank you so much QAQ
[bashrc.txt](https://github.com/ajeetdsouza/zoxide/files/15207301/bashrc.txt)

I believe the ~/.bash_aliases file is empty so that shouldn't be the problem

**Comment by ajeetdsouza** [comment]
1. The same .bashrc file works for me (WSL + zoxide v0.9.4). Are you running a different version of zoxide?

```bash
zoxide -V
```

2. Are you able to find the line that's causing the `--bash` error? You can find it by using `set -x` right at the top of your bashrc file.
3. What is the output of `type cd`?

**Comment by hat082** [comment]
with the --cmd cd option i could no longer use cd so i ctrl c out of it
![image](https://github.com/ajeetdsouza/zoxide/assets/129358687/053b2944-71aa-4f2a-9309-cb0e0c146f74)

here's the type cd and zoxide -V outputs
![image](https://github.com/ajeetdsouza/zoxide/assets/129358687/1ec6f691-bdfa-42ee-af07-0003582fd3f1)

![image](https://github.com/ajeetdsouza/zoxide/assets/129358687/6cbef41c-59f7-4eba-ac1b-84c52b6f2760)
after i source bashrc it works now

I tried the set -x option and it gives me a lot of outputs but i dont really know how to interpret this output

**Comment by ajeetdsouza** [comment]
You have 2 versions of zoxide installed on your system. I'm guessing you first installed it using `sudo apt install zoxide`, and then ran the install script from the README after that.

To fix this:

```bash
sudo apt remove zoxide
```

In your .bashrc:

```bash
export PATH="$HOME/.local/bin:$PATH"
eval "$(zoxide init bash --cmd cd)"
```

**Comment by hat082** [comment]
That solved the issue. My god you are a genius!

**Comment by JacobKovarovic** [comment]
I'm having a similar issue and I've tried everything mentioned in this issue so far. I used the script to install zoxide and added it to my .bashrc. When I `source .bashrc` it works fine, but when I start a new terminal it says "Command 'zoxide' not found". I made sure everything was added to $PATH and it works whenever I source the bashrc.

![image](https://github.com/ajeetdsouza/zoxide/assets/148407509/ea80fa2b-6f83-4f50-869e-dcebe2f8bb24)

### Bashrc
![image](https://github.com/ajeetdsouza/zoxide/assets/148407509/5a0cea00-9ceb-42d0-b88f-d5c7952ab838)

*$HOME/.local/bin is already in $PATH*

OS: Ubuntu 22.04.4
Kernel: WSL2
Shell: Bash 5.1.16

**Comment by ArifulH8** [comment]
@JacobKovarovic I found changing my eval statement to the below fixed the issue
`eval "$(~/.local/bin/zoxide init bash)"
`
I believe the issue is because bash loads the .profile file on startup.
In the profile file it loads .bashrc file and then updates the path with bin files in .local folder.
So while the .profile is setting up everything the .bashrc file cannot find the zoxide bin file. So it will output the error. 
However it then adds the bin file later on. So when you source the .bashrc file the second time it can find bin file.
