### ISSUE TITLE
feasibility integrate with vscode cli(`code`)

### ISSUE THREAD

**Issue by flavono123** [ajeetdsouza/zoxide#789]
is it possible that such as `cd` does. index the paths state and open(rather than move) in vscode.
or any problem? i guess open new file would collide with.

**Comment by ajeetdsouza** [comment]
zoxide is designed for scriptability. Here's a simple POSIX function that does what you want:

```sh
zc() {
  _result="$(zoxide query -- "$@")" && code "$_result"
}}
```

**Comment by flavono123** [comment]
good.
is there a way also on fzf? when stroke space+tab

**Comment by ajeetdsouza** [comment]
```sh
zci() {
  _result="$(zoxide query --interactive -- "$@")" && code "$_result"
}}
```

**Comment by davidgfitzgerald** [comment]
Legend @ajeetdsouza thx for both 🙏
