### ISSUE TITLE
Unable to initialize zoxide in my zsh

### ISSUE THREAD

**Issue by moheladwy** [ajeetdsouza/zoxide#792]
I put this command `eval "$(zoxide init zsh)"` in my .zshrc at the bottom of the file as the README said, 
When I open the terminal I got this error "(eval):51: parse error near \`}" at the startup of the terminal,
I run the command and exported in an external file and then opened it, I found out that the problem with the function __zoxide_z(), the line 51 was the } at the end of the this function.

    function __zoxide_z()  {
        # shellcheck disable=SC2199
        if [[ "$#" -eq 0 ]]; then
            __zoxide_cd ~
        elif [[ "$#" -eq 1 ]] && { [[ -d "$1" ]] || [[ "$1" = '-' ]] || [[ "$1" =~ ^[-+][0-9]$ ]]; }; then
            __zoxide_cd "$1"
        else
            \builtin local result
            # shellcheck disable=SC2312
            result="$(\command zoxide query --exclude "$(__zoxide_pwd)" -- "$@")" && __zoxide_cd "${result}"
        fi
    }

i don't know what is the problem with this function actually. How can I solve this problem?

**Comment by ajeetdsouza** [comment]
What version of zsh are you using? You might need to upgrade it.

```zsh
zsh --version
```

**Comment by moheladwy** [comment]
The Version of the zsh on my system (arch-linux) is 5.9

![image](https://github.com/ajeetdsouza/zoxide/assets/59349012/0ba5cf57-534b-40be-97e4-3ae4ba835fe2)

**Comment by ajeetdsouza** [comment]
I'm not able to reproduce this, it feels like it may be specific to your configuration. Could you try deleting one line at a time and seeing where the offending line is?

**Comment by lagner** [comment]
Hello!

I have the same symptoms. The problem is the following line
```zsh
[[ "${+functions[compdef]}" -ne 0 ]] && compdef __zoxide_z_complete j
```
My terminal says 
```
✓ ~/Projects % compdef
zsh: command not found: compdef
```
However, the tool seems to work even if I just comment out the line

**Comment by ajeetdsouza** [comment]
@lagner that's likely because you haven't called `compinit` in your `.zshrc` before initializing zoxide, which will cause it to initialize without completions.

**Comment by lagner** [comment]
Yes. You are right. I need to do
```bash
autoload -Uz compinit && compinit
```
before the zoxide initialization. But I had an error with permissions. That's why it didn't work.
Thank you.
