### ISSUE TITLE
Zoxide with cd alias breaks fish - 'prevd-or-backward-word' & 'nextd-or-forward-word'

### ISSUE THREAD

**Issue by Shobhit0109** [ajeetdsouza/zoxide#793]
When i have set alias as recommended- 
`zoxide init fish --cmd cd | source`
I can no longer use the bindings i set for them using-
`bind \e. nextd-or-forward-word`
 `bind \e, prevd-or-backward-word`
Installed zoxide using cargo install & zoxide version is 0.9.4.

**Comment by ajeetdsouza** [comment]
> I can no longer use the bindings i set for them

Can you elaborate?

**Comment by Shobhit0109** [comment]
![image](https://github.com/ajeetdsouza/zoxide/assets/97778494/aa2cd54f-9dec-45fd-a6b9-c541bd3f7962)
![image](https://github.com/ajeetdsouza/zoxide/assets/97778494/0bd326cb-447e-4348-8a95-a27a316732b3)

As you can see, these two works with bind in fish.
We can set bindings to traverse directory history but when I use cd as alias for zoxide this feature of fish doen't work.
