### ISSUE TITLE
eval not found

### ISSUE THREAD

**Issue by shrikeit** [ajeetdsouza/zoxide#794]
Hello,

Installed using homebrew, added **eval “$(zoxide init zsh)”** to end of ~/.zshrc file and ran **source ~/.zshrc**, which resulted in the following:

`❯ source ~/.zshrc    
(eval):1: ============================================================================ not found`

`❯ which zoxide
/opt/homebrew/bin/zoxide`

`❯ echo $PATH           
/Users/peter/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin`

Thanks for the help.

**Comment by ajeetdsouza** [comment]
Can you paste the contents of your .zshrc file here?

**Comment by ajeetdsouza** [comment]
What's the output of `zoxide init zsh`?
