### ISSUE TITLE
Unable to install zoxide in arch linux

### ISSUE THREAD

**Issue by sanjyay** [ajeetdsouza/zoxide#795]
After adding 'eval "$(zoxide init zsh)"' to ~/.zshrc . I am using zsh shell btw.
![image](https://github.com/ajeetdsouza/zoxide/assets/102979855/5ec86d77-f92d-415d-ae6f-98a49bf3a47f)
![image](https://github.com/ajeetdsouza/zoxide/assets/102979855/0a5aeb57-60b6-4332-a57d-778a259c70fe)
But i am getting output for zoxide 
![image](https://github.com/ajeetdsouza/zoxide/assets/102979855/ec472b64-559b-4a04-84cd-5305f8d537b5)
but i cannot use z or cd using z

**Comment by ajeetdsouza** [comment]
Does it happen after you restart your shell?

**Comment by sanjyay** [comment]
I uninstalled zoxide and restarted my pc and reinstalled and now zoxide is working .
