### ISSUE TITLE
__zoxide_cd:cd:2: no such file or directory: world!

### ISSUE THREAD

**Issue by BurntNail** [ajeetdsouza/zoxide#810]
Whenever I try to use `cdi` in my terminal, I get this error:
```
__zoxide_cd:cd:2: no such file or directory: world!
```

I use zsh, with the following command in my `.zshrc`:
```sh
eval "$(zoxide init zsh --cmd cd)"
```

Is there a way I can use `cdi`, or `zi` in the default configuration?

**Comment by ajeetdsouza** [comment]
What version of zoxide / zsh is this?

```bash
zoxide --version
zsh --version
```

**Comment by BurntNail** [comment]
Zsh: `zsh 5.9 (x86_64-redhat-linux-gnu)`

This issue seems to affect me on both machines running Fedora 39 & 40 (v0.9.2). 

Also - If I `sudo dnf remove zoxide` and `cargo install --git https://github.com/ajeetdsouza/zoxide/` , I still get the issue.

**Comment by ajeetdsouza** [comment]
This is almost certainly an issue specific to your setup. `cdi` is based on the `zoxide query -i` command, which only outputs absolute paths (so just `world!` should not be possible), and it only outputs directories that exist.

It's hard to debug without having access to your setup. But here's some steps I think you could use to debug this on your own:
- The `cdi` command is an alias of `__zoxide_zi`.
- You can see the source code by running `type -f __zoxide_zi`.
- Once you see the source code, try running it bit by bit manually and see where the `world!` result is coming from.

**Comment by BurntNail** [comment]
Managed to fix it - it was an error with my `fzf` installation. There seems to be a crate called `fzf` that prints `Hello, world!` which I had mistakenly installed and it was overriding my system `fzf`. Sorry!
