### ISSUE TITLE
Installation using shell script is not working in macOS

### ISSUE THREAD

**Issue by pravusid** [ajeetdsouza/zoxide#812]
Installation using shell script requires sudo permission since v2 install script.
After typing the correct password, installation was aborted.
(but ... I also installed it - same shell script - in arch linux and it worked )

- macOS (arm)
- zsh

```zsh
$ curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
Detected architecture: aarch64-apple-darwin
Downloaded package: zoxide.tar.gz
Password: ****
chmod: --: No such file or directory
Error: command failed: try_sudo chmod +x -- /Users/username/.local/bin/zoxide
```

The latest release (v0.9.4) has no problem and it doesn't require sudo permission.

```zsh
$ curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/v0.9.4/install.sh | sh
Detected architecture: aarch64-apple-darwin
Downloaded package: zoxide.tar.gz
Installed zoxide to /Users/usernamelocal/bin
Installed manpages to /Users/username/.local/share/man

zoxide is installed!
```

**Comment by ajeetdsouza** [comment]
Fixed, thanks! https://github.com/ajeetdsouza/zoxide/commit/ae33940331a0e71c5cbf46fd40166d683323b699
