### ISSUE TITLE
aarch64-linux-android not packaged

### ISSUE THREAD

**Issue by Rignchen** [ajeetdsouza/zoxide#813]
Hello, I'm on an Android (Samsung S20 FE) and I use [termux](https://github.com/termux/termux-app) as a terminal.
I've been using zoxide for about 8 months now and I wanted to use it on my phone to but when I did the curl command in the README, I dot an error telling me it isn't packaged

```sh
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
```
```
Detected architecture: aarch64-linux-android    Error: zoxide has not yet been packaged for your architecture (aarch64-linux-android), please file an issue: https://github.com/ajeetdsouza/zoxide/issues
Error: found empty string: package
```

**Comment by ajeetdsouza** [comment]
Thanks for pointing this out, this will be available in the next release. In the meantime, you can install using the Termux package manager:

```sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
```
