### ISSUE TITLE
Feature request: Add directory history support

### ISSUE THREAD

**Issue by jmg-duarte** [ajeetdsouza/zoxide#815]
Hey, thanks for the great project, I was skeptical at first but now I can't live without `zoxide`! 

As for my feature, some context —I keep going back and forth with a mix of `..` and friends, however, sometimes I overshoot or just want to go back to the directory I was in 3 `z`'s back.

Having something like `zhist` that has an `fzf` interface to select one of previous directories would be amazing.

**Comment by ajeetdsouza** [comment]
Is this the same as https://github.com/ajeetdsouza/zoxide/issues/784?

**Comment by jmg-duarte** [comment]
Yes, it seems so, though I don't care for time or frequency, just the order. But it seems to, more or less, solve the same thing.

Apologies for the duplicate!
