### ISSUE TITLE
Feature request: Allow manually specifying high priority paths.

### ISSUE THREAD

**Issue by spthiel** [ajeetdsouza/zoxide#816]
### Goal:
I'd like for there to be a command that allows to permanently set the frequency of any directory to always be higher than all other directories (except directories in the current PWD)

### Explanation:
I have the three directories "foo-main" "foo-test" and "docker-foo" and generally when I use `z foo` I go to "foo-main" because that's the main directory I work in and always want to go there. Sometimes however I spend a few days in docker-foo or foo-test which causes the frequency of these two to increase above foo-main causing `z foo` to go into those instead.

Because I have mentally saved different keywords to explicitly go into foo-test and docker-foo I do not need either of them be accessible with "foo"

**Comment by atharvakadlag** [comment]
You could just easily setup aliases for this. the point of `z` seems to be to guess what directory the user wants to go to without them explicitly mentioning it. so adding manual high priority paths seems redundant.

**Comment by ajeetdsouza** [comment]
Agreed, I think high priority paths are overcomplicating the problem. zoxide should stay out of the way as far as possible - people really don't want to think so much about their `cd` command.
