### ISSUE TITLE
zoxide query -l isn't valid

### ISSUE THREAD

**Issue by fecetrulo** [ajeetdsouza/zoxide#82]
I install `zoxide` via `yay` but command `zoxide query -l` (shown on [intruduction] isn't valid). 
Am i doing something wrong?

![Screenshot from 2020-06-03 14-49-18](https://user-images.githubusercontent.com/18095002/83670302-54dc4800-a5a9-11ea-9134-0d73eca1bb62.png)

**Comment by ajeetdsouza** [comment]
This feature hasn't been released yet. The only way to use it at the moment would be to clone and build the `next` branch from GitHub :smile:

**Comment by fecetrulo** [comment]
@ajeetdsouza thanks for your reply.

**Comment by ajeetdsouza** [comment]
No problem! For how, if you want to list all db entries, you can run `zi`.
