### ISSUE TITLE
zoxide doesn't go to the previous directory

### ISSUE THREAD

**Issue by stephane-archer** [ajeetdsouza/zoxide#820]
zoxide doesn't go to the previous directory:
```
z -
cd: The directory '-' does not exist
```
```
zoxide 0.9.4
```
config.fish
```
if status --is-interactive
        set -x GOPATH (go env GOPATH)
        set -x PATH $PATH (go env GOPATH)/bin
        set fish_cursor_insert line
        starship init fish | source
        function __zoxide_cd_internal
                builtin cd $argv
        end
        zoxide init fish | source
end
```

**Comment by ajeetdsouza** [comment]
Why have you replaced the __zoxide_cd_internal function?

**Comment by stephane-archer** [comment]
@ajeetdsouza because cd is an alias to be disabled to force me to use zoxide, so I need zoxide to use the built-in cd, not the alias.

**Comment by ajeetdsouza** [comment]
`builtin cd` does not support `cd -`. To solve this issue, remove the custom `__zoxide_cd_internal` function, and disable `cd` _after_ you initialize zoxide.

**Comment by stephane-archer** [comment]
@ajeetdsouza 
removing the custom `__zoxide_cd_internal` 
then 
``` 
if status --is-interactive
        zoxide init fish | source
end

function cd
    if status is-interactive
        echo "Use z"
        return 1
    end
    builtin cd $argv
end
``` 
doesn't work for me. I see `Use z`  when using zoxide

**Comment by ajeetdsouza** [comment]
Your version of zoxide is likely out of date. Can you try with the latest version?

**Comment by stephane-archer** [comment]
I use this version
``` 
zoxide 0.9.4
``` 
I think it's the last one?

**Comment by ajeetdsouza** [comment]
Works for me:

<img width="546" alt="image" src="https://github.com/ajeetdsouza/zoxide/assets/1777663/3e92cdf1-f9c3-4800-8361-5c16d778e104">

Can you check if you've set a `cd` alias using `--save` that's getting loaded before zoxide?

**Comment by stephane-archer** [comment]
@ajeetdsouza This works for me now, I still had a `cd` defined in `fish/.config/fish/function/`
it's strange to me that you depend on the current `cd` on the system. Why did you make that choice?
Thank you for the help.

**Comment by ajeetdsouza** [comment]
Unlike most shells, Fish's `builtin cd` does not work with `cd -`, `cd +` etc. Instead, it's defined in a separate function that internally calls `builtin cd`. I believe on one of their GitHub issues they mentioned moving all this logic into the builtin, but that has not been picked up yet.

In other shells, zoxide depends on `builtin cd` (or equivalent) which is useful when users alias `cd` to something else, but on Fish, the only options seem to be:

1. Use `builtin cd` and don't support `cd -` / `cd +` / etc.
2. Copy the original `cd` function verbatim from Fish's repo into zoxide, and use that.
3. Upon startup, copy the `cd` function that is available into `__zoxide_cd_internal`. The condition here is that you must only alias cd _after_ initializing zoxide.

Option 2 will use FIsh's internal variables for tracking the directory stack, but if any of them get renamed in a later Fish version, or if the function uses some newer features of Fish, it will behave differently. For that reason, I picked option 3, but it's causing enough confusion that I'm considering moving to option 2.
