### ISSUE TITLE
Partial match high priority nested path over exact direct descendent (edge-case)

### ISSUE THREAD

**Issue by qgates** [ajeetdsouza/zoxide#825]
In `~` I have 2 folders:

```
~/go
~/dev/srv/api-go
```

The latter is in z's db with a high priority (80+).

- If I type `z go` from anywhere I end up in `~/dev/srv/api-go` (wanted behaviour)
- But when I type `z go` from `~` it takes me to `~/go` (unwanted behaviour)

Can this be fixed without excluding `~/go` entirely? So I could still type `z ./go` or `z ~/go` to get there, but in all other cases `z go`  matches `~/dev/srv/api-go`. 

I'll admit this is an edge case but it's been chafing with me lately. Perhaps a negative score in `zoxide edit` would indicate such directories?

Apologies in advance if I've missed anything obvious 😉

**Comment by ajeetdsouza** [comment]
`z` behaves first like a cd command, and then like a "jump" command. This is so that you don't have to build muscle memory for two commands (should I cd into this directory, or use z?)

The only way to solve this particular case is to use a query that will not match a local directory. Here's some alternatives:

- `z api`
- `z / go`
- `z a go`

**Comment by qgates** [comment]
Thanks for your response. I am aware of the workarounds, but the example I gave is one of many. The issue - for me at least - is that although `z` is designed to replace `cd`, it __isn't__ `cd` on account of its additional fuzzy matching db functionality.

`z` can fuzzy match or exact match, but the behaviour is dependent upon which directory a user is already in. That presents a confused outcome to the user: will `z go` change to an immediate subdirectory called exactly `go` or will it fuzzy match from its database?

What I'm suggesting is to make that semantically clear, or to provide that at least optionally. It makes more sense to me at least. Operands resulting in a physical pathspec behave like `cd` and in all other cases fuzzy matching from the database.

**Comment by ajeetdsouza** [comment]
It's easy enough to implement - zoxide is designed with scriptability in mind. What you're asking for can be achieved with a simple one line function:

```
function z() { cd "$(zoxide query -- "$@")" }
```

**Comment by qgates** [comment]
Wasn't aware of that - thanks. However, that's not quite what I'm looking for. The above only works with parameters that match entries in the db, and doesn't work in situations where I want to do a straight `cd` with a pathspec eg:

`z ./go` or `z /home/user/go`

Sorry to trouble you further, but if straightforward how would I go about achieving that? So if I'm in `~` and I type `z go` it matches from the db, but only does a `cd` when a pathspec is provided ie. `z ./go`?

Appreciate for your help 🙂

**Comment by ajeetdsouza** [comment]
As far as Linux is concerned, `cd foo` is identical to `cd ./foo`. Both are relative paths.

You could certainly write a custom script that only tries to manually `cd` if the directory contains a `/` in it, and falls back to zoxide otherwise - should solve your problem.
