### ISSUE TITLE
zoxide forgets too easily by default

### ISSUE THREAD

**Issue by skorokithakis** [ajeetdsouza/zoxide#83]
I have some directories that I use once a week or so, but zoxide seems to forget about them very easily. I think the default is a bit too conservative, could it be changed to remember many more items, if this wouldn't slow things down much?

**Comment by ajeetdsouza** [comment]
I've been using zoxide with `_ZO_MAXAGE=10000`. I've never once seen it stutter, and it has only gotten faster since. I think I'll set the default to 10000 in future releases.

**Comment by skorokithakis** [comment]
That would be quite great, thank you.
