### ISSUE TITLE
Interactive completions when using powershell

### ISSUE THREAD

**Issue by tommdq** [ajeetdsouza/zoxide#837]
Hey! I've been using zoxide for a while in windows with powershell. 
I recently discovered zoxide has a interactive completion when pression space + tab but  this is not working for me, instead I get completion based on CWD. 
I don't know if this is a copy of https://github.com/ajeetdsouza/zoxide/issues/344 or if it's a missconfiguration of powershell, but I've tried a few things like remapping tab in user_profile config but with no results.

This is what i get after pressing space+tab instead of fzf competion.
![image](https://github.com/ajeetdsouza/zoxide/assets/80493479/6c8b33af-f289-4d74-9262-248dd1283554)

But if y use zi i get the fzf completion 
![image](https://github.com/ajeetdsouza/zoxide/assets/80493479/41455aa4-5904-4954-afb6-0e881e8ba37b)

**Comment by ajeetdsouza** [comment]
The README does mention that interactive completions are only supported on 3 shells:

> ```sh
> z foo<SPACE><TAB>  # show interactive completions (zoxide v0.8.0+, bash 4.4+/fish/zsh only)
> ```

I haven't found the time to add interactive completions for PowerShell, but if you'd like to submit a PR for it, I'd be more than happy to help.
