### ISSUE TITLE
error: unrecognized subcommand 'Documents'

### ISSUE THREAD

**Issue by dehlong** [ajeetdsouza/zoxide#838]
Hello,
I have installed zoxide but it does not want to change to any directory.
When I run:
/usr/bin/zoxide Documents, it does not change path, just errors out. Documents folder exists, though.
![image](https://github.com/ajeetdsouza/zoxide/assets/112163027/d813842b-d287-4eb3-9f73-146b7add5569)

**Comment by dehlong** [comment]
It also does not do anything mentioned in the README.md.
I tried running: zoxide init --cmd cd Documents
But I again got an error
![image](https://github.com/ajeetdsouza/zoxide/assets/112163027/11488113-4d63-476a-9ccb-bcd55d7a5b5e)

Is it still

**Comment by ajeetdsouza** [comment]
Please go through the [README](https://github.com/ajeetdsouza/zoxide) again.

**Comment by mhdalmajid** [comment]
I faced the same issue, just close and open the terminal it will. Solve the issue 

It is worth adding it to the readme file

I can add if you agree on @ajeetdsouza
