### ISSUE TITLE
[Bug Report]: No directory history in the database, check out the `zoxide` docs to set it

### ISSUE THREAD

**Issue by hsuyelin** [ajeetdsouza/zoxide#845]
### zoxide doesn't work in yazi
<img width="1432" alt="image" src="https://github.com/ajeetdsouza/zoxide/assets/17918063/8c9c953e-647a-4a9f-8e28-dc45e2a9b2f5">

### zoxide version && system arch/version
<img width="1448" alt="image" src="https://github.com/ajeetdsouza/zoxide/assets/17918063/bad422f5-809f-46d9-ac28-a6dbed4b4008">

### zoxide did work in zsh
<img width="1458" alt="image" src="https://github.com/ajeetdsouza/zoxide/assets/17918063/1e7a386f-7505-4a4e-83af-d1ab4b80f5c8">

could u give me some suggestions to fix it ? thx

**Comment by ajeetdsouza** [comment]
If zoxide is working normally in zsh but not in yazi, you may want to raise it on the yazi repo.

**Comment by linusr** [comment]
I faced the same issue with Yazi + zoxide and search took me to this issue.
Not sure if @hsuyelin managed to get this fixed.

What fixed this for me was to set $SHELL to match with shell being used, likely when login shell is not used.
I was using nushell instead of default zsh.

**Comment by fortes** [comment]
In case others are hitting this, it may be because you're running Debian Bookworm which has an ancient version of `zoxide` (0.4.3) that doesn't support the `--exclude` flag.

Installing the latest (0.9.7) resolved things for me

**Comment by igortas** [comment]
Not working on arch.

**Comment by gabx** [comment]
I have same issue with zoxide inside yazzi on arch linux.

**Comment by mohammadazeemwani** [comment]
Same issue on macOS
```bash
╰─➤  sw_vers
ProductName:            macOS
ProductVersion:         26.2
BuildVersion:           25C56
```

Any update ?

**Comment by mohammadazeemwani** [comment]
I have it working now; 
I thought it is something that will work out of the box. 

I did the [initialization](https://github.com/ajeetdsouza/zoxide#:~:text=Add%20this%20to%20the%20end%20of%20your%20config%20file%20(usually%20~/.zshrc,to%20rebuild%20your%20completions%20cache%20by%20running%20rm%20~/.zcompdump*%3B%20compinit.), now everything is working. 

And you need to run zoxide outside of yazi too. to that it creates some history and then you can use it flawlessly.
