### ISSUE TITLE
`zi` doesn't work

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ajeetdsouza/zoxide#846]
When I call `zi`, it always echoes `zoxide: no match found`.

Versions:
- zsh 5.9 (x86_64-apple-darwin23.0)
- zoxide 0.9.4 (installed via brew)
- fzf 0.53.0 (installed via brew)

**Comment by ajeetdsouza** [comment]
Have you installed zoxide recently?

**Comment by Shaharyar-developer** [comment]
Same Issue (version 0.9.4), Tried installing via pacman, paru and install script, added the eval script to .zshrc, even tried to manually override the envs. zoxide query does not maintain any state, `zoxide query` only shows current working directory.
```bash
cd .config
zoxide query
# returns  /home/shaharyar/.config
cd ~
zoxide query
returns zoxide: no match found
```

**Comment by MaximilianAnzinger** [comment]
Oh i see, so `no match found` doesn't mean my setup with fzf is incorrect but rather that there is no reasonable response yet. I was just trying to verify my install.

Thx 👍
