### ISSUE TITLE
`zoxide` does not work

### ISSUE THREAD

**Issue by Shaharyar-developer** [ajeetdsouza/zoxide#847]
### Zoxide does not work.
The database does not maintain any data.
I tried manually overriding the env `_ZO_DATA_DIR` variable, this did infact change where the db.zo file is *sometimes* present
running zi simply returns `no match found` regardless of where its run

**Comment by ajeetdsouza** [comment]
What shell / OS are you using zoxide on? Have you added the init line to the _end_ of your config as mentioned in the README?

> this did infact change where the db.zo file is sometimes present

What does this mean? Does the file disappear after it has been created once?

**Comment by Shaharyar-developer** [comment]
Nvm. That was just me being extremely sleep deprived and incognizant. Instead of setting the alias as `alias cd="z"` I set it to `alias z="cd"`. The same goes for the file disappearing, I didn't provide an absolute path to the `_ZO_DATA_DIR` env var

**Comment by ajeetdsouza** [comment]
> The same goes for the file disappearing, I didn't provide an absolute path to the _ZO_DATA_DIR env var

zoxide will produce a warning next time: https://github.com/ajeetdsouza/zoxide/commit/b881866216d53239d0337feac4e19008f9a7f340
