### ISSUE TITLE
Add support for bash autocd option

### ISSUE THREAD

**Issue by PhoenixmitX** [ajeetdsouza/zoxide#850]
If you use the `bash` autocd option, it will execute the `cd -- path/to/dir` command.
Zoxide is not able to handle this, meaning that it is unable to find a match.

There is also a PR (#695) to fix this.
The PR has two lines of code added to it, is over 4 months old, and has received no attention from the maintainers.

Since issues seem to get more attention, I hope this will get the maintainers' attention.

More information can be found in #695.

**Comment by ajeetdsouza** [comment]
Merged.
