### ISSUE TITLE
Support regexp

### ISSUE THREAD

**Issue by ruirlliu** [ajeetdsouza/zoxide#851]
Thanks for your work on this tool, it's very useful to switch folders for me.

However, I found zoxide doesn't support regexp ( didn't find in the wiki ), if there are some folders with similar name, zoxide may jumps into the wrong folder.

For instance, 
```sh
z ~/a/b/c
z ~/a/b/c1
z ~/a/b/c2

# cd to the folder c
z  c
# jumped into wrong folder
~/a/b/c1
```
If zoxide supports regexp, it's easy to jump into a specific folder, such as:
```sh
# cd to a folder ends with c
z c$

~/a/b/c
```

More info: 
- system: `ubuntu 22.04`
- zoxide version: `zoxide 0.9.4`
- fzf version: `0.53.0 (brew)`

**Comment by ajeetdsouza** [comment]
I don't think regex is the correct solution here.

- regex is designed to be precise, but is hard (and slow) to write. Moreover, you'd have to manually escape characters - both for regex and for your shell.
- zoxide's query language may be imprecise and get 1% of queries wrong, but as a result it's much faster to write queries and it's a lot quicker to think up a query when working in your shell.

Implementing regex in zoxide would be one library import away, and regex is a fantastic tool - but IMHO it's the wrong tool for the job. That said, if you still want functionality like this, zoxide is designed to be scriptable - you should be able to set up something with `zoxide query --all` and `grep`.
