### ISSUE TITLE
Using --cmd cd in Fish Shell does not work

### ISSUE THREAD

**Issue by EvilsSouls** [ajeetdsouza/zoxide#856]
I wanted to switch from cd to zoxide. So that I could keep my muscle memory I wanted to also replace the z (and zi) command with cd. Thus instead of just adding `zoxide init fish | source` I changed it to `zoxide init --cmd cd fish | source`. I restarted my terminal and first checked if the command `z` is still a thing. Sure enough it wasn't. Then I used cd, however instead of it just behaving as the original `z` command it gave this error:
![image](https://github.com/user-attachments/assets/3003fa89-dec2-4e75-ad13-a75d49b900f7)

Removing the `--cmd cd` from the config.fish file fixes it again.

PS: If it wasn't obvious already I'm using fish as my shell

**Comment by EvilsSouls** [comment]
If it helps, I also first tried just doing `zoxide init --cmd cd` from the terminal (after I had added it to the config.fish file), because I wasn't sure where to actually do the command, so that might be the root of the problem. (Even though I don't actually think so, because the command just spat out what it would normally do inside the actual `config.fish` file.)

**Comment by ajeetdsouza** [comment]
What version of zoxide are you running?

```
zoxide -V
```

**Comment by EvilsSouls** [comment]
> What version of zoxide are you running?
> 
> ```
> zoxide -V
> ```
`zoxide v0.4.3-unknown`. I installed it yesterday through apt.

**Comment by EvilsSouls** [comment]
> > What version of zoxide are you running?
> > 
> > ```
> > zoxide -V
> > ```
> `zoxide v0.4.3-unknown`. I installed it yesterday through apt.

I just actually read through the README and realized, that it said not to use apt. I guess I'll use the install script. Thank you!

**Comment by esn89** [comment]
I am getting a similar issue actually.  I installed it via macports.

The `zoxide init --cmd cd | source` does nothing in `~/.config/fish/config.fish`.

`cd` is still pointing to the `/usr/bin/cd`.

**Comment by ajeetdsouza** [comment]
@esn89 the output of `which cd` is always `/usr/bin/cd` because `which` does not lookup shell functions. If you're having any issue actually using zoxide, please create a fresh issue.
