### ISSUE TITLE
Symlinks unable to resolve

### ISSUE THREAD

**Issue by elmoteroloco** [ajeetdsouza/zoxide#860]
I have my `Temp` folders on a `RAM disk` via symbolic link and Zoxide just won't install (`An unexpected error occurred while running the command: weakly_canonical: unknown error: "R:\Temp\WinGet\ajeetdsouza.zoxide.0.9 .4\extracted\zoxide.exe"`)

I found a problem that I assume is related ("Zoxide crashes when the database has symbolic links #628") and that I left commented.

(This being my first 'issue' on GitHub I prefer some redundancy by adding this throwaway, since, due to the differences between the cases, I am not quite sure of the correct way to handle it. I apologize in advance, thank you.)

**Comment by ajeetdsouza** [comment]
Seems to be an issue with winget rather than zoxide, I'd suggest reporting it on https://github.com/microsoft/winget-pkgs.
