### ISSUE TITLE
[Feature Request] Confirmation for changing location, when file with same name is found

### ISSUE THREAD

**Issue by EvilsSouls** [ajeetdsouza/zoxide#861]
I often find myself thinking that a file is a folder and thus cding to it. However instead of it giving me an error (like what cd would do) zoxide just changes to any directory that resembles it. I suggest having an option to enable or disable a confirmation when changing location, if a file with the same name as the prompt is found. For example, if you'd be in a folder containing a file called "config" you might think that it is a folder. Then you z into it, not realizing that it was actually just a file and that now you're in your `~/.config` folder. With the option enabled, it would first prompt you if you are sure you want to change directory (but only when there is actually a file inside the current folder with the same name as the folder you're trying to switch to).

**Comment by ajeetdsouza** [comment]
I don't think this would be a particularly good idea for zoxide - the point of an autojumper is to be fast to work with, and a confirmation dialog seems to be a step in the wrong direction. I'd even take an error such as `zoxide: that's a file, not a directory` over a confirmation dialog.

Unless there's more interest in this issue, I don't think I'm adding it to zoxide itself, but it should be extremely easy to write a small wrapper function to make this work. zoxide is intended to be tweaked via basic scripting - you can initialize it without `z` (`zoxide init zsh --no-cmd`) and then wrap `__zoxide_z` (that's the `z` command) with whatever logic you'd like.
