### ISSUE TITLE
[BUG] zoxide no match found loop

### ISSUE THREAD

**Issue by Sanix-Darker** [ajeetdsouza/zoxide#862]
When a match is not found, looks like zoxide loop on error "no match found"...
```bash
$ zoxide --version
zoxide 0.9.4
```
```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
```
![ddd](https://github.com/user-attachments/assets/93b9d8ea-b36d-45c8-9952-ec2b78af8703)

**Comment by ajeetdsouza** [comment]
Something in your configuration seems to be calling zoxide in a loop. Have you followed the instructions in the README and initialized zoxide at the end of your config?
