### ISSUE TITLE
Add configurable location to "go home" to

### ISSUE THREAD

**Issue by mars-monkey** [ajeetdsouza/zoxide#869]
I want to be able to configure the directory to which I am sent when I type
```
z
```
I don't want to change `$HOME` because I am trying to separate my dotfiles and my actual data.

**Comment by ajeetdsouza** [comment]
`z` is an alias of `__zoxide_z`. The intention of creating `__zoxide_z` is exactly for this kind of custom use case - you can simply write a shell function `z` that goes to your chosen directory if there are no arguments, and falls back to `__zoxide_z` otherwise.
