### ISSUE TITLE
Z alias conflict with Zypper on OpenSuse

### ISSUE THREAD

**Issue by jpringle1** [ajeetdsouza/zoxide#871]
In OpenSuse Tumbleweed, "z" is already aliased to Zypper, the package manager. Even after adding `eval "$(zoxide init zsh)"` to the very end of my .zshrc file, the alias doesn't update with zoxides intended command.

What command can i use to override this manually? Naturally, i tried aliasing it to just "zoxide" but that just shows the help dialog. What command is z supposed to be assigned to?

**Comment by ajeetdsouza** [comment]
`alias z = __zoxide_z`

Strange that you're still seeing the Zypper alias. Perhaps `set -x` after your `zoxide init` statement will reveal the culprit?
