### ISSUE TITLE
on bash, not able to initialize zoxide with inline eval

### ISSUE THREAD

**Issue by aster-void** [ajeetdsouza/zoxide#875]
## Problem

```bash
eval $(zoxide init bash)
```
doesn't work.

but this
```bash
zoxide init bash > .zoxiderc
source .zoxiderc
```
works.

please consider updating README to the latter. 

## OS / Version

OS: Linux/NixOS on nixos/unstable + home-manager/master
bash: GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
zoxide: zoxide 0.9.4

**Comment by ajeetdsouza** [comment]
There should be no difference between eval and source as far as I'm aware, something else in your shell may be messing with zoxide. Are you calling zoxide at the **end** of your config file as specified in the README?

The issue with your method is that if the zoxide binary updates, the script it generates may change, but your system would still be running the old one, which may introduce some unexpected behavior.
