### ISSUE TITLE
Zoxide is not learning ?

### ISSUE THREAD

**Issue by avario-cpu** [ajeetdsouza/zoxide#877]
Am I doing somethig wrong ?

https://github.com/user-attachments/assets/47747f9c-4762-4990-b81b-d09cb3a3a1ae

**Comment by avario-cpu** [comment]
Had not put
`Invoke-Expression (& { (zoxide init powershell | Out-String) })`
At the bottom of the file.
Since starship requires
`Invoke-Expression (&starship init powershell)`
To be at the bottom as well. 

So priority seems to be zoxide > starship. Starship still works this way

**Comment by ajeetdsouza** [comment]
Yup, zoxide can play nicely with other programs when it's last, but other programs may override zoxide's config when they're initialized after. Unfortunately, there isn't much we can do about that.

**Comment by rijulkap** [comment]
Ran into this issue as well. Can't seem to get zoxide to learn newer directories after installing starship. Tried the recommended fix, but to no avail. My current powershell profile looks as follows:


```
Invoke-Expression (&starship init powershell)

$prompt =""
function Invoke-Starship-PreCommand {
    $current_location = $executionContext.SessionState.Path.CurrentLocation
    if ($current_location.Provider.Name -eq "FileSystem") {
        $ansi_escape = [char]27
        $provider_path = $current_location.ProviderPath -replace "\\", "/"
        $prompt = "$ansi_escape]7;file://${env:COMPUTERNAME}/${provider_path}$ansi_escape\"
    }
    $host.ui.Write($prompt)
}

Invoke-Expression (& { (zoxide init powershell | Out-String) })
```

Removing the middle code block (required by wezterm) does not help. Shuffling the init order or using a different terminal does not help either. The only way to get zoxide to add directories once again is getting rid of the starship init command completely. Any suggestions at all?

**Comment by ajeetdsouza** [comment]
Please create a fresh issue.
