### ISSUE TITLE
Support for my phone's architecture

### ISSUE THREAD

**Issue by RyanBaig** [ajeetdsouza/zoxide#878]
Tried installing zoxide on Termux on my Oppo A37fw (Android 5) and it said this:
```
Detected architecture: aarch64-linux-android
Error: zoxide has not yet been packaged for your architecture (aarch64-linux-android), please file an issue: https://github.com/ajeetdsouza/zoxide/issues
Error: found empty string: package
```

Please help me with this.

**Comment by ajeetdsouza** [comment]
Why not `pkg install zoxide`?

**Comment by ajeetdsouza** [comment]
Why not `pkg install zoxide`?

**Comment by RyanBaig** [comment]
Didnt work since that package isn't included in my version of termux (android 5&6 versions don't include latest packages)

**Comment by RyanBaig** [comment]
Hello?

**Comment by ajeetdsouza** [comment]
This has already been merged, the binary will be available after the next release of zoxide.

https://github.com/ajeetdsouza/zoxide/pull/814
