### ISSUE TITLE
"zi" with fzf

### ISSUE THREAD

**Issue by ragokan** [ajeetdsouza/zoxide#884]
Does "zi" command only works for the previously visited folders? With fzf, I can do search for folders but when I do "zi lib", I get this output:

```
 ❯ zi lib            
zoxide: no match found
```

But if I do "fzf" and then type "lib", I get results that I want to see. Is there any way to populate zoxide with fzf?

**Comment by ajeetdsouza** [comment]
Nope. The reason zoxide works so well is that it has a very small search space, so it almost always gets the query correct. Populating zoxide with fzf entries would defeat the purpose.

**Comment by ragokan** [comment]
Got it, thanks for your fast answer @ajeetdsouza
