### ISSUE TITLE
Where can I find the prompt in `demo.gif`?

### ISSUE THREAD

**Issue by rrthomas** [ajeetdsouza/zoxide#89]
Sorry to post this as an issue! When I landed on zoxide, I was immediately struck by the bash prompt in `demo.gif`, with its excellent use of color and the right margin. After extensive searching, I can't find how it's done (well, not without learning all the terminal magic from first principles—I already understand customizing bash prompts!). Could you possibly add a note saying where it comes from? I guess it could be `bash-it`? But that has no visual directory that I can find, nor does searching its theme descriptions give me much of an idea. Thanks in advance, and thanks for zoxide!

**Comment by rrthomas** [comment]
Hmm, further investigation suggests this may be a powerline thing?

**Comment by ajeetdsouza** [comment]
Hey @rrthomas,

I've updated my [dotfiles](https://github.com/ajeetdsouza/dotfiles) so you can replicate my exact configuration.

I'm using the UbuntuMono [Nerd Font](https://github.com/ryanoasis/nerd-fonts), the [powerlevel10k](https://github.com/romkatv/powerlevel10k) prompt, and the [base16-onedark](https://github.com/chriskempson/base16-shell) color scheme, except I've manually changed the background color to black.

I'm closing this issue, but feel free to ask me if you have any further questions!

**Comment by rrthomas** [comment]
Wow, thanks so much @ajeetdsouza, especially for kindly responding to an issue that isn't really about your code at all.
