### ISSUE TITLE
z! stopped working

### ISSUE THREAD

**Issue by antoyo** [ajeetdsouza/zoxide#893]
Hi.
Since a few days, I noticed that using `z!` stopped working.
When I try to use it as in:
```
z some_folder z!/home/user/path/some_folder
```
it says:
```
zoxide: no match found
```
even thought the absolute path exists and I can `cd` to it.

(`z some_folder` will still work; it's when adding the `z!` argument that it fails)

I use zoxide 0.9.6 on ArchLinux with the `fish` shell.

Thanks to fix this issue.

**Comment by ajeetdsouza** [comment]
It seems like your init script is outdated. Are you initializing zoxide as `zoxide init fish | source`?

`z!` is no longer required, as zoxide's Fish autocompletion is now able to change the directory on its own.

**Comment by antoyo** [comment]
I have `zoxide init fish | source` in my `~/.config/fish/config.fish`.

What do you mean by it's no longer required?

I don't remember why I started using `z!` in the first place. Was it because the `fzf` completion wouldn't work?
Now it does seem to work. Is this what you mean?

**Comment by ajeetdsouza** [comment]
> I don't remember why I started using z! in the first place.

Are you manually typing in `z!` with some directory name? If yes, why?

**Comment by antoyo** [comment]
That's what I don't remember exactly: I type it manually to go to another directory than the first one chosen by zoxide.

Perhaps there was a bug in the past that stopped me to use the autocompletion to choose a different directory. Is this possible?

**Comment by antoyo** [comment]
If I would type:
```
z some_directory
```
it will go, let's say, to:
```
/tmp/some_directory
```

I use `z!` to go to another directory, directly, for instance `/usr/some_directory`.

In any case, I guess I do not need to use `z!` anymore since the autocomplete now works, which is the likely reason for why I needed to use `z!` in the first place.

Just, so I understand, `z!` is not supported anymore?

**Comment by ajeetdsouza** [comment]
> I use `z!` to go to another directory, directly, for instance `/usr/some_directory`.

Why not just use `z /usr/some_directory`?

> Just, so I understand, `z!` is not supported anymore?

Correct. `z!` has been superceded by a much better completion function - which will jump to the directory you choose rather than having you press Return twice.

**Comment by antoyo** [comment]
> Why not just use `z /usr/some_directory`?

At that time, I used `fish`'s autocompletion, so I didn't have to type the whole thing.
Thanks for fixing the issue with the completion!
