### ISSUE TITLE
Using PowerShell defaults, should directories ALWAYS be added to database even when using regular `cd`?

### ISSUE THREAD

**Issue by GitMurf** [ajeetdsouza/zoxide#901]
I may have misunderstood the expected behavior of zoxide, but is a regular `cd PATH` in powershell supposed to add to the zoxide database? or is it only supposed to add/increment when I do `z PATH`?

For some reason I thought the expectation was if you stuck to the defaults and did NOT set `cd` to use `z` alias, then when using `cd` nothing would happen at all and only things are added to the database when using `z` or `zoxide add` explicitly? What is the correct expected behavior?

Thanks!

**Comment by ajeetdsouza** [comment]
`cd` and `z` both add entries to the database.
