### ISSUE TITLE
[Enhancement] Work with environment variables

### ISSUE THREAD

**Issue by WiIIiamWei** [ajeetdsouza/zoxide#906]
I use Windows PowerShell and I tried this (I aliased zoxide to `cd` properly):
```
PS C:\Users\William> cd %temp%
zoxide: no match found
```
Which is expected to be:
```
C:\Users\William\AppData\Local\Temp
```
It would be nice if zoxide could work with these, I believe so called, "enviroment variables".

Could be the similar case of #855.

**Comment by rajiknows** [comment]
we can change the poershell.txt function for __zoxide_cd  
we will check if the path is present in env , if it does than we will set the dir to that path .

**Comment by ajeetdsouza** [comment]
I'm not a Windows user, but isn't `%temp%` the syntax of `CMD.EXE`? I'm not sure I've followed the use case here.

**Comment by WiIIiamWei** [comment]
> I'm not a Windows user, but isn't `%temp%` the syntax of `CMD.EXE`? I'm not sure I've followed the use case here.

Actually yes, blame me for not properly testing this. I only tried this on `cmd` because I don't want to touch my PowerShell profile to disable zoxide, and thought the same syntax would work for PowerShell. However I think it's still a small cool feature if it would work the same in PowerShell.

**Comment by ajeetdsouza** [comment]
I think that would be confusing for many users, I'd suggest wrapping the `z` command in your shell if you'd like this feature.
