### ISSUE TITLE
Doesn't work with fzf's --bind one:accept (auto-select on unique entry)

### ISSUE THREAD

**Issue by rieje** [ajeetdsouza/zoxide#908]
fzf's `--bind one:accept` auto-selects entry when there's only one match (run `echo 'a' | fzf --bind one:accept` and it won't show the interactive prompt). It doesn't seem to have any effect--launching `__zoxide_zi` and inputting a '`downloads`' when '`downloads`' is a unique entry, it doesn't get auto-selected despite being the only match. Same goes with `--zoxide_zi downloads`--fzf displays only one match but it doesn't get auto-selected.

    _ZO_FZF_OPTS='--bind one:accept'
    eval "$(zoxide init --no-cmd zsh)"
    alias z='__zoxide_zi'

**Comment by ajeetdsouza** [comment]
Try `--select-1` instead.

**Comment by rieje** [comment]
Same behavior.

    _ZO_FZF_OPTS='--select-1'
    eval "$(zoxide init --no-cmd zsh)"
    alias z='__zoxide_zi'

**Comment by ajeetdsouza** [comment]
> ```zsh
> _ZO_FZF_OPTS='--select-1'
> ```

You're setting a shell variable. The syntax for setting environment variables is different:

```zsh
export _ZO_FZF_OPTS='--select-1'
```
