### ISSUE TITLE
Feat: `z path/to/file` cds into `path/to`

### ISSUE THREAD

**Issue by jficz** [ajeetdsouza/zoxide#922]
I enjoyed this behavior with zsh, not exactly sure what the exact config or plugins were but when one did

```
cd path/to/file
```
the directory was changed to `path/to`

Useful with other autocomplete/search features where you look for a file and need to cd to the directory that contains the file fast.

**Comment by ajeetdsouza** [comment]
If you need custom functionality, you can wrap the `__zoxide_z` function to do what you want.

For example:

```sh
eval "$(zoxide init zsh --no-cmd)" # initialize without `z` command

function z() {
  if test -f "$1"; then
    cd "$(dirname "$1")"
  else
    __zoxide_z "$@"
  fi
}
```
