### ISSUE TITLE
checking zoxide was initialised - `zoxide status` or env variable!?

### ISSUE THREAD

**Issue by ocehugo** [ajeetdsouza/zoxide#923]
Hi, I would like to look before initialising zoxide.

It would be great if, instead of checking the existence of the "z" function, I could ask zoxide itself (`zoxide status`), or to rely upon a default environmental variable (e.g. `ZO_INIT=yes`). 

Reasons: a. initialise once , b. make this the same task check for different shells.

I wonder what the author's preference is here.

**Comment by ajeetdsouza** [comment]
You can check for the existence of the `__zoxide_z` function. This function is always created upon initialization so that people can alias it / wrap it as per their preferences, and it has the same name across all shells.
