### ISSUE TITLE
unrecognized subcommand 'Documents' when using zoxide to change directories

### ISSUE THREAD

**Issue by dfalling** [ajeetdsouza/zoxide#927]
I installed zoxide and fzf via homebrew on macOS 15.0.1 (24A348), and am setting up both in my `.zshrc` config:
```zsh
export PATH="/opt/homebrew/bin:$PATH"

autoload -Uz compinit
compinit

source <(fzf --zsh)

alias z=zoxide
eval "$(zoxide init zsh)"
```

When I try to use zoxide to change directories, I get an `unrecognized subcommand` error. Are there any logs or troubleshooting steps I can check to see why the standard setup isn't working for me?

```zsh
❯ z Documents
error: unrecognized subcommand 'Documents'

Usage: zoxide <COMMAND>

For more information, try '--help'.
```

Thanks!

**Comment by ajeetdsouza** [comment]
Remove `alias z=zoxide`, that's not necessary.
