### ISSUE TITLE
What is the value of _ZO_MAXAGE? Minutes, hours, etc.?

### ISSUE THREAD

**Issue by ejuarezg** [ajeetdsouza/zoxide#93]

**Comment by ajeetdsouza** [comment]
The name MAXAGE is a bit misleading IMO, it was named that way to be consistent with similar tools.

zoxide gives you the option of defining one of 2 hooks:
- prompt: updates the database with the current directory every time a terminal prompt occurs
- pwd: updates the database every time the current directory is changed

Every database update increases the "score" of a directory. The total score of all the directories is not allowed to exceed _ZO_MAXAGE, which limits the total number of entries in the database.

Hope this resolves your query! I'm closing the issue, but feel free to ask if you need any further clarifications.

**Comment by ejuarezg** [comment]
Thank you for the explanation. I'm left with final question though. What is the default value for _ZO_MAXAGE?

It would also be nice if a short description of _ZO_MAXAGE actually was added to the README along with the default value. Regardless, thanks.

**Comment by ajeetdsouza** [comment]
> What is the default value for _ZO_MAXAGE?

If _ZO_MAXAGE isn't set explicitly, it defaults to `10000`.

> It would also be nice if a short description of what _ZO_MAXAGE actually does was added to the README along with its default value.

Noted, I will do that!

**Comment by ejuarezg** [comment]
Thanks for your help.
