### ISSUE TITLE
Forcibly add entries to database via environment variable _ZO_INCLUDE_DIRS

### ISSUE THREAD

**Issue by rraafays** [ajeetdsouza/zoxide#930]
I have a huge music library stored in `~/Music/`
Currently I can do `z prince` which takes me to `~/Music/prince_and_the_revolution`
Obviously this is because I have manually visited this dir in the past
But there are thousands of folders under `~/Music/*`

Basically I would love the ability to forcibly index or include directories via globbing
I imagine this would require a new environment variable as shown in the title and then a way to forcibly update the database whilst including the results of the glob at top priority.

**Comment by ajeetdsouza** [comment]
You can use `zoxide add` to add directories manually. However, I'd advise against this, since polluting your zoxide directory will lower the quality of the matches you get. For the same reason, I don't think this would be a good feature to add to zoxide.
