### ISSUE TITLE
nushell(0.99.1) can't load zoxide

### ISSUE THREAD

**Issue by seocamo** [ajeetdsouza/zoxide#934]
i am trying out nushell on arch linux(btw), and the file zoxide make with the init command start with a if and that is not allow
only def, const, extern, alias, use, module, export or export-env is allow

so i think it need to wrap in a module or something.
```
Error: nu::parser::expected_keyword

  × Expected keyword.
    ╭─[~/.cache/zoxide/zoxide.nu:9:1]
  8 │ # Initialize hook to add new entries to the database.
  9 │ if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
    · ─┬
    ·  ╰── expected def, const, extern, alias, use, module, export or export-env keyword
 10 │   $env.__zoxide_hooked = true
    ╰────
```

**Comment by ajeetdsouza** [comment]
Have you followed the initialization instructions in the README exactly, or have you changed something there?

**Comment by seocamo** [comment]
ohh i try to delete what i added and retype it.
and i typed ```use``` and not ```source``` sorry it is my bad
