### ISSUE TITLE
Add config file support, e.g. ~/.config/zoxide/config.json

### ISSUE THREAD

**Issue by milnak** [ajeetdsouza/zoxide#935]
Not a fan of cluttering up environment variables for configuration.

Can you add config file support for these environment variables:

* _ZO_DATA_DIR          Path for zoxide data files
* _ZO_ECHO              Print the matched directory before navigating to it when set to 1
* _ZO_EXCLUDE_DIRS      List of directory globs to be excluded
* _ZO_FZF_OPTS          Custom flags to pass to fzf
* _ZO_MAXAGE            Maximum total age after which entries start getting deleted
* _ZO_RESOLVE_SYMLINKS  Resolve symlinks when storing paths

**Comment by ajeetdsouza** [comment]
Sorry, this is not a planned feature. This was discussed in a previous issue, the consensus was that it's overkill for a cd command to have to check both a config file and env variables before starting up.

**Comment by jollySleeper** [comment]
Hi @ajeetdsouza, 

Sorry for commenting on a closed issue and sorry for not checking out the old issue which you are referring to.

But are you saying that each time when zoxide runs it checks for Env Variables?
Also, I resonate with @milnak here. It's easy to manage different settings for zoxide in its own config folder.

Thank you for this awesome project.
