### ISSUE TITLE
_ZO_EXCLUDE_DIRS doesn't work ?

### ISSUE THREAD

**Issue by ilan-schemoul** [ajeetdsouza/zoxide#938]
zoxide query --all -ls do not contain mmsx-3

```bash
dev ⟩ echo $_ZO_EXCLUDE_DIRS
/home/ilan/dev/mmsx-*
dev ⟩ zoxide --version
zoxide 0.9.6
dev ⟩ cd ~/dev/mmsx-3
```

zoxide query --all -ls contains mmsx-3
_ZO_EXCLUDE_DIRS is ignored

```fish
zoxide init fish | source
```

**Comment by ajeetdsouza** [comment]
How are you setting _ZO_EXCLUDE_DIRS?

**Comment by ilan-schemoul** [comment]
in my config.fish
`set _ZO_EXCLUDE_DIRS "/home/ilan/dev/mmsx-*"`
then later in the same file
`zoxide init fish | source`
