### ISSUE TITLE
Not adding folders on regular cd usage

### ISSUE THREAD

**Issue by manuqs33** [ajeetdsouza/zoxide#941]
I've installed zoxide  as an apt package on a fresh ubuntu install, version 0.9.3, in Bash. 
I have the required:

`eval "$(zoxide init bash)"`

In the .bashrc. 
The question is the history is not building correctly on its own. An example:

![image](https://github.com/user-attachments/assets/e8040b0d-e9e0-4e9f-b70c-701cb0970be4)

I can add a directory manually with zoxide add, but it's very inconvenient, kind of messes up the main strength of the tool. 

Any help will be much appreciated, thanks in advance

**Comment by ajeetdsouza** [comment]
Have you added the line at the end of your bashrc as mentioned in the README?

**Comment by manuqs33** [comment]
Sorry I had another script that was silently modifying the PROMPT_COMMAND variable below the zoxide initialization script. Kind of dumb but at least the issue may be useful for someone having the same problem.

Thanks for zoxide! Amazing tool, I use it every day.
