### ISSUE TITLE
Issues with fancy name resolution on windows

### ISSUE THREAD

**Issue by SturdyFool10** [ajeetdsouza/zoxide#957]
it seems that zioxide on my machine isn't updating the database every time I use it to change directories with the terminal, it looks like it only touched the database when I do z add <dir> or z query <dir>, am I doing something wrong?

**Comment by SturdyFool10** [comment]
my hook flag is the default, which the docs say messes with the db every time I use it to change dirs, but that seems to not be the case, so I tried setting it explicitly, which didn't change the results

**Comment by ajeetdsouza** [comment]
Have you added zoxide to the **end** of your powershell config, as mentioned in the README?

**Comment by SturdyFool10** [comment]
it worked after changing the order such that zoxide init is the last call in the powershell profile, still don't know why that changes anything though...

**Comment by ajeetdsouza** [comment]
Because your powershell prompt very likely overwrites zoxide's hook.
