### ISSUE TITLE
What is the format of the db.zo file?

### ISSUE THREAD

**Issue by code-IM-perfect** [ajeetdsouza/zoxide#961]
Hi I'm sorry this is not an issue, but I want to integrate zoxide into my c++ application.

I am not very experienced in rust and am struggling to find how zoxide stores info in the db.zo file. Can you please explain this to me or direct me to some resource for understanding how it reads and writes to the file.

**Comment by ajeetdsouza** [comment]
Could you tell me about what exactly you're trying to build?

There are a lot of tools out there that integrate with zoxide (see the bottom of the README for examples). The way they do it (which is the recommended way) is to run the zoxide command in a subprocess and pipe the output to your program.

`zoxide --help` should help get you started.

**Comment by code-IM-perfect** [comment]
I love the integration with yazi and was thinking of contributing towards adding integration to dolphin. I am just probing the feasibility of such an integration, and seeing the optional-dependencies of Dolphin, I'm not sure if they'll allow a non-kde dependency even if it is optional.

I want to make it clear that I am probing about it as an individual and have no affiliation with KDE itself and have not talked to anyone in KDE regarding this.

**Comment by ajeetdsouza** [comment]
You won't need any dependencies, just use it with `popen` and `pipe` as I described earlier - that's how yazi does it too. The manpages / help file should give you all the info you need to build a plugin, but feel free to create an issue if you have any questions!

**Comment by code-IM-perfect** [comment]
@ajeetdsouza I mean I would need zoxide as a dependency in order to `popen` zoxide, right?

**Comment by ajeetdsouza** [comment]
popen is not a library dependency - you can just attempt to launch the binary, if it fails you could prompt the user to install zoxide.
